### ISSUE TITLE
Bug, attack or just pushing the limits?

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1016]
As you hunt for the networking bug in 1.0.83, and all our nodes are Observers, all of my nodes had a high Ram usage, high cpu (I think 100% but docUI/termui seems to report incorrectly).

Bandwidth is moderate, a few Mbps, not even close to 100mbps per node.

![image](https://user-images.githubusercontent.com/16723548/72972188-aa227480-3dd3-11ea-8b8d-e74e07bda24f.png)

**Comment by soringp** [comment]
There are reports of nodes stuck on the same block, c5c3f2 (as discovered by George on TG)

**Comment by joesixpack** [comment]
I shut them all down.  They were eating up 100% cpu with no peers connected.

**Comment by joesixpack** [comment]
It's baaack!  Shutting down again.

**Comment by soringp** [comment]
Maybe there are just too many observers on shard 0.

This might be a coincidence but after I've turned off 7 nodes, observers on shard 0, my other 4 observers CPU usage went down.

**Comment by miiu96** [comment]
was a bug related witch cpu. now is fixed
