### ISSUE TITLE
Incompatibility with new Golang 1.14

### ISSUE THREAD

**Issue by viastake** [ElrondNetwork/elrond-go#1174]
The 1.0.89 release does not seem to compile with the very latest Golang version 1.14:
![image](https://user-images.githubusercontent.com/60931849/75594563-67665300-5a89-11ea-86d1-648dc3069c8c.png)

Forcing Golang 1.13.8 solves the issue:
![image](https://user-images.githubusercontent.com/60931849/75594607-8f55b680-5a89-11ea-8e84-15672e94e2aa.png)

**Comment by miiu96** [comment]
yes for the moment we are not fully compatible with the lastet version of Goland. we fix the scrips to use an older version of goland.

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please open a new issue if the problem persist.
