### ISSUE TITLE
Blanace of the node validator isn't shown in node termui

### ISSUE THREAD

**Issue by alexpatru** [ElrondNetwork/elrond-go#1175]
Elrond node version 1.0.89

In the termui viewer the blance it's 0, but if you check the explorer you can see aroun 11k ERDs.

Wallet address:  78f9b7345b85a6abb2ec076c84dcf439bb84e6c0ac98e270c66e9d7447b815b4

![Capture](https://user-images.githubusercontent.com/17834606/75610302-c7f0a100-5b18-11ea-9344-ed4f4049d811.PNG)

**Comment by miiu96** [comment]
for the moment in termui viewer the balance it's 0 because we disabled rewards estimation. we have a new version of economics (rewards are received at the end of the epoch). soon will be an update where rewards will be again estimated.

**Comment by alexpatru** [comment]
Ok. Thank you for your answer!

**Comment by iulianpascalau** [comment]
We should remove that estimation field from termui

**Comment by iulianpascalau** [comment]
Removed the field. Closing this issue. Thanks.
