### ISSUE TITLE
'division by zero' node crash of version 1.92

### ISSUE THREAD

**Issue by MarkWillems** [ElrondNetwork/elrond-go#1221]
Hello, 

The nodes (version=v1.0.92-0-g396af8cd8/go1.13.6/linux-amd64) crashes multiply time with this message:
 
INFO [2020-03-13 16:20:06.061] meta block has been committed successfully epoch=25 round=21305 nonce=10437 hash=6b5fb0...05af25
panic: division by zero

goroutine 14567 [running]:
math/big.nat.div(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00bce17c8, 0x1, 0x1, 0x0, ...)
        /usr/local/go/src/math/big/nat.go:648 +0x481
math/big.(*Int).QuoRem(0xc002269a18, 0xc002269a38, 0xc0022699f8, 0xc002269828, 0x0, 0x0)
        /usr/local/go/src/math/big/int.go:239 +0xbf
math/big.(*Int).Div(0xc002269a18, 0xc002269a38, 0xc0022699f8, 0x0)
        /usr/local/go/src/math/big/int.go:250 +0x6d
github.com/ElrondNetwork/elrond-go/epochStart/metachain.(*economics).ComputeEndOfEpochEconomics(0xc002e5ad80, 0xc006bce4e0, 0x8, 0xc00bce1680, 0xc00dc7e000)
        /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/epochStart/metachain/economics.go:111 +0xdd5
github.com/ElrondNetwork/elrond-go/process/block.(*metaProcessor).updateEpochStartHeader(0xc0044b8c80, 0xc006bce4e0, 0x0, 0x0)
        /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/process/block/metablock.go:678 +0x344
github.com/ElrondNetwork/elrond-go/process/block.(*metaProcessor).CreateBlock(0xc0044b8c80, 0x17179a0, 0xc006bce4e0, 0xc00b612de0, 0x0, 0x40, 0x40, 0x40, 0x42, 0x17179a0)
        /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/process/block/metablock.go:626 +0x165
github.com/ElrondNetwork/elrond-go/consensus/spos/bls.(*subroundBlock).createBlock(0xc006bf4430, 0x17179a0, 0xc006bce4e0, 0x0, 0x0, 0x84, 0xc00c5445a0, 0xa, 0x481c32)
        /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/consensus/spos/bls/subroundBlock.go:146 +0x114
github.com/ElrondNetwork/elrond-go/consensus/spos/bls.(*subroundBlock).doBlockJob(0xc006bf4430, 0x104a900)
        /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/consensus/spos/bls/subroundBlock.go:86 +0x2fc
github.com/ElrondNetwork/elrond-go/consensus/spos.(*Subround).DoWork(0xc00c38caa0, 0x1701c20, 0xc000490140, 0x0)
        /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/consensus/spos/subround.go:124 +0xe8
github.com/ElrondNetwork/elrond-go/consensus/chronology.(*chronology).startRound(0xc005cb5d40)
        /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/consensus/chronology/chronology.go:140 +0x1df
github.com/ElrondNetwork/elrond-go/consensus/chronology.(*chronology).StartRounds(0xc005cb5d40)
        /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/consensus/chronology/chronology.go:117 +0x38
created by github.com/ElrondNetwork/elrond-go/node.(*Node).StartConsensus
        /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/node/node.go:359 +0xa9d
 `

**Comment by miiu96** [comment]
we know about this bug. is fixed now . thanks for the help :)
