### ISSUE TITLE
Counter not working, consensus accepted 0 - v1.0.95

### ISSUE THREAD

**Issue by adrianromanbc** [ElrondNetwork/elrond-go#1247]
![WhatsApp Image 2020-03-18 at 20 24 12](https://user-images.githubusercontent.com/57146186/77000172-3c6c7200-6958-11ea-9e54-606cfc879378.jpeg)

**Comment by miiu96** [comment]
i have to take a look why the counter is not working

**Comment by LucianMincu** [comment]
Issue should be solved by this PR https://github.com/ElrondNetwork/elrond-go/pull/1306
