### ISSUE TITLE
node out of sync - restart doesn't help v1.0.95

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1255]
My node on Shard 4 is out of sync for over 12 hours. Restart didn't help.

![image](https://user-images.githubusercontent.com/16723548/77142615-58bbfc00-6a89-11ea-9046-7e8b9ca4f194.png)

The shard is producing blocks, there are enough validators, 53/58.

As expected, the rating is suffering, it's down to 25.

**Comment by soringp** [comment]
Later update, the blocks count has progressed:
The node is synching, but not reaching full sync:

![image](https://user-images.githubusercontent.com/16723548/77152958-9462c000-6aa1-11ea-98d2-8e342d04c456.png)

@iulianpascalau  do you need the database to investigate?

**Comment by LucianMincu** [comment]
Hi @soringp! 

This one is quite old. This should have been solved in the latest [releases](https://github.com/ElrondNetwork/elrond-go/releases/latest). 

Let us know if you still have issues related to sync process.
