### ISSUE TITLE
Problme after vps restore

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#1264]
Hello Team

I have the following problem

I have a Vps with 400 gb ssd, 12 core , and 32 gm ram, on which  i have 4 nodes.
 yesterday after a peak of 480 mbps , as it shows here
![image](https://user-images.githubusercontent.com/26198807/77175479-62665380-6acb-11ea-9c0c-f0384bc84e4e.png)
somehow the vps crashed. I have contacted the provider , they restarted it as i could not do it successful and the vps started again.

on resuming all of those 4 nodes which are running here, did not sync. i stared the problem around 10 am, and at 4 pm the situation is like this:

on all 4 modes :

node 1:
![image](https://user-images.githubusercontent.com/26198807/77175817-ddc80500-6acb-11ea-9b9c-b05253f0806a.png)

node 2:
![image](https://user-images.githubusercontent.com/26198807/77175919-ffc18780-6acb-11ea-886b-21a730e9b962.png)

node 3:

![image](https://user-images.githubusercontent.com/26198807/77176002-21227380-6acc-11ea-8989-7f22df51a71f.png)
 
node 4:

![image](https://user-images.githubusercontent.com/26198807/77176078-3ac3bb00-6acc-11ea-91f0-419d7a13db37.png)

at this moment none of these 4 nodes are synced.

 i mention that i have not reinstalled the  VPS, it just recovered after hard reset from the provider.

**Comment by miiu96** [comment]
this is a bug with epoch configuration, we working to fix it

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please open a new issue if the problem persist.
