### ISSUE TITLE
tempRating frozen, success/failure counters stuck to 0

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go#1266]
My 2 nodes on meta have reached and are keeping 100% rating, all 4 nodes on shards (shard 0, 3, 3, 4) lost rating in recent epochs and since the epoch before the current one their tempRating is frozen as they have 0 success but also 0 failures both as leader and as validator. Only metachain nodes have leader and validator success and failure counters still updating.

The two shard nodes that lost most rating (5%, both down to 91% now) are each sharing a machine with either of the two metachain nodes holding their 100% rating so they should actually be performing decently too.

Looking at all the network through the `/validator/statistics` endpoint of a node on metachain shows all except 60-something nodes (likely those on metachain) have success and failure counters stuck at 0, which explains why tempRating is also stuck.

I wonder if it has to do with something not keeping up with transactions in the pool being up in the millions now. We have reached higher TPS but have we ever had so full a pool?

Below is the termui output of one of the affected nodes.

![image](https://user-images.githubusercontent.com/62286558/77248736-0111c200-6c3c-11ea-86f4-a2d883c75cfc.png)

**Comment by ravenx29** [comment]
same here:
![image](https://user-images.githubusercontent.com/26198807/77249242-64095600-6c48-11ea-8f39-d1b1d4d10e44.png)

**Comment by flyingbasalt** [comment]
Another observation: while `/validator/statistics` still reports 

```
"nrLeaderSuccess": 0,
"nrLeaderFailure": 0,
"nrValidatorSuccess": 0,
"nrValidatorFailure": 0,
```

and termui continues showing warnings, it seems the blocks do keep getting signed, e.g. block ec483b9028f8b31152fcc14f14fcbc5dd3266701ffe0d601db7ae88d5e37312a lists my validator above (key 29e18fd2e7d87abed ...) in the in the consensus group.

**Comment by raduchis** [comment]
Can be reproduced and will be fixed. Nodes on shards do not have the information about rating, that is computed by meta.

**Comment by iulianpascalau** [comment]
fixed as of today. v1.1.0
