### ISSUE TITLE
sync not happend after node reboot

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#1267]
I had to reboot one of my nodes, after rebooting the node is not syncing ( staying like this for a while )
here a print screen 
![image](https://user-images.githubusercontent.com/26198807/77249183-ff4dfb80-6c47-11ea-9f82-66f9a2176bf6.png)

**Comment by iulianpascalau** [comment]
This should be fixed as of today, 2020.05.18. Please open a new issue if the problem persists.
