### ISSUE TITLE
Version v1.0.96 have block nonce and consensus round stuck

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#1268]
The current version (v1.0.96 ) has many of the block nonce and consensus round stuck up without any movement with an observation of more than 20 minutes from different shards. The highlighted in yellow remain unchanged for several minutes

**Screenshot from shard 0**
![image](https://user-images.githubusercontent.com/7301249/77256488-eefd4700-6c6e-11ea-98f6-9b0b1fd43fe4.png)

**Screenshot for Shard Meta**
![image](https://user-images.githubusercontent.com/7301249/77256544-4d2a2a00-6c6f-11ea-810c-1e9c78088ab3.png)

**Screenshot from shard 1**
![image](https://user-images.githubusercontent.com/7301249/77256696-10126780-6c70-11ea-90e4-d40cf17500ae.png)

I thought there is already a mechanism for a shard to recover from this kind of scenario. But I waited patiently for several minutes without seeing any traces of recovery. A look right worth it

**Comment by iulianpascalau** [comment]
There were some sync bugs found in that version. This should be fixed as of today, 2020.05.18. Please open a new issue if the problem persists.
