### ISSUE TITLE
v1.0.98 showing Validator when Observer

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#1288]
Two nodes formerly Validators are now Observers after upgrading to v1.0.98.

One is actually an Observer on the explorer and shows up in the terminal as Observer.  953efad63d3f8dad2edc440795e7212c42f4ab6efd2c6abef3d0c2d5ae637e73cc28e242f17445a2902fd1832aeb1b17cebad7f27798b6b7b4cbded2f483e8170a38a6157bb0d77b9d1f4001e2721722ab09ebce2a2c8f0f602bb766b0547f14

The other is actually an Observer on the explorer but shows up in the terminal as Validator.
581c86ab4f96afeb6b19f6f71ce6e14bf9f08e699e37d1369bca50e1b3e0aadbc80c011fba3cbdf353c0819a5fa42d0f40f9b57f4fa877716455594c5bc4765267f2b814045c8334521a58ff8db4293fa60bc282a0320afc30cd6391ca2eef07

**Comment by joesixpack** [comment]
Presuming 581c86 is on the pool waiting list, then suggestion to change status to "Waiting" or such in the terminal.

**Comment by miiu96** [comment]
i will take a look and try to reproduce this problem, maybe in termUI console node type is displayed wrong.

**Comment by iulianpascalau** [comment]
@raduchis , any thoughts on this?

**Comment by raduchis** [comment]
@iulianpascalau will look into it. I'll try to reproduce the behaviour but it could be fixed already.

**Comment by miiu96** [comment]
problem was fixed in this pull request https://github.com/ElrondNetwork/elrond-go/pull/1765
