### ISSUE TITLE
Registered Validators are showing as an observers in the Explorer but Node dashboard shows otherwise

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#1290]
The screenshot below is showing 3 validators as observers from the explorer. Only one of the four is seeing as an observer but this is not the case in the node dashboard
![image](https://user-images.githubusercontent.com/7301249/77512466-63083c80-6e73-11ea-81e8-eeee6ba8bcc6.png)

Below are the node screen confirming all to be validators. You might have a look what really went wrong either it is a synchronization issue or otherwise
**First node:** 
![image](https://user-images.githubusercontent.com/7301249/77512541-86cb8280-6e73-11ea-91c2-07901bff43b1.png)

**Second node:**
![image](https://user-images.githubusercontent.com/7301249/77512615-acf12280-6e73-11ea-89e9-9314fbc434a1.png)

**Third node:**
![image](https://user-images.githubusercontent.com/7301249/77512674-ce520e80-6e73-11ea-9d17-8636f03be802.png)

**Fouth node:**
![image](https://user-images.githubusercontent.com/7301249/77512760-efb2fa80-6e73-11ea-9876-aa78b4d98419.png)

**Comment by miiu96** [comment]
thank you for the feedback. i will try to reproduce this problem.

**Comment by raduchis** [comment]
fixed
