### ISSUE TITLE
Unable to create directory and files (probably sudoer issue)

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#1291]
Is there any final solution that can be provided for sudoer that required permission before some file can be created?
![image](https://user-images.githubusercontent.com/7301249/77513236-ed9d6b80-6e74-11ea-9b0d-ba931e065bde.png)

![image](https://user-images.githubusercontent.com/7301249/77513271-fa21c400-6e74-11ea-9fc1-1b8106dde746.png)

**Comment by iulianpascalau** [comment]
This is annoying. Maybe we can replace the L14 from https://github.com/ElrondNetwork/elrond-go-scripts-v2/blob/master/config/variables.cfg to something like `CUSTOM_HOME=~/$who` ? @valentin-lup

**Comment by raduchis** [comment]
fixed
