### ISSUE TITLE
Epoch number reported by termui lags behind INFO messages

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go#1292]
I've noticed this in the past but stopping and restarting termui used to be enough to get an updated epoch nr. displayed but this time it does not. However the info messages in the log show the correct epoch number.

![image](https://user-images.githubusercontent.com/62286558/77529295-a1135980-6e8f-11ea-92bb-46d3d3450b29.png)

**Comment by iulianpascalau** [comment]
@miiu96

**Comment by bogdan-rosianu** [comment]
Hi! A fix was done for this issue and it's currently in pull request.
