### ISSUE TITLE
node enrolled as validator shows errors

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#1293]
One of my nodes wich is displayed as validator ( not the one who is in standby) shows the folowing error.
![image](https://user-images.githubusercontent.com/26198807/77530175-9a89df80-6e99-11ea-9a3e-7d1949a9b57c.png)

![image](https://user-images.githubusercontent.com/26198807/77530233-ae354600-6e99-11ea-8124-3873b0f112c2.png)
![image](https://user-images.githubusercontent.com/26198807/77530352-dc1a8a80-6e99-11ea-99c5-82a6e19affa9.png)

other of my 2 nodes , who are in stand by show the same error

![image](https://user-images.githubusercontent.com/26198807/77530417-f94f5900-6e99-11ea-8eb1-496ca8b63877.png)
![image](https://user-images.githubusercontent.com/26198807/77530507-1e43cc00-6e9a-11ea-85ae-18cf21738d9e.png)
![image](https://user-images.githubusercontent.com/26198807/77530535-2bf95180-6e9a-11ea-879f-97ffb34f4408.png)

**Comment by iulianpascalau** [comment]
Should have been corrected as of today, 2020.05.14.
