### ISSUE TITLE
Proposal: Restrict transaction to have min value between 0.0001 and our maximum balance up to 8 decimals

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#1298]
Hi i see Dr. Delphi attack but can you restrict it value to have minimum amount instead of 0?

https://explorer.elrond.com/transactions/8e0e4a708d1bf9ce9273766dc8435084b8ff1cc814656c8c60dd7021d9cfb13a

you can gave warning in the tx forms on the wallet administration page, i know we will have a future wallet, but just incase this feature is still left behind, i try to give a note here, so #nobodyleftbehind, thank you

**Comment by iulianpascalau** [comment]
Won't do. Someone might just want to send 0 as value but call a SC or just notarize some data on the blockchain. Closing.
