### ISSUE TITLE
node rating going down

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#1307]
I have the folowing problem, my node rating is only going down, it is because of  the not working  metrics? the node is running on VDS ( not contabo based) with more then enough resources.
![image](https://user-images.githubusercontent.com/26198807/77685455-2425d400-6fa4-11ea-9345-4426c0368c04.png)
![image](https://user-images.githubusercontent.com/26198807/77685548-43bcfc80-6fa4-11ea-8251-274f57802cd2.png)

**Comment by iulianpascalau** [comment]
There were some sync issues with that version - that is why your node was left behind and ratings were going down. Should be fixed by now, 2020.05.18. If the problem persists, please open a new issue. Thanks.
