### ISSUE TITLE
nodes going offline, and not sync

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#1308]
2 of my nodes, wich are still running goes off line in the bot ant not sync in termui

![image](https://user-images.githubusercontent.com/26198807/77690330-cb5a3980-6fab-11ea-8a8b-fbac58437e40.png)
![image](https://user-images.githubusercontent.com/26198807/77690439-f3e23380-6fab-11ea-88d6-99c4be0fab83.png)

**Comment by elrondscammer2** [comment]
Beniamin Mincu 
ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
  ERD BIG DUMP SELL NOW ...

**Comment by iulianpascalau** [comment]
Those nodes are having connection issues. Should be fixed by now, 2020.05.18. Please open a new issue if the problem persists. Reference PR #1553  . Thanks
