### ISSUE TITLE
after restart not resync, with  key error

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#1310]
I had to restart my vps, as my 2 nodes the bot showed me they go offline, they were on but not synced as i stated earlier, after restart after 4 -5 min in which node was syncing , it showed my synchronized for 1 sec , and i catch the eror in log file **, could not get validator public key**, and goes again in _curently syncing mode_.
![error](https://user-images.githubusercontent.com/26198807/77699619-627abd80-6fbb-11ea-96e1-1cba708d2a16.jpg)

**Comment by iulianpascalau** [comment]
That was a leftover WARN message. It was placed on DEBUG level by now. Thanks.
