### ISSUE TITLE
CPU Spiking on Internet Down

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#1329]
Making machine sluggish.

![image](https://user-images.githubusercontent.com/23145642/78115714-10210e80-73b8-11ea-9e46-7ab4636d9da1.png)

**Comment by joesixpack** [comment]
No better on Internet resumption:

![image](https://user-images.githubusercontent.com/23145642/78116536-4d39d080-73b9-11ea-8d73-5642b8cc651a.png)

**Comment by iulianpascalau** [comment]
Should be fixed as of this moment, 2020.05.18. Please open a new issue if the problem persists, reference PR #1553
