### ISSUE TITLE
v1.0.100 Fails to Upgrade/Build: Missing Dependencies?

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#1342]
![image](https://user-images.githubusercontent.com/23145642/78314089-bdf20180-750d-11ea-8feb-920b96434fcc.png)

![image](https://user-images.githubusercontent.com/23145642/78314239-31940e80-750e-11ea-92cf-895bb1aa0240.png)

sudo apt install gcc-5 g++-5

**Comment by joesixpack** [comment]
Think its aborting here...

![image](https://user-images.githubusercontent.com/23145642/78314425-c39c1700-750e-11ea-9c1b-5044322e8d23.png)

**Comment by joesixpack** [comment]
The lack of building is due to go v1.14 being installed on the system through a sneaky backport PPA.

**Comment by joesixpack** [comment]
I'm wondering about unattended upgrades on Ubuntu could be upgrading to incompatible versions also.

**Comment by valentin-lup** [comment]
Strange. Go version is pegged at 1.13.5 in Scripts V2 since 28.02.2020...

**Comment by joesixpack** [comment]
Well, it wont install 1.13.5 if it dectects at least that version is already available, so risk is winding up with three copies as in my case: in elrond's path, in apt path and in custom PPA path.  Whoever wins is probably first in the PATH.

**Comment by joesixpack** [comment]
And I probably do need go1.14 for something else, but it escapes me at the moment.

**Comment by valentin-lup** [comment]
Soon we'll have Scripts V3 released and those will work with prebuilt binaries... so no need for you to have multiple versions of Go installed :)

**Comment by elrondscammer1** [comment]
BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ER

**Comment by elronscam8** [comment]
BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
  We want our money back, Romanian sons of bitches.

**Comment by iulianpascalau** [comment]
Closing as it is fixed by now to compile with both 13.x and 14.x versions. If the problem persists, please open a new issue.
