### ISSUE TITLE
v 1.0.100 update problem with update and validator key

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#1343]
Even the autoupdate is enabled the nodes did not update, i have 6 nodes wuith same setings five of them failed to update
![image](https://user-images.githubusercontent.com/26198807/78328838-cf2c2400-7588-11ea-996b-3f54915f2701.png)
![image](https://user-images.githubusercontent.com/26198807/78328859-dd7a4000-7588-11ea-8943-065f4f4fc03e.png)
![image](https://user-images.githubusercontent.com/26198807/78328883-ee2ab600-7588-11ea-9ed6-8ff1ec0ade9f.png)
![image](https://user-images.githubusercontent.com/26198807/78328911-fd116880-7588-11ea-84b7-e81a0a135b87.png)

at one of  the nodes, the problem with **can not get validatorpublickey**  came back
![image](https://user-images.githubusercontent.com/26198807/78329079-6e511b80-7589-11ea-90f6-a0f7caae786b.png)

**Comment by ravenx29** [comment]
Te reboot of the vps did not help them to update

**Comment by ravenx29** [comment]
the only node wich update himself was a node wich has the user "ubuntu" , so the rewriting of variables.cfg din not "upset" him
![image](https://user-images.githubusercontent.com/26198807/78330637-1fa58080-758d-11ea-81e0-fe4945d59d7e.png)
![image](https://user-images.githubusercontent.com/26198807/78330662-2fbd6000-758d-11ea-9cb3-9352f02fb8b8.png)

**Comment by ravenx29** [comment]
After correcting in variables.cfg  and changing with the correct user name , the nodes updated and struggling to sync.

one of them synced with error i never seen till now, plus with the validator key error
![image](https://user-images.githubusercontent.com/26198807/78331335-80818880-758e-11ea-8b7f-70d60f15064f.png)

**Comment by ravenx29** [comment]
All of the sync after 20 min, all with errors, different errors:
![image](https://user-images.githubusercontent.com/26198807/78332791-5da4a380-7591-11ea-8f40-087f6501b15f.png)
![image](https://user-images.githubusercontent.com/26198807/78332879-8036bc80-7591-11ea-8382-409bc7759a17.png)
![image](https://user-images.githubusercontent.com/26198807/78332958-aa887a00-7591-11ea-852c-336b4c36c2f8.png)

**Comment by iulianpascalau** [comment]
@valentin-lup , related with #1291 ?
