### ISSUE TITLE
proposal: made a dark / night view mode for the browser wallet

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#1349]
hello i found this useful when you need to access it in the night when our eyes is not quite good to see more light again,,

preview.
![darkview](https://user-images.githubusercontent.com/44559893/78401409-e3bcfa80-7622-11ea-8667-63ffeaa38df8.png)

**Comment by raduchis** [comment]
ok! 10x

**Comment by scraido** [comment]
thanks
