### ISSUE TITLE
v 1.0.101 trie storage manager: newSnapshotTrie    error = key not found (MacOS)

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#1350]
I am seeing these errors in the node log:
trie storage manager: newSnapshotTrie    error = key not found

I am seeing this on my MacOS and Ubuntu nodes:

elrond@ubuntu-s-4vcpu-8gb-ams3-01:~$ journalctl --unit elrond-node-0 -o cat | grep -B1 -A1 ERROR
INFO [2020-03-24 18:08:19.476] shard block has been committed successfully epoch=0 round=112 nonce=104 shard id=2 hash=18bf89...dc0147
ERROR[2020-03-24 18:08:19.477] trie storage manager: newSnapshotTrie    error=key not found
INFO [2020-03-24 18:08:19.746] shard block has been committed successfully epoch=0 round=115 nonce=105 shard id=2 hash=604dfb...6a95e9
--
INFO [2020-03-24 18:08:35.360] shard block has been committed successfully epoch=0 round=220 nonce=204 shard id=2 hash=7a09cb...cd2f9e
ERROR[2020-03-24 18:08:35.360] trie storage manager: newSnapshotTrie    error=key not found
INFO [2020-03-24 18:08:35.645] shard block has been committed successfully epoch=0 round=222 nonce=205 shard id=2 hash=23850f...a5a0e3
--
INFO [2020-03-24 18:08:53.323] shard block has been committed successfully epoch=0 round=337 nonce=304 shard id=2 hash=e2c985...b3aa7c
ERROR[2020-03-24 18:08:53.324] trie storage manager: newSnapshotTrie    error=key not found
INFO [2020-03-24 18:08:53.424] shard block has been committed successfully epoch=0 round=338 nonce=305 shard id=2 hash=5105d0...d49f79
--
INFO [2020-03-24 18:09:07.697] shard block has been committed successfully epoch=0 round=444 nonce=403 shard id=2 hash=860f93...82f3ff
ERROR[2020-03-24 18:09:07.699] trie storage manager: newSnapshotTrie    error=key not found
INFO [2020-03-24 18:09:07.812] shard block has been committed successfully epoch=0 round=445 nonce=404 shard id=2 hash=f595d3...605fe7
--
INFO [2020-03-24 18:09:20.431] shard block has been committed successfully epoch=0 round=555 nonce=504 shard id=2 hash=b9d03a...ec7051
ERROR[2020-03-24 18:09:20.432] trie storage manager: newSnapshotTrie    error=key not found
INFO [2020-03-24 18:09:20.516] shard block has been committed successfully epoch=0 round=556 nonce=505 shard id=2 hash=540d6d...c61358
--
INFO [2020-03-24 18:11:00.132] shard block has been committed successfully epoch=1 round=865 nonce=699 shard id=2 hash=3da7de...95b482
ERROR[2020-03-24 18:11:00.136] trie storage manager: newSnapshotTrie    error=key not found
INFO [2020-03-24 18:11:00.308] shard block has been committed successfully epoch=1 round=866 nonce=700 shard id=2 hash=5c7eee...356681
elrond@ubuntu-s-4vcpu-8gb-ams3-01:~$

**Comment by frankf1957** [comment]
Beagle:node-0 elrond$ ./node -v
Elrond Node CLI App version v1.0.101-0-g294d8ef8a/go1.13.8/darwin-amd64

**Comment by elronscam8** [comment]
Crooked sons of bitches. Give us our money back.

**Comment by elronscam8** [comment]
BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
  We want our money back, Romanian sons of bitches.

**Comment by BeniaminDrasovean** [comment]
This problem was fixed in the following PR: https://github.com/ElrondNetwork/elrond-go/pull/1461.
