### ISSUE TITLE
observer node on meta stopped syncing: round keeps being rolled back

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go#1353]
I run an observer on meta for my monitoring. We are in epoch 43 right now, and it has been unable to sync since epoch 33. Restarting the node doesn't help.

![image](https://user-images.githubusercontent.com/62286558/78502663-7dd78c80-7762-11ea-8d91-d5afa9b293b3.png)

From the logs it seems round 19968 keeps being rolled back. Attached is a log from this morning. The log starts with the node being restarted, first rollback debug output at line 113.

[debug_log_observer_meta.zip](https://github.com/ElrondNetwork/elrond-go/files/4434203/debug_log_observer_meta.zip)

**Comment by elrondscammer2** [comment]
Crooked sons of bitches. Give us our money back.
 BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ER

**Comment by elronscam8** [comment]
BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
  We want our money back, Romanian sons of bitches.

**Comment by sasurobert** [comment]
This was a problem of shards remaining in an epoch which is too old, plus small issues on the restart - start in epoch process. It was resolved through a set of bugFixes. One such bugFix was this: https://github.com/ElrondNetwork/elrond-go/pull/1472
