### ISSUE TITLE
enhancement: support running two instances with same key

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go#1354]
Is running more than one instance using the same key officially supported? I could only find [one reference to duplicated validators](https://github.com/ElrondNetwork/elrond-go/pull/1316#discussion_r401475451) but I don't understand the implications.

It would be a very simple way of providing automatic failover in case of hardware or network failure. It also solves the issue with uptime during maintenance. From my testing it currently works.
```
machine    node keys  
1          3c2a08e1..., c41df4b6...
2          c887a3cc..., b348e399...
3          29e18fd2..., 938c9ad7...
4          c41df4b6..., b348e399..., 938c9ad7...
```
I have machines 1-3 of different specs and location, each running 2 validators. Since patch 1.0.99 I added a fourth machine running 3 instances which reuse the same keys as one validator for each of the other three machines. Everything seems to work as it should, and those keys used by 2 instances seem to accrue a small rating advantage over the non-duplicated node running on the same machine. Which makes sense as they have two horses in the race so to speak, and it rewards higher availability.

**Comment by soringp** [comment]
Multiple instances is not supported, and my testing also shows no penalty is enforced atm.

In the past signing an empty block with two node instances used to cause problems, and slashing was mentioned as penalty for this.

**Comment by newtmex** [comment]
@soringp so, is this a feature or a bug?

**Comment by soringp** [comment]
I'd say missing feature, probably not integrated into the current public version or disabled, slashing territory

**Comment by flyingbasalt** [comment]
As an update, I have kept running the same setup as above and I consistently see a small advantage in rating. By the time a key running on two instances reaches rating 100, the other key running on the same machine is around 97-98. But my reason for doing this is redundancy, particularly now that #1259 seems not to happen anymore with current 1.0.103.

**Comment by soringp** [comment]
It was just a matter of time until duplicate nodes would cause a fork: [https://github.com/ElrondNetwork/elrond-go/issues/1460](https://github.com/ElrondNetwork/elrond-go/issues/1460)

It looks like there's a bug in the fork mitigation mechanism, so it should be fixed and not cause a shard to die, but still, this can be considered malicious activity and subject to slashing.

**Comment by flyingbasalt** [comment]
I think slashing should be reserved for things that require running a modified source code. Misconfigurations may result in poor rating, but even that would be problematic if it can result from things like firing up a duplicated node. It will probably be the most common mistake, especially if people need to come up with more complex failover mechanisms than just running two instances 24/7 with the same key.

**Comment by flyingbasalt** [comment]
Closing this because running duplicated nodes will not be supported. In https://t.me/ElrondValidators/67809 @iulianpascalau explained:
> At the moment we are trying to make the network robust to double signing. We managed so far to keep it that way, the last issue encountered was triggered by double signing but the shard was crippled by a trie bug. In the near future we plan to implement a warning system to announce when a node did a double signing and also a slashing mechanism.

On **testnet only** it still helps to run some duplicated nodes to verify that the network reacts properly against double-signing.
