### ISSUE TITLE
sync stuck until process restart: 'account state is reverted to snapshot'

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go#1442]
Node b348e399... on v. 1.0.107 stopped syncing a couple of epochs ago. Attached log shows repeated forced rollbacks and 'account state is reverted to snapshot'. Stopping and restarting the node cleared the issue for now.

[sync-stuck.log](https://github.com/ElrondNetwork/elrond-go/files/4498796/sync-stuck.log)

**Comment by elronscam8** [comment]
ERD Scam Coin. Team ERD is a con man. Don't buy ERD. I send this message every day to everyone in the group. Prevent more people from being conned by sharing with you.

**Comment by iulianpascalau** [comment]
There were some issues on this version of the binary. Please open a new issue if the problem exists. Thanks.
