### ISSUE TITLE
v1.0.113 node will not start in observer mode - bootstrap error is timeout

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#1504]
The community has noticed issues starting the node in observer mode and have been reporting that it can take a lot of time, but that it will eventually start. 

I ran a test with my DestinationShardAsObserver set to 2, and my log level set to *:DEBUG.

The first message in the log is this:
INFO [2020-05-03 19:42:24.125]   starting node

The last message in the log is this:
ERROR[2020-05-03 19:52:50.221]   bootstrap return error

The node has failed to start after 10 minutes.  In the log we can see that the node spend all of it's time trying to do this:
requesting trie nodes from network       topic = accountTrieNodes shard = 2 num nodes = 1

**Comment by frankf1957** [comment]
I am getting this INFO message no matter what shard number I set in prefs.toml.

INFO [2020-05-03 19:15:00.852]   shard info                               started in shard = 4

**Comment by frankf1957** [comment]
Attaching log file.
[elrond-go-2020-03-05-19-42-24.log.gz](https://github.com/ElrondNetwork/elrond-go/files/4571483/elrond-go-2020-03-05-19-42-24.log.gz)

**Comment by frankf1957** [comment]
My validator running on MacOS with key 8fffa28d8e7a failed, and because of this issue I could not restart it.  I moved the validatorKey.pem to a VPS and it did manage to eventually start.

Actually, what happened is that the node would fail to start after 10 minutes and exit with bootstrap error.  systemctl would then automatically restart the node after a 3 second pause.  Eventually, after several attempts, the node did finally manage to start.

I feel that in this case we should not be relying on systemctl to restart, this should really be resolved in the node startup code.

**Comment by frankf1957** [comment]
Well, after all that effort, here is the final result for my validator. 

INFO [2020-05-04 13:18:53.735]   terminating at internal stop signal      reason = shuffledOut 
INFO [2020-05-04 13:18:53.745]   closing network connections...

**Comment by elrondscam2** [comment]
ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
  ERD BIG DUMP SELL NOW ...

**Comment by elrondscam6** [comment]
ERD Scam Coin. Team ERD is a con man. Don't buy ERD. I send this message every day to everyone in the group. Prevent more people from being conned by sharing with you.

**Comment by raduchis** [comment]
fixed
