### ISSUE TITLE
v1.0.113: panic: runtime error: index out of range [0] with length 0 (MacOS)

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#1520]
DEBUG[2020-05-06 17:29:36.027]   2020-05-06 17:29:36.023924355  ################################## ROUND 54896 BEGINS (1588786176) ################################## 
DEBUG[2020-05-06 17:29:36.028]   2020-05-06 17:29:36.029420355  ................................... SUBROUND (START_ROUND) BEGINS ................................... 
DEBUG[2020-05-06 17:29:36.030]   random source for the next consensus group rand = 935448..746316 
DEBUG[2020-05-06 17:29:36.030]   ComputeValidatorsGroup                   randomness = 353438..746316 consensus size = 63 eligible list length = 70 
DEBUG[2020-05-06 17:29:36.074]   step 0: preparing the round              leader = 4ef69a35b2d6 messsage =  
DEBUG[2020-05-06 17:29:36.100]   not in consensus group                   
DEBUG[2020-05-06 17:29:36.139]   2020-05-06 17:29:36.140298355  ...................................... SUBROUND (BLOCK) BEGINS ...................................... 
panic: runtime error: index out of range [0] with length 0

goroutine 15498 [running]:
github.com/shirou/gopsutil/process.(*Process).MemoryInfoWithContext(0xc00d463340, 0x55bf160, 0xc0000ca008, 0x0, 0x0, 0x0)
	/Users/elrond/go/pkg/mod/github.com/shirou/gopsutil@v0.0.0-20190731134726-d80c43f9c984/process/process_darwin.go:466 +0x270
github.com/shirou/gopsutil/process.(*Process).MemoryInfo(...)
	/Users/elrond/go/pkg/mod/github.com/shirou/gopsutil@v0.0.0-20190731134726-d80c43f9c984/process/process_darwin.go:458
github.com/ElrondNetwork/elrond-go/core/statistics/machine.(*MemStatistics).ComputeStatistics(0xc00cf04020)
	/Users/elrond/go/src/github.com/ElrondNetwork/elrond-go/core/statistics/machine/memStatistics.go:36 +0xd6
github.com/ElrondNetwork/elrond-go/cmd/node/metrics.registerMemStatistics.func1(0xc00cf04020)
	/Users/elrond/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/metrics/machineStatistics.go:48 +0x2b
created by github.com/ElrondNetwork/elrond-go/cmd/node/metrics.registerMemStatistics
	/Users/elrond/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/metrics/machineStatistics.go:46 +0x58
Beagle:logs elrond$

**Comment by frankf1957** [comment]
Attaching DEBUG log file.
[elrond-go-2020-06-05-17-19-12.log.gz](https://github.com/ElrondNetwork/elrond-go/files/4588616/elrond-go-2020-06-05-17-19-12.log.gz)

**Comment by elrondscam2** [comment]
Crooked sons of bitches. Give us our money back.
 BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ER

**Comment by iulianpascalau** [comment]
This is a new one. Thanks. Will search through it.
