### ISSUE TITLE
Meta nodes rating extremely low / out of sync - 1.0.113

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1522]
My meta nodes have a very low rating. This has been conformed by others as well, so all meta nodes might be affected by a bug.

Not all meta nodes were affected at the same time, some kept a good rating for a few days then went down, but one was struggling the entire time, here is the story of two nodes:

**Node "Three,s2"**

04.05.2020
![image](https://user-images.githubusercontent.com/16723548/81293281-b75b2a80-9075-11ea-854a-c141b29eec30.png)

05.05.2020 - Node in standby
![image](https://user-images.githubusercontent.com/16723548/81293333-d0fc7200-9075-11ea-946f-905b833245b9.png)

07.05.2020 - Observer, is this jail time?
![image](https://user-images.githubusercontent.com/16723548/81293390-f38e8b00-9075-11ea-8c69-4da22b19e327.png)

**Node "Ten.s6"**

04.05.2020
![image](https://user-images.githubusercontent.com/16723548/81293484-1751d100-9076-11ea-8f7a-10485e686dec.png)

05.05.2020
![image](https://user-images.githubusercontent.com/16723548/81293606-41a38e80-9076-11ea-87cb-d5b282e0dda2.png)

07.05.2020
![image](https://user-images.githubusercontent.com/16723548/81293635-4c5e2380-9076-11ea-8c43-9f491057b69e.png)

Second node experienced a huge rating drop, while the other failed to get a good rating from the beginning.

Ten.s6 is slightly out of sync, doesn't seem to reach the latest block, it is constanlty 2 blocks behind:

![image](https://user-images.githubusercontent.com/16723548/81294392-82e86e00-9077-11ea-8769-767031985918.png)

Three.s2 is out of sync as well, but by a wider margin:
![image](https://user-images.githubusercontent.com/16723548/81294861-28034680-9078-11ea-928c-661aa5874c6d.png)

They are still syncing, just not to the latest nonce.

**Comment by elrondbigscam** [comment]
ERD BIG DUMP SELL NOW ...ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.

**Comment by raduchis** [comment]
There was a problem with the metachain nodes and just every 3rd block was proposed correctly in the previous version. The rating decrease was correctly computed based on the fact that multiple blocks were missed. 

It should be fixed in v 1.0.114.
