### ISSUE TITLE
keybase and heartbeat not working properly - v1.0.114

### ISSUE THREAD

**Issue by josefcoap** [ElrondNetwork/elrond-go#1658]
I have 6 nodes, 2 of them are not visible on the explorer. And in heartbeat it appears like observer, but with termui I can see they working as validators. All of them have the Identity paremeter of keybase properly writen

![photo_2020-05-09_14-10-12](https://user-images.githubusercontent.com/53934875/81474049-4fd2e580-9203-11ea-80bf-76b5a8fa37b6.jpg)
![photo_2020-05-09_14-07-52](https://user-images.githubusercontent.com/53934875/81474052-506b7c00-9203-11ea-8028-1766670e5cb2.jpg)
![photo_2020-05-09_14-07-26](https://user-images.githubusercontent.com/53934875/81474054-51041280-9203-11ea-8f10-584d72f10e0e.jpg)
![photo_2020-05-09_14-07-04](https://user-images.githubusercontent.com/53934875/81474055-519ca900-9203-11ea-842f-21abb08f709d.jpg)
![photo_2020-05-09_14-12-34](https://user-images.githubusercontent.com/53934875/81474056-52353f80-9203-11ea-9bad-85dd24c159d0.jpg)
![photo_2020-05-09_14-11-38](https://user-images.githubusercontent.com/53934875/81474057-52cdd600-9203-11ea-9850-78acb21e5b46.jpg)
![Captura](https://user-images.githubusercontent.com/53934875/81474090-7d1f9380-9203-11ea-9ea6-95e948a5330a.PNG)

[elrond-go-2020-09-05-14-36-17.log](https://github.com/ElrondNetwork/elrond-go/files/4603471/elrond-go-2020-09-05-14-36-17.log)

**Comment by josefcoap** [comment]
It can be related with the issue:

#1537

This is the journalctl output, it seems that after some hours not working, the rating goes to zero and then the resuffle activates:

![Captura3](https://user-images.githubusercontent.com/53934875/81475102-3c774880-920a-11ea-9af1-1d8e28027c93.PNG)

**Comment by miiu96** [comment]
hello thank you for the feedback . we will take a look on this problem.
