### ISSUE TITLE
Automatic restarts of the elrond-node service - v1.0.114

### ISSUE THREAD

**Issue by josefcoap** [ElrondNetwork/elrond-go#1659]
In 2 nodes (in the same server), I have periodical restarts of the service. I can't figure why, but around 15:06 I have it tracked on the logs.

[elrond-go-2020-09-05-15-04-56.log](https://github.com/ElrondNetwork/elrond-go/files/4603494/elrond-go-2020-09-05-15-04-56.log)

**Comment by josefcoap** [comment]
we see with Lucian that it's the same behavior than this issue:

https://github.com/ElrondNetwork/elrond-go/pull/1537

And this is the journalctl output at the moment of the automatic restart:

![Captura3](https://user-images.githubusercontent.com/53934875/81475073-08038c80-920a-11ea-94f8-d7a13d9ba21e.PNG)

**Comment by elrondscam6** [comment]
ERD Scam Coin. Team ERD is a con man. Don't buy ERD. I send this message every day to everyone in the group. Prevent more people from being conned by sharing with you.

**Comment by elronscam8** [comment]
That's enough!! Cheating bastards.
The price keeps falling. People don't trust you. ERD doesn't buy. What do you boys do for a living?

Binance Delist/ Don't Buy ERD/ELROND / Erd scam coin / Erd big dump
ERD BIG DUMP SELL NOW ...ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
 
 Beniamin Mincu 
ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
  ERD BIG DUMP SELL NOW ...
 
 
 Crooked sons of bitches. Give us our money back.
 BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
 
  BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
  We want our money back, Romanian sons of bitches.
  
  Elrond was HACKED!
  Elrond announced that he had been hacked. Please don't buy ERD

**Comment by AdoAdoAdo** [comment]
This is part of handling node shuffling between shards, the node is re-started in the new shard whenever shuffling mechanism decided the node needs to be assigned to a different shard. It was the first step to verify the mechanism as a whole functions as expected.
The node soft-restart feature is in progress which will do reinitialisations internally without re-starting the process and will replace the above when finished.
