### ISSUE TITLE
[BUG] Web Wallet Invalid Transaction (Network @ v1.0.114)

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1740]
<details>
<summary>Invalid Transaction</summary>
<pre>
Application version: v1.0.114
Web Wallet
</pre>

I've created a new wallet from an existing seed. I've received the expected address for this seed.
I've requested 50000 xERD as the address has never been used.

Instead of Pending or Success, the transaction generated appears **Invalid** on the explorer.

https://explorer.elrond.com/transactions/69cdfd995e73c9cd5acb28fba91a54e00c34d377398416dfe4ac4cd825f2698b

![image](https://user-images.githubusercontent.com/16723548/81846598-049a3900-955b-11ea-9e12-fd129a0bef0b.png)

Is this a nonce issue?

From another address where I've had some funds, the Send transaction is not Invalid but stays at Pending, so the network might be down.

![image](https://user-images.githubusercontent.com/16723548/81846646-17ad0900-955b-11ea-9523-22d76b3e5002.png)

</details>

**Comment by LucianMincu** [comment]
Metachain is stuck. New release should be out in the next hour. 👍

**Comment by soringp** [comment]
![image](https://user-images.githubusercontent.com/16723548/81863016-3c14df80-9573-11ea-8949-306af06612ab.png)
