### ISSUE TITLE
reference for node running, page not found 

### ISSUE THREAD

**Issue by nysxah** [ElrondNetwork/elrond-go#1750]
In [Readme](https://github.com/ElrondNetwork/elrond-go/blob/master/README.md):

https://docs.elrond.com/start-a-validator-node/start-the-network

**Page Not Found**

> Follow the steps outlined **[here](https://docs.elrond.com/start-a-validator-node/start-the-network
> )**. This is because in order to join the testnet you need a specific node configuration.

**Comment by camilbancioiu** [comment]
Link updated. Thank you!
