### ISSUE TITLE
[FEAT] Explorer Proposal, please made explorer can search min. 2 keywords, coz i couldn't find any Xn

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#1751]
Feature for Explorer, coz i got a trouble find mine and must goes scroll all validator name because i couldn't find any X to n X1 - X4 (X5&X6 still not be on explorer, coz i just submit it a couple of days ago)

**Comment by raduchis** [comment]
will try to investigate this further

**Comment by scraido** [comment]
thanks
