### ISSUE TITLE
Observer bootstrap error - key not found - v1.0.115

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1754]
I've tried to start two observer nodes, on Shard 0 and Shard 1, with no db folder present.
I have a 'key not found' error during bootstrap on both.

![image](https://user-images.githubusercontent.com/16723548/82159177-2534fc80-9895-11ea-9d80-350191c989fa.png)

Shard 0
` INFO [2020-05-17 12:23:33.408]   starting node                            version = v1.0.115-0-g
40e42e696/go1.13.1/linux-amd64 pid = 32109
INFO [2020-05-17 12:23:33.428]   start time                               formatted = Wed May 13 20:00:00 UTC 2020 seconds = 1589400000
INFO [2020-05-17 12:23:33.430]   starting as observer node
INFO [2020-05-17 12:23:33.430]   shard info                               started in shard = 0
INFO [2020-05-17 12:23:33.529]   listening on addresses                   addr0 = /ip4/127.0.0.1/tcp/35163/p2p/16Uiu2HAmHhrp74BsoSSCcGau5WTFhqo$
INFO [2020-05-17 12:23:33.529]   waiting 20 seconds for network discovery...
WARN [2020-05-17 12:24:33.654]   received metablock is not of type epoch start error = not epoch start block
WARN [2020-05-17 12:24:37.885]   received metablock is not of type epoch start error = not epoch start block
WARN [2020-05-17 12:24:43.989]   received metablock is not of type epoch start error = not epoch
 start block
INFO [2020-05-17 12:24:45.583]   got consensus for epoch start metablock  len = 4
INFO [2020-05-17 12:24:45.612]   new nodes config is set for epoch        epoch = 0
WARN [2020-05-17 12:24:45.647]   Did not find nodesConfig                 epoch = 87
WARN [2020-05-17 12:24:45.677]   Did not find nodesConfig                 epoch = 88
ERROR[2020-05-17 12:25:50.864]   bootstrap return error                   error = getNodeFromDB
error key not found for key 985352253f39d863f60615a83cc66ad027aa7c7f7d8659379c99d84c018987dd`

Shard 1
`INFO [2020-05-17 12:00:11.256]   starting node                            version = v1.0.115-0-$
40e42e696/go1.13.1/linux-amd64 pid = 31834
INFO [2020-05-17 12:00:11.285]   start time                               formatted = Wed May 1$
 20:00:00 UTC 2020 seconds = 1589400000
INFO [2020-05-17 12:00:11.286]   starting as observer node
INFO [2020-05-17 12:00:11.286]   shard info                               started in shard = 1
INFO [2020-05-17 12:00:11.354]   listening on addresses                   addr0 = /ip4/127.0.0.$
/tcp/32837/p2p/16Uiu2HAkxNDt8sdt5re4z6MvVDiEgV3ig8gaUrPVn6GP9uUun2kE addr1 = /ip4/192.168.1.118$
tcp/32837/p2p/16Uiu2HAkxNDt8sdt5re4z6MvVDiEgV3ig8gaUrPVn6GP9uUun2kE
INFO [2020-05-17 12:00:11.354]   waiting 20 seconds for network discovery...
INFO [2020-05-17 12:00:33.561]   got consensus for epoch start metablock  len = 6
INFO [2020-05-17 12:00:33.638]   new nodes config is set for epoch        epoch = 0
WARN [2020-05-17 12:00:33.719]   Did not find nodesConfig                 epoch = 86
WARN [2020-05-17 12:00:33.765]   Did not find nodesConfig                 epoch = 87
ERROR[2020-05-17 12:01:11.909]   bootstrap return error                   error = getNodeFromDB
error key not found for key 076c4187f7c1d2db275a3cd26ea65ec0aadd75581d4345a751fd872c551998f0
ERROR[2020-05-17 12:01:11.909]   getNodeFromDB error key not found for key 076c4187f7c1d2db275a$
cd26ea65ec0aadd75581d4345a751fd872c551998f0`

The problem doesn't happen if I take a validator's db, for the same shard!

This could be related to a different issue but the error is different: https://github.com/ElrondNetwork/elrond-go/issues/1504

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.115-0-g
40e42e696/go1.13.1/linux-amd64
Hosting VPS: @home
</pre>
</details>

**Comment by LucianMincu** [comment]
Fixed in [En 6453 fix trie sync](https://github.com/ElrondNetwork/elrond-go/pull/1775).
Pending deployment on testnet.

**Comment by iulianpascalau** [comment]
will close for now, please reopen if the problem persists.
