### ISSUE TITLE
[BUG] Malformed staking action should be logged as warning

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#1786]
The following error occured on one of the nodes. It seems like it's the result of a malformed staking request to the network.
Shouldn't this type of event be logged at most at warning level, as it seems it is not an error of the node itself.

<pre>
May 22 06:16:21 erd5 node[3996]: #033[0;31mERROR#033[0m[2020-05-22 03:16:21.838]   could not create validator info from body - do nothing on nodesCoordinator epochStartPrepare
</pre>

<details>
<summary>Executing details</summary>
<pre>
Checked: /var/log/syslog
Application version string: v1.0.117
Hosting VPS: private
</pre>
</details>

**Comment by sasurobert** [comment]
This is not a critical error. It appears after a revert state to block, and the nodesCoordinator does not need to recompute the new config for the selected epoch, as it is already computed. However the nodescoordinator will get a nil body, thus returns from computation. It is only a log. Will fix the log.

**Comment by arcsoft-ro** [comment]
Thanks @sasurobert this will be helpful for reducing the false positives on log monitoring.
