### ISSUE TITLE
Web wallet - cannot send funds to certain addresses v1.0.117

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1791]
I cannot send funds from erd1veteran8tuf357zh73gp8zcf2wsk0h9jsnh27dcwe05xnr6urrjsswhkdf to erd15x3ljq8myh0uc9ep47vkr766gaz9r5la9n270wp6c8kk5rgh4mnsjgwep7.

![image](https://user-images.githubusercontent.com/16723548/82697333-65b7c000-9c71-11ea-9d48-7b130dc0cc4b.png)

Invalid: https://explorer.elrond.com/transactions/a7e9b141812ee64aa76e541edea7af1fc01466c19056347c7b53ade7bde1cbde 

I suspect that the web wallet might not calculate the destination shard id correctly, given the new setup with 4 shards instead of 5. Or it could be something else entirely :)

The transaction doesn't get published/accepted.

Transferring to a different address worked just fine:
 
![image](https://user-images.githubusercontent.com/16723548/82697236-2f7a4080-9c71-11ea-9d0b-11c2939b4d39.png)

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.117
Hosting VPS: web wallet
</pre>
</details>

**Comment by LucianMincu** [comment]
@soringp is this still valid for the current testnet version ?

**Comment by soringp** [comment]
All good now @LucianMincu, both from the same shard and from a different shard:

![image](https://user-images.githubusercontent.com/16723548/82931166-264de400-9f8f-11ea-996f-3fc30b06dcca.png)

![image](https://user-images.githubusercontent.com/16723548/82931222-3ebdfe80-9f8f-11ea-910b-47ffcd261b17.png)

Thanks
