### ISSUE TITLE
[BUG] Web Wallet - Smart Contract transaction status is not updated

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#1793]
After an SC transaction is initiated, it's status is PENDING, but regardless of the final result (Success or Not Executed) the transaction status is not updated in the wallet.

![1](https://user-images.githubusercontent.com/37418817/82739321-6a4ea800-9d47-11ea-95e1-dbf2420cf9ab.jpg)
![2](https://user-images.githubusercontent.com/37418817/82739322-6ae73e80-9d47-11ea-829c-243ee85cf916.JPG)

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.118
Hosting VPS: private
</pre>
</details>

**Comment by LucianMincu** [comment]
Done! Thanks for pointing out!

![Screen Shot 2020-05-26 at 6 43 53 PM](https://user-images.githubusercontent.com/30302419/82927623-45de1000-9f81-11ea-8c69-1d9611256ec3.png)

https://explorer.elrond.com/transactions/26f86f6e5e5dcda517c9d0b345c411fa15cf6b31153af737696093b619270805
