### ISSUE TITLE
[BUG] Node statistcs API does not return data

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#1794]
The node statistics API endpoint does not return data, except the "roundTime" and the "nrOfShards".

<pre>
{
  "statistics": {
    "liveTPS": 0,
    "peakTPS": 0,
    "blockNumber": 0,
    "roundNumber": 0,
    "roundTime": 6,
    "averageBlockTxCount": 0,
    "totalProcessedTxCount": 0,
    "shardStatistics": [
      {
        "liveTPS": 0,
        "averageTPS": null,
        "peakTPS": 0,
        "currentBlockNonce": 0,
        "totalProcessedTxCount": 0,
        "shardID": 0,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 0
      },
      {
        "liveTPS": 0,
        "averageTPS": null,
        "peakTPS": 0,
        "currentBlockNonce": 0,
        "totalProcessedTxCount": 0,
        "shardID": 0,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 0
      },
      {
        "liveTPS": 0,
        "averageTPS": null,
        "peakTPS": 0,
        "currentBlockNonce": 0,
        "totalProcessedTxCount": 0,
        "shardID": 0,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 0
      },
      {
        "liveTPS": 0,
        "averageTPS": null,
        "peakTPS": 0,
        "currentBlockNonce": 0,
        "totalProcessedTxCount": 0,
        "shardID": 0,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 0
      },
      {
        "liveTPS": 0,
        "averageTPS": null,
        "peakTPS": 0,
        "currentBlockNonce": 0,
        "totalProcessedTxCount": 0,
        "shardID": 0,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 0
      }
    ],
    "lastBlockTxCount": 0,
    "nrOfShards": 5
  }
}

</pre>

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.118
Hosting VPS: private
</details>

**Comment by LucianMincu** [comment]
Related to #1787 cc @bogdan-rosianu

**Comment by bogdan-rosianu** [comment]
Hello ! 
That API endpoint only contains relevant data when the is in `metachain` and the `elastic search indexer` is enabled. 
We will discuss what we'll do with that endpoint.

Thank you !

**Comment by bogdan-rosianu** [comment]
Update: now the endpoint will show relevant data even if elastic search indexer is disabled. However, it is still available only for metachain nodes. The fix is in testing

**Comment by iulianpascalau** [comment]
Will close for now. Please open a new issue if the problem persists. Thanks.
