### ISSUE TITLE
[FEAT] Explorer: Display icon and validator name on node page

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1805]
It would be nice to display the keybase identity for a registered node, icon + name in this section:

![image](https://user-images.githubusercontent.com/16723548/82887320-840f0b80-9f50-11ea-80f5-b55d07089b2b.png)

**Comment by LucianMincu** [comment]
Sure! Good idea! Will come back once it's ready!

**Comment by soringp** [comment]
I see there has been a development for this, identity appears for an eligible validator: 

![image](https://user-images.githubusercontent.com/16723548/83638828-6fff8580-a5b2-11ea-9b35-e9a1d073577a.png)

How about for a waiting validator? Is it's identity ignored until it becomes eligible?

![image](https://user-images.githubusercontent.com/16723548/83638600-0e3f1b80-a5b2-11ea-897c-a068fa909b06.png)

The identity is present on heartbeat:

![image](https://user-images.githubusercontent.com/16723548/83638702-3890d900-a5b2-11ea-9d0c-9108a6983066.png)

Actually I have a waiting validator showing the logo, so it might be related to the fact that I've recently staked the node.
![image](https://user-images.githubusercontent.com/16723548/83638943-a0472400-a5b2-11ea-814f-fa8541f53906.png)

The new one is not showing on the validators list under v4nitylab5 either.

**Comment by soringp** [comment]
Don't forget to upload any new keys to keybase kids 😉

**Comment by LucianMincu** [comment]
Done. Please note that this is still work in progress but it's a matter of time until things will be again at the next level on the validator page as well.

![Screen Shot 2020-06-11 at 6 37 38 PM](https://user-images.githubusercontent.com/30302419/84415250-cacc5900-ac12-11ea-871d-8d40570c5213.png)
