### ISSUE TITLE
The "Bored Wale" attack v1.0.118

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1822]
**ERD spent**: 625.000.000

**The plan**: stake enough nodes and keep them offline, see what happens until they get jailed 

**My question**: will the epoch change?

**Actual outcome**: Metachain stuck at block 86100

![image](https://user-images.githubusercontent.com/16723548/83240292-dd21ae00-a1a1-11ea-8092-fd50f7ec7310.png)

I have staked 250 "eb01a" nodes. First 100 batch got through and they became eligible validators:

![image](https://user-images.githubusercontent.com/16723548/83241441-82895180-a1a3-11ea-9fab-8eee74072200.png)

The second batch of nodes didn't become eligible, there are still >66% nodes online in every shard.

This attack was possible on Testnet because we have unlimited funds at disposal, so unless you have some serious cash to burn or risk losing to slashing, I don't think it's a risk for Mainnet.

It's up to you to decide the level of success for this attack, but it did affect the epoch change.

Rating is slowly decreased, but it will still take a long time to get to jail time. The worst of the 250 is 39, after 10 hours. 

Bored whale out! (●'◡'●)

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.118-0-ga20faf818/go1.13.1/linux-amd64
Hosting VPS: none needed
</details>

**Comment by soringp** [comment]
I've enabled my meta nodes from wave 1 (from first 100), block production resumed on meta, then all my other 150 new nodes, all offline, became eligible so this is how it looks now:

![image](https://user-images.githubusercontent.com/16723548/83266782-f9d2db80-a1cb-11ea-9f9d-f563c098b999.png)

Is it ok to have all the new nodes activated at once? Half of the total nodes are waiting now?

I cannot activate all the 250 nodes so all shards are done!

End of mission :) mostly educational

**Comment by iulianpascalau** [comment]
This was a bit out of specs attack. However, we are planning to improve the mechanism that is responsible with adding new peers.

**Comment by sasurobert** [comment]
This attack is possible in any PoS, dPoS chains if the attacker has unlimited funds. In this case, having all those testnet ERDs for free, you did a nothing at stake attack. This type of behavior is mitigated through the incentives paid to validators and the slashing to their stake when they are not online. This attack vector is furthermore reduced in case of Elrond when the Auction will be activated. It will cost much more (more than existing non-locked tokens) to takeover the network or one of the shards.

**Comment by soringp** [comment]
7/ - Fixed sort ascending of validators based on index that could influence the order in which the validators were taken from the waiting lists and added to the eligible lists. This could also have influenced the stake/unstake order

Looks like my attack succeeded because of this. Bug out!
