### ISSUE TITLE
node on home pc logging on/off random

### ISSUE THREAD

**Issue by grazzza** [ElrondNetwork/elrond-go#1826]
[logfile grazzza home.txt](https://github.com/ElrondNetwork/elrond-go/files/4706005/logfile.grazzza.home.txt)
BoN monitor BoT, [30.05.20 13:41]
⭕️ Node offline - grazza home

BoN monitor BoT, [30.05.20 13:41]
✅ Node online - grazza home

BoN monitor BoT, [30.05.20 14:31]
⭕️ Node offline - grazza home

BoN monitor BoT, [30.05.20 14:31]
✅ Node online - grazza home

BoN monitor BoT, [30.05.20 15:13]
⭕️ Node offline - grazza home

BoN monitor BoT, [30.05.20 15:14]
✅ Node online - grazza home

BoN monitor BoT, [30.05.20 15:51]
⭕️ Node offline - grazza home

BoN monitor BoT, [30.05.20 15:51]
✅ Node online - grazza home

**Comment by LucianMincu** [comment]
`DEBUG[2020-05-30 09:00:45.609]   error connecting to seeder               seeder = /dns4/gateway.battleofnodes.com/tcp/10000/p2p/16Uiu2HAmFKvSukM3DAHkLj2k9g5zn3ZSqdPSAwSxBPsKgiVSC8DF error = failed to dial 16Uiu2HAmFKvSukM3DAHkLj2k9g5zn3ZSqdPSAwSxBPsKgiVSC8DF: all dials failed
`

This was most probably related to seednode reaching it's maximum open file limit of 1024 (default OS value) when network size extended above 1000 nodes. 
Checks have been set and built in all the critical services where higher limits are required.

Thanks for sharing this. 🙏
