### ISSUE TITLE
on node shows more accepted then signed blocks

### ISSUE THREAD

**Issue by grazzza** [ElrondNetwork/elrond-go#1827]
[logfile signedaccepted blockz vulture.txt](https://github.com/ElrondNetwork/elrond-go/files/4706035/logfile.signedaccepted.blockz.vulture.txt)

![image](https://user-images.githubusercontent.com/36407272/83334058-2f4af800-a2a4-11ea-945e-96fdb237f7e7.png)

**Comment by bogdan-rosianu** [comment]
Hello! Was your node restarted meanwhile or something like this?

**Comment by grazzza** [comment]
Hello Bogdan
Sorry for responding so late. I really have no idea why this did happen.
Now I'm running 6 nodes in BoN and again 1 node shows more accepted then
proposed blocks
No idea why.
Grtz George Kardaun

Op do 4 jun. 2020 om 10:37 schreef bogdan-rosianu <notifications@github.com

**Comment by iulianpascalau** [comment]
should be fixed by now, as of v1.1.0
