### ISSUE TITLE
Node terminated with stop signal after re-stake v1.0.122

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1831]
I have unstaked a genesis node, it went from validator to observer and stayed online.

I then proceeded with a re-stake but the node got disconnected.

The node received an internal stop signal with reason shuffled out, and is now offline:

![image](https://user-images.githubusercontent.com/16723548/83358923-9093c980-a37f-11ea-9788-28116bbb79d9.png)

![image](https://user-images.githubusercontent.com/16723548/83359048-4d862600-a380-11ea-8969-c042bdc19cf1.png)

Is the disconnect related to the re-staking? 

[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/4708119/logs.zip)

After a manual restart the node was back in action:

![image](https://user-images.githubusercontent.com/16723548/83361852-225a0180-a395-11ea-8412-e3329b2fdf9a.png)

But on a different shard, so could this be a shuffling issue?

-----------------------------------------------------------------------------------------------------

As a side question, I didn't receive any funds on unstake, but I could stake back with 0 stake. Is this expected functionality?

Genesis has 2.5 mil for my address staked:

    "address": "erd1ha75w6zs5hevgvakm2ekdllc66qz80dytwlc32u46xstx6vge9uqd4ncvp",
    "supply": "2500000000000000000000000",
    "balance": "0",
    "stakingvalue": "2500000000000000000000000",
    "delegation": {
      "address": "",
      "value": "0"
    }

Unstake: https://explorer.elrond.com/transactions/260b9a9aff545673f4b2a2fc73ca3a572a2cbfe2e0e6dfb9cc9987c3725fde34

Re-stake: 
https://explorer.elrond.com/transactions/6fc08cdab77cc16fa961e54733cd2f28acf2ded53b5b04fffbcaa3ec3a9973da

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.122-0-g559693daa/go1.13.1/linux-amd64
Hosting VPS: ubuntu server 18.04 @ home
</details>

**Comment by sasurobert** [comment]
Hi @soringp ! After unStaking the node, that one becomes observer. Next time when you stake, you go into the NEW validators list, from there you are assigned to one random shard. If your current shard is different then the newly assigned one, the nodes is closed, as it waits to be restarted. When restarted he will start in the correct node.

You received the stake only after calling unBond as well.
