### ISSUE TITLE
CPU Eater

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#1856]
![image](https://user-images.githubusercontent.com/23145642/83624916-195d6180-a548-11ea-9c75-bf10aeb89c37.png)

**Comment by joesixpack** [comment]
Still persists.

![image](https://user-images.githubusercontent.com/23145642/84002340-2221af00-a91d-11ea-905c-c1951f57cee2.png)

[nodelogs2.zip](https://github.com/ElrondNetwork/elrond-go/files/4744442/nodelogs2.zip)
[nodelogs.zip](https://github.com/ElrondNetwork/elrond-go/files/4744443/nodelogs.zip)

**Comment by iulianpascalau** [comment]
Please tell us your system specs and how many nodes are you running on this instance

**Comment by joesixpack** [comment]
I wonder if this is related to the memory heap bug.

**Comment by joesixpack** [comment]
Seems particularly pernicious when syncing, but especially so when the syncing never catches up.

**Comment by iulianpascalau** [comment]
Can you try again with the latest version? Thanks.

**Comment by joesixpack** [comment]
Yeah, it's pretty much fixed.  Put it to bed.

**Comment by iulianpascalau** [comment]
Thanks for the feedback
