### ISSUE TITLE
Send form resets during edit [Web Wallet]

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1858]
I've experienced a form reset a few times and it's quite annoying, is this a bug or a feature? If this is a feature it should only affect the available balance and not remove the entered address.

I was finally able to take some screenshots:

1. With a pending transaction on the background, initiate a new transfer, and fill out the form:

![image](https://user-images.githubusercontent.com/16723548/83637275-05e5e100-a5b0-11ea-9863-eb8a8f582537.png)

2. At some point before the pending transaction turns from pending to processed there is a refresh 
and my form resets:

![image](https://user-images.githubusercontent.com/16723548/83637435-4cd3d680-a5b0-11ea-9c48-ebf19b591a92.png)

3. Moments later the pending transaction status is updated:

![image](https://user-images.githubusercontent.com/16723548/83637475-607f3d00-a5b0-11ea-87b9-9e06f2f8a19c.png)

<details>
<summary>Executing details</summary>
<pre>
Google Chrome - Version 83.0.4103.61 (Official Build) (64-bit) on Windows
</pre>
</details>

**Comment by LucianMincu** [comment]
Should be fixed in the latest build release from today @soringp. 🙏 

Please open the issue again if the problem persist after clearing your browser cache ensuring the latest build has been loaded. 
Thanks!
