### ISSUE TITLE
Wallet unavailable

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#1866]
I have used 3 different browsers to access wallet that was newly created but all to no avail with the screenshot below without specific instruction on what causes the issue

![image](https://user-images.githubusercontent.com/7301249/83759962-35f2ba00-a66c-11ea-94e5-585b512c65cc.png)

**Comment by LucianMincu** [comment]
Hey @victoroshi! 

Currently the network has just upgraded to v1.0.125 and there is still 1 hour left until genesis time (until the network starts). 

The wallet cannot be used before genesis time.

Thanks!
