### ISSUE TITLE
Error opening db v1.0.125

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1873]
I'm trying to move a node to a different VPS, so I've started a new node withoud the db folder.

One problem was caused by the non-responsive seednode, I had 3 nodes on 3 different locations not starting.

When the node finally connected to the seednode and started synching, I experienced these errors:

![image](https://user-images.githubusercontent.com/16723548/83865384-c98cbf00-a72e-11ea-91a9-ebd72ef0961e.png)

Then the node died.

Here's the log: [elrond-go-2020-05-06-12-11-30.log](https://github.com/ElrondNetwork/elrond-go/files/4735390/elrond-go-2020-05-06-12-11-30.log)

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.125-0-g2164f5f04/go1.13.5/linux-amd64
Hosting VPS: Contabo
</pre>
</details>

**Comment by soringp** [comment]
For the same node, logview cannot be attached, might be related to the db issue:

![image](https://user-images.githubusercontent.com/16723548/83868549-c0522100-a733-11ea-8a88-f2e4038bad44.png)

Logview attaches just fine to a healthy node.

**Comment by LucianMincu** [comment]
Hi @soringp!
The issue should be solved in the latest release [v1.0.126](https://github.com/ElrondNetwork/elrond-go/releases/tag/v1.0.126)

Please reopen the issue if this can still be reproduced with the latest version. 🙏
