### ISSUE TITLE
Node running termui hangs while closing v1.0.125

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1874]
While the seednode was refusing connections, I kept trying to start a new node without a db folder.

I've started the node manually, with Termui but there were not enough peers so I've closed it with ctrl+c.

Termui closes then It hanged at this point, for minutes, refusing to shut down. It did eventually.

![image](https://user-images.githubusercontent.com/16723548/83866571-a9f69600-a730-11ea-9b4a-9c969b4b3239.png)

When running with log-view option, exiting from the same state was instant, so this might be related to termui.

Log: 
[elrond-go-2020-05-06-11-44-20.log](https://github.com/ElrondNetwork/elrond-go/files/4735472/elrond-go-2020-05-06-11-44-20.log)

Steps:
1. start a node without db folder, without —use-log-view    
2. due to seednod issues, there are no connected peers, nothing happens 
3. after pressing ctrl+c , it hangs on this screen 

Missing db folder might be unrelated but who knows, seems to be caused by the seednode not connecting.

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.125-0-g2164f5f04/go1.13.5/linux-amd64
Hosting VPS: Contabo
</details>

**Comment by soringp** [comment]
Somewhat in this are, same node but a different state, still no db but connectiong to seednode, I cannot attach logview:

![image](https://user-images.githubusercontent.com/16723548/83868208-2ab69180-a733-11ea-9ad2-d32303f5be0a.png)

**Comment by sasurobert** [comment]
This bug is related to P2P closing deadlock. It was fixed in this PR: https://github.com/ElrondNetwork/elrond-go/pull/1910
