### ISSUE TITLE
[FEAT] add the PID of the running node to the node/status route

### ISSUE THREAD

**Issue by citterio** [ElrondNetwork/elrond-go#1879]
I'm developing a dedicated monitoring solution for elrond nodes. The agent, [vilya](https://github.com/flyingbasalt/vilya), running on the same machine as the elrond nodes needs the pid of the running instance to collect more performance metrics.

Right now I find the pid by searching the list of running processing for the full path of each executable, as they are in separate ~/elrond-nodes/node-n directories. But this is messy when more than one user is running nodes on the same big machine as there will not be an obvious mapping between port 808n and node-n, and there can be several 'node-0', 'node-1', ... directories anyways.

It will also be useful for tracking node restarts by systemd and for restarting a crashed node on systems without systemd (btw. thanks for resolving #1077!)

**Comment by raduchis** [comment]
Does the agent also restart the node? If so when starting the node programmatically you could have access to the PID. 

We will take this into consideration in a future expansion of our api routes. 

Thanks for the suggestion.
