### ISSUE TITLE
[BUG] After Genesis Stake, UnStake, UnBond Causes Node to become Jailed, Can't UnBond

### ISSUE THREAD

**Issue by yuriygeorge** [ElrondNetwork/elrond-go#1888]
Shortly after genesis launch, I staked 3 nodes at 2.5M each. Then I decided to experiment with the unStake. Not too long after becoming staked (moving from Oberser to Validator (new)) state, I decide to unStake. Not knowing that I need to wait 400 rounds, I then proceeded to unBond.

My validator then switched to (leaving) state, and then it became jailed.

My guess that it shouldn't have gotten jailed. Maybe because it was running for such a short amount of time, and then was unStaked too soon, that it may have caused statistics to jail it. I don't know.

Also, maybe the unBond transaction should not succeed if 400 rounds has not passed?

Anyways, I posted in Telegram Validators chat, and was asked to make an issue.

stake:
https://explorer.elrond.com/transactions/faa26665fcaff6a9152f458b8b3e0d2a9cb9ececb75a4b2a4b4fef88b75a042f
unStake: https://explorer.elrond.com/transactions/cb3ebe8afcb7f6d2cfe9f587a217d924aaaf80e9971710d53169310352886836
unBond: https://explorer.elrond.com/transactions/e9f16c58da92e97975110d90d9db75bd3e360eade50a31fd14f1c01da8c81527
<details>
<summary>Executing details</summary>
<pre>
Application version string: 1.0.127
Keybase: sovietprodigy

</pre>
</details>

**Comment by yuriygeorge** [comment]
Aight tried to unstake, waited 40 minutes, then unbond, no dice. Validator did go into (waiting) state. Now it’s miraculously back to “eligible” state, but I never re-staked it… Might have to try it again later.
I have 3 nodes staking individually from the same ERD wallet. Maybe I should have used three different wallets…

unJail: https://explorer.elrond.com/transactions/f71ea78a4f32f7338d5530d39579c51f485b371b6970180b9b2e9d0331b4599a
unStake: https://explorer.elrond.com/transactions/00ac0e894b6dcd9e26d49444518ef148b53e1da41cac221aeb8187a6ea190972
unBond: https://explorer.elrond.com/transactions/65e590e26859925f7fc7fab51f5d16b713d685c86cc72517265f5b0e4b3b2c5e
unBond: https://explorer.elrond.com/transactions/67be6bd70c4df723a8a2bae96ce3334ebc267b361ed123e6eadc7b3ea97da9bc

Will update Github issue

**Comment by yuriygeorge** [comment]
It says "unBond is not possible as not enough remaining" - what does that mean?

**Comment by yuriygeorge** [comment]
Interesting, well I notice that (thinking the first unStake didn’t go through) my second unStake transaction shows error:
"unStake is not possible for address with is already unStaked”
https://explorer.elrond.com/transactions/00ac0e894b6dcd9e26d49444518ef148b53e1da41cac221aeb8187a6ea190972

but then the unBond transaction, shows the error “unBond not possible as not enough remaining”
Maybe after becoming jailed, or after a series of duplicate unStake/unBond transaction, it is no longer able to be unBound.

by looking at the code you posted, the condition for that error is either:

!r.canUnBond()
OR
isValidator

It could be that canUnBound is returning false, i.e., **cannot** unBond.
canUnBound() function is:
config.StakedNodes - config.JailedNodes - config.MinNumNodes >= 0

I think maybe because my node was previously Jailed, then maybe there is some bug related to that, and it’s returning that it cannot be unBound.

**Comment by LucianMincu** [comment]
Hey @yuriygeorge!
The chain is currently waiting the next release which would happen in about 1h from now on. Please retry the entire process with the new version and let us know the exact steps to reproduce the error. Thanks for pointing this out. 🙏

**Comment by yuriygeorge** [comment]
Genesis for 1.0.128 has begun
epoch 1, approaching epoch 2

First trial (I), I will try to unStake and unBond properly, by waiting the 400 rounds / 40 minutes.
Second trial (II), I will try to unStake, but then immediately unBond, to see if it becomes jailed again.

Validator(https://explorer.elrond.com/validators/2fa4f38e7dfbfee5522ea97ca2a16061965f2b2500653d419dffd129e0a25ebee9069112c5a2e3c37092800acf9acc058bd8fa371b6a6e747a9a18c0cfbe91a1fbeaaa7344efb571021bf860b07aabd59d8db5594c0ad13ad5f2d8b581196302)
Currently showing Eligible (state)

Trial I:
Step 1: unStake transaction, wait: https://explorer.elrond.com/transactions/54915b60eb9571dc268b76c93b2001f717bccfb1d1fde356efb75e0daa1d4b2e

Validator still showing Eligible (state), right after transaction succeeds.
Monitoring for validator status...

Validator switched to  (eligible (leaving)) state

Step 2: wait 400 rounds/ 40 minutes
Step 3: unBond transaction in epoch 2, 45 minutes later: https://explorer.elrond.com/transactions/14ffe77a11b9c504ede1483b4cb5c59c88e3881a1c109d78db8f99feb1f66c3f

Transaction succeeded, but explorer shows this error:
unBond is not possible for address /���}���R.�|��`a�_+%e=A���)��^���Ţ��p�� Ϛ����7jntz��Ͼ�����sD��q�`�z�՝��YL �:��ص�c because unBond period did not pass

Do I need to wait until Validator finishes the (leaving) state?
What Validator state should I be looking for to know that unBonding is ready?

Step 3 (again): will try to unBond again in epoch 3, one hour later: 
Validator is now in just (leaving) state, where before above when unBond failed, it was in (eligble(leaving)) state
https://explorer.elrond.com/transactions/1d19dd0047a3133ae123ef5f098b768bf4ffad323fd61bedcf20d40e68e5739b

Crossing fingers... now it says Success, with no errors.

It worked!

Will try again to unStake, unBond with other node.

**Comment by yuriygeorge** [comment]
Trial II: Will reStake again, then shortly after unStake, then attempt to unBond again. Will try to see if this causes the node to become jailed.

stake transaction: https://explorer.elrond.com/transactions/8d806728cb4586b691fcf7ded932f997cf958f7d061c03524f51c9ffd5d290df

Validator is now in (new) state, then
Step 2: Attempting to unStake: https://explorer.elrond.com/transactions/c50a08bd5401b20f8b229a16efbee508d8d8ce7437ba116ea87421b610d93b6d

Validator is now in (leaving) state

Step 3: Attempting to unBond without waiting the 40 minutes
https://explorer.elrond.com/transactions/7b5a64a7c17e629b49c7b658db5c8d2d8b16b2165e5b34f3244d8c8edcc8234b

 unBond is not possible for address /���}���R.�|��`a�_+%e=A���)��^���Ţ��p�� Ϛ����7jntz��Ͼ�����sD��q�`�z�՝��YL �:��ص�c because unBond period did not pass

So, it looks like the new .128 patch shows the error message which is helpful.

I was not able to reproduce this error in 128 patch because I believe I wasn't able to jail the node.
I believe, if the node becomes jailed, and then an attempt to unBond, then it would be possible to reproduce.

Another key difference is, the problem/jail situation I experienced the first time was also when I had set up my nodes for the first time, and received the free 2.5M xERD's to become Validator for the first time. This could have something to do with it becoming jailed.

I think it's safe to close this issue. I'll see if I do get jailed again, will try to reproduce.

**Comment by sasurobert** [comment]
HI @yuriygeorge 

First of all thanks for trying it all the functions out.
In case of your fist tries, the problem was with metachain as it was advancing super slow, plus it did not notarized transactions fast enough from the shards. Furthermore, as a lot of validators got their rating depleted, the shuffler could not shuffle out those validators who had good rating, even if they did an unStake (we prefer to keep the good people in and let the bad guys out, even if this means the imposibility of unBond for the good guys for a longer period of time).

The system smart contract JAIL function is not activated currently - so those nodes which appear as jailed they do from the perspective of rating - not yet per se jailed in the perspective of the smart contract. If the node is jailed in the smart contract - it will lose a portion of its stake. This will be activated later on, when we ensure that we do not have problems in the protocol which would cause good nodes to get jailed as well (one example is yesterday's edge case). We do not want good nodes, running proper software on proper machines to lose money.

What is happening right now with "unBond": The node can be unBonded in the following conditions: unStake was called at least 400 blocks before, the node is not in eligible / waiting list, plus there are enough nodes in the system to ensure the quorum and safety of each shard. After unStake it is mandatory to wait at least 2 epochs - in order to shuffled into an inactive list before calling unBond.

**Comment by yuriygeorge** [comment]
Great. THanks for the explanation!
