### ISSUE TITLE
Termui red notification after the App version number 

### ISSUE THREAD

**Issue by Dazard** [ElrondNetwork/elrond-go#1889]
Sometimes i can observe a red notification on my nodes in termui after the App version number, like this: 
App version: v1.0.127-0-g07a688e4d/go1.13.5/linux-amd64 (version [invalid key] is available)

Hosting: no VPS - nodes running on local workstations

@miiu96

**Comment by bogdan-rosianu** [comment]
Hello. We analyzed this issue and it may be caused by the early initialization of the TermUI component and it's metrics. This is fixed and is currently in pull request.
