### ISSUE TITLE
Node stuck offline / shuffled out v1.0.127

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1893]
After running fine for hours, the node is shuffled out and all connections are closed. 

This only happened at home, 4 times in 48 hours, on two different machines. This doesn't happen on any of the other 4 VPS I'm using. 

It also happened in v1.0.126.

After a manual restart, the node started in Shard 0 just fine. It died on metachain.

![node stuck offline](https://user-images.githubusercontent.com/16723548/84125434-352f9e80-aa45-11ea-897e-0d987ed16649.png)

![shuffled out](https://user-images.githubusercontent.com/16723548/84125448-3b257f80-aa45-11ea-908d-0f932c2f8648.png)

![serialDB is closed](https://user-images.githubusercontent.com/16723548/84125458-3eb90680-aa45-11ea-9e7d-6489ae875c9d.png)

Full log:
[elrond-go-2020-08-06-17-55-11.zip](https://github.com/ElrondNetwork/elrond-go/files/4750886/elrond-go-2020-08-06-17-55-11.zip)

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.127-0-g07a688e4d/go1.13.1/linux-amd64
Hosting VPS: Ubuntu 18.04 @ home
</pre>
</details>

**Comment by soringp** [comment]
@LucianMincu recommended logging this issue.

If this is not a bug, how come other shard changes happen smoothly, without a manual restart?

**Comment by soringp** [comment]
New version, similar issue, logs:
[1.0.128 logs.zip](https://github.com/ElrondNetwork/elrond-go/files/4757003/1.0.128.logs.zip)

The node was appearing online on the explorer but it had 0 peers connected and 25% downtime.

Also BoN monitor BoT reported periodic offline intervals for it: 07:10 - 07:11, 07:19 - 07:20, 07:37 - 07:50, 08:13 - 08:15, 08:23 - 08:24, 08:35 - 08:36, 08:41 - 08:46, 08:51 - 09:10, 09:15 - 09:24, 09:29 - 09:59, 10:04 - 10:18, 10:23 - 10:29

**Comment by iulianpascalau** [comment]
There might be some issues regarding the new libp2p libs: https://github.com/libp2p/go-libp2p/issues/933 . Changed the order of operations in PR #1910 (the change will be available in the next release). Please open another issue if this problem persists. Thanks! :+1:
