### ISSUE TITLE
[BUG] unable to load rounds

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#1899]
Validator has been up since the evening before BoN onchained and upgraded itself throughout the different versions.  Currently its rating is declining instead of rising.  [Explorer ](https://explorer.elrond.com/validators/ad7aabd956588fc09a8eb56468348deba564d1725de3bbbfd7be9364acd84e100cb60472b7e2b303e933994c8c2b2e0a9f299c74cf6bc5342b5269abcd9a6e7f98a8f8d43109aea64a80cbddf4b1d58aa48fa5ef0e9e23dd8c57add52550b813)shows "unable to load rounds" asif it's never known it ?

Termui : 
![image](https://user-images.githubusercontent.com/8461454/84168133-54dfba80-aa77-11ea-8fe6-1217a8dc1c80.png)

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.127-0-g07a688e4d/go1.13.4/linux-amd64
Hosting VPS: Contabo VPS-L 
</pre>
</details>

**Comment by koen84** [comment]
Persists after restarting the node.

**Comment by bogdan-rosianu** [comment]
Hello!
As I see inside validator statistics, you have some failures when being a validator.
```
totalNumValidatorSuccess: 2665,
totalNumValidatorFailure: 444,
```
@raduchis maybe you can provide more details, please.

**Comment by LucianMincu** [comment]
Thanks for pointing this out @koen84 🙏 
The error has occurred on all shards below metachain and this is just a warning or more a side effect of the main problem, which was that metachain stopped producing blocks at that time with version v1.0.127.
