### ISSUE TITLE
[BUG] Unable start when setting the node name with space

### ISSUE THREAD

**Issue by fiowind** [ElrondNetwork/elrond-go#1903]
Unable restart the nodes when setting the node name with a space
<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.126 - v1.0.127/go1.13.5/linux-amd64
Hosting VPS: Ubuntu 18.04.4 LTS
</pre>
</details>

**Comment by bogdan-rosianu** [comment]
Hello!
Can you please provide more information about this?
Did you set the `NodeDisplayName` inside `prefs.toml`? What value did you use?

Thank you!

**Comment by iulianpascalau** [comment]
Will close this one, confirmed that we can have white spaces in the node's name. Maybe you have forgot a closing "
