### ISSUE TITLE
[FEAT] When paying rewards, stamp BLS key as data

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1912]
This is a feature meant for Mainnet, where we could have multiple nodes receiving rewards to the same address.

This is a current rewards transaction, I can't tell the rewarded node from it:

![image](https://user-images.githubusercontent.com/16723548/84269054-57064f80-ab31-11ea-9513-4a39dd5fb767.png)

You could set the first 10 characters of the BLS key in the data field for querying. 

If this is left out intentionally, for privacy reasons, then maybe you can stamp some other unique identifier or hash, that only the owner of the BLS key could know.

Thanks

**Comment by sasurobert** [comment]
We did not add the BLS keys and the value accumulated for each validator in order to optimize the length of rewards and messages. The values of how any each node - each bls key performed can be taken from validator statistics API.

**Comment by soringp** [comment]
I'm interested to sum up the rewards for a given node, on a given interval. Can I do this from the validator stats?

**Comment by sasurobert** [comment]
You can add a set of logs in epochStart/metachain/rewardsV2.go -> computeRewardsPerNode
