### ISSUE TITLE
[QUESTION] Changing state from Eligible to Waiting pattern v1.0.128

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1913]
This is my conspiracy theory for @iulianpascalau:

The nodes are supposed to be benched randomly, yet I find this pattern of nodes going Waiting based on their BLS key id.

I've noticed all my nodes named "fab1ed" going to sleep at the same time, from time to time.

I've made a snapshot and expanded my observation to all nodes.

It turns out that all "e" and "f" nodes were sleeping at the same time, non were eligible. Most of the "d" and "9"s as well, but some were eligible here.

Other than a few in the 0-c range, most likely old heartbeats, no key in the 0-c was sleeping. (except for 9)

Isn't this a bad thing? 

Thanks

[heartbeat.txt](https://github.com/ElrondNetwork/elrond-go/files/4758819/heartbeat.txt)
[eligible.txt](https://github.com/ElrondNetwork/elrond-go/files/4758820/eligible.txt)
[waiting.txt](https://github.com/ElrondNetwork/elrond-go/files/4758828/waiting.txt)

Is this an intermediate step before a reshuffling?

**Comment by AdoAdoAdo** [comment]
Selection of shuffled out validators was changed.
