### ISSUE TITLE
[BUG] Script.sh Install Fails on Attempted Overwrite

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#1916]
![image](https://user-images.githubusercontent.com/23145642/84292931-ea249280-aafb-11ea-8be0-48918216b963.png)

Need to support:

sudo apt-get -o Dpkg::Options::="--force-overwrite" install <package>

in the install script for edge cases like this.

**Comment by valentin-lup** [comment]
Good catch ! But only that flag will not be enough in case of grub updates. I will add something like this:
sudo DEBIAN_FRONTEND=noninteractive apt -qy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
