### ISSUE TITLE
[BUG] termui 'panic: repeated read on failed websocket connection'

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go#1917]
2 out of 6 nodes, on different machines, had their connected termui crash with message 'panic: repeated read on failed websocket connection'.

It happened in epoch 10 after round 6592 and epoch 14 after round 8963.

Both nodes kept running, their logs show nothing abnormal during those rounds at the [INFO] level, unfortunately I'm not logging [DEBUG] today. I tried to restart termui just a few minutes after it had crashed and it connected to the node normally.

![image](https://user-images.githubusercontent.com/62286558/84296288-1f58d100-ab4c-11ea-9c67-de33c44a0579.png)

Both machines have significantly more resources than the required minimum (one of them was only running one node, with 4 physical cores and 16 GB RAM)

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.128-0-g8c5d7bd30/go1.13.7/linux-amd64 
Hosting VPS: no VPS 
</pre>
</details>

**Comment by LucianMincu** [comment]
Hi @flyingbasalt!
This issue has been fixed in one of our [latest releases](https://github.com/ElrondNetwork/elrond-go/releases/latest).
Thanks for pointing this out and let us know if the problem persist. 🙏
