### ISSUE TITLE
Cannot change destination as observer after sync v1.0.128

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1924]
I just did a clean install, with one node - new random key.

It started as Observer on shard 0. It quickly got in sync.

I then proceeded to change the DestinationShardAsObserver to "metachain" and I've restarted the node. I've checked with Termui, the node was definitely down and back up.

The node started on shard 0, ignoring my pref setting.

I only got it working after stopping the node and deleting the db folder.

With no db, is started synching on metachain right away.

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.128-0-g8c5d7bd30/go1.13.5/linux-amd64
Hosting VPS: unrelated
</details>

**Comment by soringp** [comment]
Whatever this was it doesn't happen on 1.0.129. I will keep an eye and reopen the issue if needed.

**Comment by soringp** [comment]
This happened again in version v1.0.132, this time to @ChibisovYuriy (TG handler)

The node was reading the setting, saying it's starting on shard 1 (same as updated config) but the db stayed synced on Shard 0, as seen on Termui.

**Comment by soringp** [comment]
ARCSoft-RO's input on #2001:

Steps to reproduce:

Spin up a new observer node and set-it up as observer for Shard0 for example
Stop the observer node
Change prefs.toml to switch the observer on Shard1 for example
Start the observer node
Checking the observer status via termui will show that the observer is still part of Shard0.
Checking the filesystem will reveal that a new folder for the Shard1 DB is not created.
Completely removing the DB folder will force the node to sync and switch to the new shard.

Application version string: v1.0.132

**Comment by soringp** [comment]
I've experienced the issue even with both Shard folders present, I've imported manually Shard_0 folder to a node synched on Shard_1, switched config to 0, but it resumed working on Shard 1. 
Renaming Shard_1 to Shard_1.x made the node resume sync on the imported Shard_0 folder.

**Comment by bogdan-rosianu** [comment]
Hello. This has been fixed but it will work only if the node is not a validator (does not belong to `eligible` or `waiting` list)
