### ISSUE TITLE
[BUG] - Node statistics endpoint returning wrong data

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#1929]
It seems like the /node/statistics endpoint is returning wrong data, at least for the per/shard statistics.

As you can see from the image below, taken out of the monitoring, the "liveTPS" (green) goes over the reported maxTPS for the shard(red)

![image](https://user-images.githubusercontent.com/37418817/84406692-8fca2580-ac12-11ea-8731-7358c988f131.png)

Below you will also find and exact response coming back from the node statistics endpoint, with liveTPS 1728 for both shards, but then another subsequent result would not change the peakTPS values for both shards:

{
  "statistics": {
    "liveTPS": 1728,
    "peakTPS": 2539,
    "blockNumber": 1329,
    "roundNumber": 1528,
    "roundTime": 6,
    "averageBlockTxCount": 656,
    "totalProcessedTxCount": 872090,
    "shardStatistics": [
      {
        "liveTPS": 1728,
        "averageTPS": 284,
        "peakTPS": 844,
        "currentBlockNonce": 1329,
        "totalProcessedTxCount": 434595,
        "shardID": 0,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 10370
      },
      {
        "liveTPS": 1728,
        "averageTPS": 286,
        "peakTPS": 1666,
        "currentBlockNonce": 1329,
        "totalProcessedTxCount": 437303,
        "shardID": 1,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 10370
      }
    ],
    "lastBlockTxCount": 10370,
    "nrOfShards": 2
  }
}

Second call
{
  "statistics": {
    "liveTPS": 332,
    "peakTPS": 2539,
    "blockNumber": 1329,
    "roundNumber": 1528,
    "roundTime": 6,
    "averageBlockTxCount": 656,
    "totalProcessedTxCount": 872090,
    "shardStatistics": [
      {
        "liveTPS": 332,
        "averageTPS": 284,
        "peakTPS": 844,
        "currentBlockNonce": 1329,
        "totalProcessedTxCount": 434595,
        "shardID": 0,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 10370
      },
      {
        "liveTPS": 332,
        "averageTPS": 286,
        "peakTPS": 1666,
        "currentBlockNonce": 1329,
        "totalProcessedTxCount": 437303,
        "shardID": 1,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 10370
      }
    ],
    "lastBlockTxCount": 10370,
    "nrOfShards": 2
  }
}

And another strange result:
{
  "statistics": {
    "liveTPS": 10,
    "peakTPS": 13156,
    "blockNumber": 1677,
    "roundNumber": 1931,
    "roundTime": 6,
    "averageBlockTxCount": 2231,
    "totalProcessedTxCount": 3742759,
    "shardStatistics": [
      {
        "liveTPS": 10,
        "averageTPS": 969,
        "peakTPS": 4626,
        "currentBlockNonce": 1677,
        "totalProcessedTxCount": 1871936,
        "shardID": 0,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 60
      },
      {
        "liveTPS": 10,
        "averageTPS": 968,
        "peakTPS": 4626,
        "currentBlockNonce": 1677,
        "totalProcessedTxCount": 1870629,
        "shardID": 1,
        "averageBlockTxCount": 0,
        "lastBlockTxCount": 60
      }
    ],
    "lastBlockTxCount": 60,
    "nrOfShards": 2
  }
}

**Comment by AdoAdoAdo** [comment]
Apparently in the metachain block that reported the peak, there were more than one block per shard included and finalized. 

Most of the time there would be only one block per shard for Metachain nodes to pick and include in the metachain block, but the constraints are not really strong here.

What metachain cares about is that the block it includes for a shard is subsequent to what it already included, it is signed by the valid consensus group in the shard for that specific round, and it is confirmed by at least one other block.

In case some shard block was delayed (propagation) the metachain would not include it in the current round and include two blocks for the shard in the following round.

We can change the reported peak in this case to consider only one block per shard.

**Comment by AdoAdoAdo** [comment]
@miiu96 can you take this but with low prio?

**Comment by bogdan-rosianu** [comment]
Hi, @arcsoft-ro!
Some time passed since you opened this issue. Releases that came after that included some fixes and enhancements in this area. 

Please let us know if you will experience issues in the future.
Thank you!
