### ISSUE TITLE
Error in stake tx but funds lost

### ISSUE THREAD

**Issue by ahakla** [ElrondNetwork/elrond-go#1937]
https://explorer.elrond.com/transactions/c5432238056dbb62598c0ea5834e14c3c12b48d512332178d8100f8dae9d267a

Staking tx with input data:
`stake@01@faea341efc2a9a550acdf1fec8a6fe9dd96be62f7c0319551b6670f4d5ec4538aea8ab4a548a2b16a581dfe303e36604316c2312d505f889e35980b97abb55eee6@67656e65736973`

Provided BLS key was 130 chars long. Output SC: ` invalid BLS keys: 242d54c964e63872d00c5407e559ecb92a1e90db478870142e2f014323544b69`.

However, the funds are lost! Tx result is `Success`.

**Comment by ahakla** [comment]
If the above is correct, please also change the docs:
https://docs.elrond.com/validators/staking/staking

**Comment by LucianMincu** [comment]
Hi @ahakla !

Have you tried to do a transaction at the same destination with `claim` after the unvalid stake transaction in order to claim the unused funds sent by the stake transaction? 

The `claim` transaction should get all your unused funds back from the staking smart contract.

Thanks 🙏
