### ISSUE TITLE
[ATTACK] Massive create validator transaction breaks transaction processing for Wallet UI/Wallet API transactions

### ISSUE THREAD

**Issue by SebastianJ** [ElrondNetwork/elrond-go#1939]
Ok, first off - I know that I'm supposed to wait until the 15th, but in order to evaluate if an attack is actually viable/the code actually works you need to be able to run a few tests here and there to make sure the tooling will actually compile, or at least do something.

And that's exactly what happened here - I compiled my tool and ran it ONCE with the specified payload/settings and the tx it sent seem to have stopped tx processing for ensuing transactions for the observer nodes used by the wallet API (https://wallet-api.elrond.com).

I've been in contact with @LucianMincu about this and it seems that the transactions actually arrive in the tx pool but are never able to get picked up after an invalid create validator tx is propagated. All subsequent txs won't somehow get processed.

### Attack summary: ###
1. I generated a massive 4500 create validator tx using this code: https://github.com/SebastianJ/elrond-sdk/blob/master/transactions/validator.go#L14-L35 - here's the exact payload I used: https://gist.github.com/SebastianJ/30d345cf430900609d08fe5024ddeca5
2. I then proceeded to send the tx using the [elrond-stress tool](https://github.com/SebastianJ/elrond-stress) - actual tx: https://explorer.elrond.com/transactions/08cec8df8dee81a97720e6a12f91c7a2e77a6ed84ed628dda313992ef713a070
3. The shard that the tx originated from then stopped processing ensuing txs when txs were submitted via the Web UI/wallet (and it stayed this way until @LucianMincu restarted the Wallet API observers)

### How to reproduce: ###

Simply send a tx using the following (or a similar) payload: https://gist.github.com/SebastianJ/30d345cf430900609d08fe5024ddeca5

Or to fully reproduce what I did:

_(Until I sort out a static binary this is kinda convoluted because of the dependency on BLS which introduces a lot of extra installation/compilation steps)_

#### Installation/compilation: ####
```
mkdir -p $GOPATH/src/github.com/herumi
cd $GOPATH/src/github.com/herumi
git clone https://github.com/herumi/mcl
git clone https://github.com/herumi/bls

mkdir -p $GOPATH/src/github.com/SebastianJ
cd $GOPATH/src/github.com/SebastianJ
git clone https://github.com/SebastianJ/elrond-sdk
git clone https://github.com/SebastianJ/elrond-stress

cd $GOPATH/src/github.com/SebastianJ/elrond-stress
make clean && make all
```

#### Execution: ####
Put a funded wallet/.pem key (ideally with >2.5m) in `keys/`
Download the create validator tx payload:
```
curl -o data/data.txt https://gist.githubusercontent.com/SebastianJ/30d345cf430900609d08fe5024ddeca5/raw/0d61ce7f6e75ef2cb51e63e0519cb67ac0933c9a/data.txt
```
Run the tool:
```
./dist/stress txs --amount 2500000 --gas-limit 6000000 --concurrency 1
```

### Effectiveness: ###
This attack essentially stopped all ensuing txs after the malicious tx from propagating - making it appear as if transactions were broken.

A temporary workaround while the Web wallet/wallet API wasn't working was to propagate txs using your own nodes.

**Comment by iulianpascalau** [comment]
Thanks, we will investigate what really happened and why. Will post here the progress.

**Comment by iulianpascalau** [comment]
Good catch! :+1: Glad to see the antiflood system works as expected (almost). Here's what happened: each and every message sent through the REST API to an observer that calls Broadcast will first need to be validated on that observer's interceptor (our input gateway). The validation first checks the antiflood stats and it found that a certain peer tried to flood it so it ban it. Unfortunately the banned peer was himself. Of course it did not succeed of disconnecting from self but since it was banned, it prevent any subsequent messages reaching the other peers. A PR will follow soon.

**Comment by SebastianJ** [comment]
@iulianpascalau Cool, awesome that you could identify the root cause and patch it so quick!

**Comment by iulianpascalau** [comment]
Yeah, logs proved to be useful in this case. Reference PR #1942

**Comment by LucianMincu** [comment]
Several security layers have been set in place in regards to the public REST API interface available at `wallet-api.elrond.com` and `api.elrond.com`. 

Thanks for pointing out and all your support @SebastianJ 🙏 
Awesome job!
