### ISSUE TITLE
[BUG] Missmatched BLS Key on transferred node

### ISSUE THREAD

**Issue by newtmex** [ElrondNetwork/elrond-go#1941]
<details>
<summary>Moving a validator node from a server to a new server and starting it with the old validatorKey associates the node with a different BLS key from the one present in the validatorKey.pem file

Application version string: v1.0.130-0-g713cd22bc/go1.13.5/linux-amd64
Hosting VPS: Vultr, Contabo
</summary>

</details>
<details>

</details>

**Comment by LucianMincu** [comment]
Hi @newtmex!
Could you please provide more details about this issue?
Unfortunately there's not really a clear problem described to debug on, so this issue will be closed for now. Please feel free to add more details and reopen if the problem still persist. 
Thanks 🙏
