### ISSUE TITLE
[BUG] Deadlock on host.stop

### ISSUE THREAD

**Issue by mihaib79** [ElrondNetwork/elrond-go#1944]
[saro3-13-6.zip](https://github.com/ElrondNetwork/elrond-go/files/4774292/saro3-13-6.zip)

**Comment by iulianpascalau** [comment]
Related to https://github.com/ElrondNetwork/elrond-go/issues/1893 . Pending response, a dirty fix will be to call Close on a go routine so the node will eventually stop but that will might hide other issues.

**Comment by soringp** [comment]
![image](https://user-images.githubusercontent.com/16723548/84577986-aff01500-adc9-11ea-85db-9e2e4edf128c.png)

Node offline, I'm trying to restart it, hangs on restart as well.

**Comment by iulianpascalau** [comment]
Partially fixed in #1954 . Will be permanent fixed later, when the host.Close call will not stuck the node.
