### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fedor3825** [ElrondNetwork/elrond-go#1945]
Hi!) 
Problem(BUG) in:
My wife 4 node is Jail.
node 1)
node name: Valentinka-1
BLS: 0d50ae57501c6a97b0b0ea27cec68880e8a7115f7039cad0e9811d28e6e2b80019901eacb4335feec0662465c6d353153fcc29de7487eee84e53e38902678a06e79a488d770a03f37f643a61b19f365ddde3ab4fbfcce486e54b92e4c783fb94
wallet: erd1tpq6yy7hwarwpns6rxcg5jrdzftyqqnfjh74rw3va8tfq0vgq99sq696za

node 2)
node name: Valentinka-4
BLS: 014b2d8f331b33147ce7aab9d58f66df55db078c1694eced5db16c2acc59865407ecc830680b78b81d4355f6c05a8403a487a8ca57fef2d47436e4c940bad62492869809605169c8acf633aab63e8454aaea051ca68b3d1800ad98e9c392fe0b
wallet: erd1t0dwxdcz8qteq2kh60q3nthkze0n8srayt5gj5lhhj4g9netk8jq823t5r

node 3)
node name: Valentinka-5
BLS: 11fda10e8fb6527220b63f08b8368d66db69aa8a7754205f00dc4f56026ab0899247d1f109a9e7dba676dc717ef1340059bc82b2bbb718dd97aad2d0e8975cb6dda363a669f113d057fa2214d579c4cc379a276c257d371b10b314e26f72c015
wallet: erd1wu07zjcdc762rfry69r4e0l48jazfegzvkfgyc06arp3ylxpplxqa2td8g

node 4)
node name: Valentinka-6
BLS: 30bae9a21e6841fa187054fc3e9b33de9f973f87e4ab8feb5ed63c8f4f23efb2d56ea16ae1dbea28bd71dd4edc877f0a48be23eb05c38d0005f44ca8aff961549166bdb90827d4557388c2578ec3e26600e69322bf30c222ebc68e1054d66288
wallet: erd1upxewdfjd0vfuvslud4a4wty2s00v2y6u9avna48yv20mxq27vlstvntn8

I try unJail them.  But not successfully. Rating reseting to 50!!! But node is still Jailed((

Transaction Hash Unjail for:
node 1)
- https://explorer.elrond.com/transactions/b1e3b0c9da4284d60b4e22d25228ae8080f140829ccf97dfd6b46eaf4c1c4e98
- https://explorer.elrond.com/transactions/a98d3d931d1eb3d1f999beb2800b8618e511bd1184774fd543a530c45e8ea81e

node 2)
- https://explorer.elrond.com/transactions/9d921544edefec78355bed39182f448f3cf5880b38888fdc0dc8d0424b575eba
- https://explorer.elrond.com/transactions/ceee31ca0c3b26f8511d3e06d8bc83d8d97da3b2e9cd9aa0216224746769a622

node 3)
- https://explorer.elrond.com/transactions/21f963ee9dcc546c1e10e37bb67a676a6efa6502e5d2cb326bb6ea81a6f10956
- https://explorer.elrond.com/transactions/97b64fc9632f37f24ff540937bb80c0279b672ff97474bb3518d5c8ea9dc798f

node 4)
- https://explorer.elrond.com/transactions/a5eee399e04f199819036b541d3f28cb14c76481b46708135ad32a5f0f2f9702
- https://explorer.elrond.com/transactions/403326b20dc29092dd83cf1d84701eb1debe2a8c8eefe21899a3caf70948180c

all transaction is successfully but node still not unjail(( 
But rating 50!!!))
Need FIX!!!)
Thanks allot!!!

![unjailed](https://user-images.githubusercontent.com/50149437/84564249-a46d0180-ad69-11ea-96ae-d2b589186d50.png)

**Comment by LucianMincu** [comment]
Hi @fedor3825 !
Thanks for pointing this out. 

The bug has been solved in the latest release [v1.0.132](https://github.com/ElrondNetwork/elrond-go/releases/tag/v1.0.132)

Please open this issue again if the problem persist.
