### ISSUE TITLE
[BUG] No Functionality of enter key in Wallet 

### ISSUE THREAD

**Issue by margaritapaws** [ElrondNetwork/elrond-go#1951]
No Functionality of enter key in data field of  Wallet, making it tedious to move to the next line.
Only way  to do so is to use space bar until the end of the line the press a key.
How can I write my novel on the blockchain like that :)

Sorry about zero code details or anything like that,one day I may learn! 
But that is what you guys are here for , right?

Have a good day and keep up the great job !

**Comment by LucianMincu** [comment]
Solved in the latest release. 🙏 
Thanks for pointing this out @margaritapaws 👍 

Please reopen this issue in case the problem it's not 100% solved.
