### ISSUE TITLE
[BUG] Invalid Keys

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#1955]
<details>
<summary>Executing details</summary>
<pre>
Application version string: 
Hosting VPS:  
</pre>
</details>

One of my nodes running the current version v1.0.131 on Contabo Sever is showing this Error
![image](https://user-images.githubusercontent.com/7301249/84654821-be444b00-af07-11ea-9af8-b6f8b7053976.png)

Runnig ./logviewer --level=*:DEBUG --file shows the following error: 
![image](https://user-images.githubusercontent.com/7301249/84654918-ecc22600-af07-11ea-85af-d751e0b9a050.png)

What else do I need to do, to bring my node back online?

**Comment by bogdan-rosianu** [comment]
Hello!
It seems that the node is not running so termui or logveiwer cannot fetch data from it. Can you please try to start it again?
If you are using elrond scripts, then run `./script.sh stop` and `./script.sh start`

Thanks!

**Comment by azeemcrypto** [comment]
I have the same issue.

`./logviewer --level=*:DEBUG --file 
INFO [2020-06-16 18:52:27.033]   logviewer application started            version = 1.0.0/go1.13.5/linux-amd64 
ERROR[2020-06-16 18:52:27.034]   logviewer websocket error, retrying in 10s... error = dial tcp 127.0.0.1:8080: connect: connection refused 
`

![image](https://user-images.githubusercontent.com/67022070/84815948-d52c8f80-b024-11ea-969c-acd2cd1ba657.png)

I am running version  v1.0.131

**Comment by bogdan-rosianu** [comment]
Hello! The problem is that your nodes' processes are not running. However, I opened a PR where I change that `[invalid key]` message to something else.
