### ISSUE TITLE
Can send erd from my wallet to my own wallet. 

### ISSUE THREAD

**Issue by CryptoChaser13** [ElrondNetwork/elrond-go#1974]
Hello i just figured out that i can send erds from my own wallet to its self destination. Is this normal?

![Screenshot_20200618_105215_com android chrome](https://user-images.githubusercontent.com/46350890/84972694-ffc83680-b151-11ea-9523-51caf24736ef.jpg)

**Comment by LucianMincu** [comment]
As long as the transaction pays the network fee, there is no problem in it. 👍 
This could be for example a simple transaction that would notarize a document or something else inside it's data field but still sent to its self address.
