### ISSUE TITLE
[FEAT] keygenerator option for stdout output

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go#1982]
The end goal is being able to generate a json keystore on a machine with no browser and without the plaintext pem ever touching the disk.
My `pem2json.py` script in [erdkeys](https://github.com/flyingbasalt/erdkeys) can read a wallet pem file and write the json keystore, but it would be more secure if `keygenerator` had an option for sending the pem to stdout so it can be piped directly  to `pem2json.py`.

**Comment by iulianpascalau** [comment]
Good idea, will come up with something for this

**Comment by iulianpascalau** [comment]
Done in #2527. Thanks for reporting this.
