### ISSUE TITLE
Wallet pagination fail [BUG]

### ISSUE THREAD

**Issue by JVidales-cat** [ElrondNetwork/elrond-go#1990]
when movinng from page 200 to page 201, explorer says that there's no transactions.

<details>
<summary>Moving through pagination</summary>
When trying to move to page 201:
![error1](https://user-images.githubusercontent.com/67277722/85300094-6dec6080-b4a6-11ea-9fb4-33c756e0eb72.png)
![error2](https://user-images.githubusercontent.com/67277722/85300098-6e84f700-b4a6-11ea-944a-67f882779426.png)

</details>

**Comment by LucianMincu** [comment]
Thanks for pointing out the issue.
The pagination error was caused by a query limit size of 10000 items on explorer database. 

The latest released versions should cover all the pointed errors. 

Thanks! 🙏
