### ISSUE TITLE
Proposal to Add, Remove also on/off specific node in 1 machine that has multiple node instead off stop all

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#1993]
We need this add and rem node also on/off node freely especially for company, imagine when company has installed 2 node on their machine and 1 is in trouble, they should can just go off the trouble one, remove it and add the new one instead of stop all the 2 node, which make the delegator on the healthy one must also affected the impact of another node, it's disadvantage delegator and will be a bad review for the validator in financial perspective 

The Existing feature is not enough, because if we want to add 1 or remove 1 we also must have to stop the other one (stop all)

Was we can just add 1 new node with simple sintax, before it Alwin has also made script for validator if they want to add new node or want to remove specific node

**Comment by lilok** [comment]
How is it possibile to remove a specific node?

Thanks

**Comment by gabi-vuls** [comment]
With the latest scripts the issue is solved.
