### ISSUE TITLE
[BUG] - Switching Shards for observers does not work until DB is completely removed

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#2001]
Steps to reproduce:

1. Spin up a new observer node and set-it up as observer for Shard0 for example
2. Stop the observer node
3. Change prefs.toml to switch the observer on Shard1 for example
4. Start the observer node

Checking the observer status via termui will show that the observer is still part of Shard0. 
Checking the filesystem will reveal that a new folder for the Shard1 DB is not created.
Completely removing the DB folder will force the node to sync and switch to the new shard.

<pre>
Application version string: v1.0.132
</pre>

**Comment by soringp** [comment]
Same issue as #1924, but switching shards got more popular these days :)

**Comment by arcsoft-ro** [comment]
Thanks @soringp - will close this dupe.
