### ISSUE TITLE
[BUG/QUESTION] A node's totalNumLeaderFailure increased while in waiting state

### ISSUE THREAD

**Issue by anhnd** [ElrondNetwork/elrond-go#2036]
So I write a script to check the consistent of data from https://wallet-api.elrond.com/validator/statistics. At epoch 4 of v1.0.134, It found something like this:

db9fa48d7b41840fbd0c409276e02b2606701fb019c22b118cac6f435f740e56358ce661d36703c53532901151fdcd0b8c040fee74fd43a8d7cdae08db4556c09e7f712acd8a7a784e984878cb9934c2aea243dc4350960ddff9812a0a1e2187":{"tempRating":51.27399,"numLeaderSuccess":0,"numLeaderFailure":0,"numValidatorSuccess":2,"numValidatorFailure":0,"rating":51.27285,"ratingModifier":1,"totalNumLeaderSuccess":6,"totalNumLeaderFailure":1,"totalNumValidatorSuccess":2202,"totalNumValidatorFailure":194,"shardId":0,"validatorStatus":"waiting"}

The node was in waiting state, totalNumLeaderFailure increased by one in the middle of the epoch (around 21:41 UTC), numValidatorSuccess showed 2, and TotalValidatorSuccess was not added up (1667+534 = 2201, showed 2202 - DrDelphi gave me the data). I'm not sure if it's something wrong or it's just a delayed update(because the network was in an intense load condition)

<details>
<summary>Executing details</summary>
Checking https://api.elrond.com/validator/statistics every 10 seconds then validating the consistent of data.
<pre>
Application version string: v1.0.134
Hosting VPS: not related
</pre>
</details>

**Comment by raduchis** [comment]
The update in the statistics can take a while. There is also a case with the last block in the previous that will be considered just in the new epoch, when the validator could be in the waiting list. 

We will still check this but it should be ok.
