### ISSUE TITLE
Failed when shuffling out restart repeatedly make my node jailed [BUG]

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#2037]
It just couldn't shuffling out the restart by itself and then increase down time, down time coincides with the failure of shuffling out restart, it happen until my node rating down below and jailed. In other of my node who can restart, got off and on several time, until it got the installation but with decreasing of down time

<details>
<summary>Failed of Shuffling Out</summary>
<pre>
Application version string: since v1.0.132
Hosting VPS: Contabo
</pre>
</details>

![shuffle-out-restart-failed](https://user-images.githubusercontent.com/44559893/86000000-21210080-ba37-11ea-8f8c-665c3ee61ec1.png)

![on-off](https://user-images.githubusercontent.com/44559893/86000077-3eee6580-ba37-11ea-85ff-b306a4b29e10.png)

**Comment by scraido** [comment]
just gave input, because i didn't want to get purge because of this stuff instead of the High TPS it self

**Comment by scraido** [comment]
maybe it's known as a blacklist BUG now? one of mine which is scraidx2 can escape the issue and start but with a big damage of down time, it's 28 june '20, will it still have the db? or it has been auto clean-up by the new release?

**Comment by scraido** [comment]
i just think maybe the db can help, coz it struggle from the storm

**Comment by scraido** [comment]
i got the db of 1 of my struggling node the x5, hope help if it come again on future update

https://drive.google.com/file/d/1WECn3mDpxy6TcNoVeGXHb6jBoZ9yj9n0/view?usp=sharing

**Comment by iulianpascalau** [comment]
There were some sync issues that were fixed. Thanks for the effort!

**Comment by scraido** [comment]
you're very welcome
