### ISSUE TITLE
[BUG] blacklisted due to incompatible p2p message 

### ISSUE THREAD

**Issue by yuriygeorge** [ElrondNetwork/elrond-go#2048]
One node on shard 1 went offline. Tried restarting it no avail. Then removed DB and restart, no help. Then did Clean up and reinstall. Now, all 3 out of 6 nodes on Shard 1 can't come back online.

Юрий, [Jun 29, 2020 at 8:13:15 PM]:
...DEBUG[2020-06-30 01:12:23.568]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:12:24.568]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:12:25.568]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000

DEBUG[2020-06-30 01:13:04.318]   blacklisted due to incompatible p2p message pid =  time = 2h0m0s 
DEBUG[2020-06-30 01:13:04.583]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:13:05.322]   blacklisted due to incompatible p2p message pid =  time = 2h0m0s 
DEBUG[2020-06-30 01:13:05.584]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:13:06.584]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:13:07.584]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:13:08.585]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2

...DEBUG[2020-06-30 01:27:18.824]   start in epoch bootstrap: SyncMissingHeadersByHash 
DEBUG[2020-06-30 01:27:18.824]   start in epoch bootstrap: started syncUserAccountsState 
DEBUG[2020-06-30 01:27:18.824]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 4e39a3..f096ef 
DEBUG[2020-06-30 01:27:19.832]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 5ab6d6..bf9422 
DEBUG[2020-06-30 01:27:19.832]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = 121f20..71d1a2 
DEBUG[2020-06-30 01:27:19.832]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = 3e644c..7068b9 
DEBUG[2020-06-30 01:27:19.832]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = 73e781..e27183 
DEBUG[2020-06-30 01:27:19.832]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = bb0ebb..6323d0 
DEBUG[2020-06-30 01:27:19.832]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = 71260e..e5bdbb 
DEBUG[2020-06-30 01:27:19.833]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = bc9946..6afb70 
DEBUG[2020-06-30 01:27:19.833]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = cc1e7b..241666 
DEBUG[2020-06-30 01:27:19.833]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = f9a83f..c8ed90 
DEBUG[2020-06-30 01:27:19.833]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = 537a13..d874f6 
DEBUG[2020-06-30 01:27:19.834]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = 3a67af..e3faa0 
DEBUG[2020-06-30 01:27:19.834]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = 49e01d..d4b215 
DEBUG[2020-06-30 01:27:19.835]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = d11df2..f98daa 
DEBUG[2020-06-30 01:27:19.835]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 10 firstHash = 69f6bd..81a713 
DEBUG[2020-06-30 01:27:20.835]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:21.835]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:22.836]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:23.836]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:24.836]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:25.837]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:26.837]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:27.837]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:28.838]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000

DEBUG[2020-06-30 01:27:29.838]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:30.838]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:31.839]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:32.841]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:33.841]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:34.842]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:35.842]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:36.843]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:37.843]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:37.945]   network connection status                known peers = 767 connected peers = 35 intra shard validators = 0 intra shard observers = 0 cross shard validators = 0 cross shard observers = 0 unknown = 35 
DEBUG[2020-06-30 01:27:37.945]   network connection metrics               connections/s = 2 disconnections/s = 1 
DEBUG[2020-06-30 01:27:38.844]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000 
DEBUG[2020-06-30 01:27:39.844]   requesting trie nodes from network       topic = accountTrieNodes shard = 1 num nodes = 1 firstHash = 000000..000000
...

DrDelphi: There's a new bug in town where innocent nodes are blacklisted and kicked out of the network and become offline for 2 hours
Jun 28 11:24:00 stakingagency06 node[20381]: DEBUG[2020-06-28 11:24:00.033]   blacklisted due to incompatible p2p message pid =  time = 2h0m0s

<details>
<summary>Executing details</summary>
<pre>
Application version string: 134
Hosting VPS: Self hosted
Keybase: sovietprodigy
</pre>
</details>

**Comment by yuriygeorge** [comment]
By switching to another machine in different network on different IP, the issue still propagates.. Seems to be tied to BLS Key on Shard 1

**Comment by napvd** [comment]
![node123](https://user-images.githubusercontent.com/35908572/86081775-57ef2900-bac0-11ea-81f9-32f4f9728b3a.png)

I see the same errors!

**Comment by Vasya-kripto** [comment]
+ have got the same issue

**Comment by yuriygeorge** [comment]
Same as: https://github.com/ElrondNetwork/elrond-go/pull/2038
