### ISSUE TITLE
[BUG] v 1.0.36 RAM ISSUE

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#2080]
At some moment after reshuffling almost all the ram of the vps is is used, reshuffling again does not make the problem disapper.
After nide is rebooted ram memory frees up, but the problem come back , making the node rating drop.
I gave provided mu node with double miminum specs.
i have 4 cpu , 8 gb ram 200 ssd.

![image](https://user-images.githubusercontent.com/26198807/86887712-a96f6780-c101-11ea-8552-510b58689975.png)
![image](https://user-images.githubusercontent.com/26198807/86887817-d58ae880-c101-11ea-864d-90ae8af0536d.png)

ten above resources are on a VDS, which runs a single node.

what is interesting is that for a vps that runs 4 nodes the memory gap seems the same, is the not the number of nodes x memory gap, also there is a huge diffrence in what termui shows that is used (2,4 gb) and what htop (8,5 gb) shows 

![image](https://user-images.githubusercontent.com/26198807/86888079-46ca9b80-c102-11ea-96bb-0495c4441e3a.png)
![image](https://user-images.githubusercontent.com/26198807/86888160-6792f100-c102-11ea-832b-d65e3470cf6e.png)
![image](https://user-images.githubusercontent.com/26198807/86888242-872a1980-c102-11ea-8a03-57b11e86e57a.png)

<details>

<pre>
Application version string: <v1,0.036, vds, romanian provider of vps
</pre>
</details>

**Comment by ravenx29** [comment]
I had the reboot the node due to the high ram usage, since then the node could not sync.
i have tried at the beginning of a new epoch Ș
sudo systemctl stop elrond-node-0

rm -rf ~/elrond-nodes/node-0/db

sudo systemctl start elrond-node-0

did not help, plus i got this message this time:

![error1](https://user-images.githubusercontent.com/26198807/87239032-fb223580-c412-11ea-9c0c-6cafc0ce06a7.jpg)

**Comment by iulianpascalau** [comment]
This was hopefully fixed by #2078. Please open a new issue if the problem persists. Thanks.
