### ISSUE TITLE
[BUG] Node statistics returning 0 for averageBlockTxCount on shards

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#2106]
Example response:

{
"data": {
"statistics": {
"liveTPS": 750,
"peakTPS": 3500,
"blockNumber": 13146,
"roundNumber": 13629,
"roundTime": 6,
"averageBlockTxCount": 860,
"totalProcessedTxCount": 11308828,
"shardStatistics": [
{
"liveTPS": 750,
"averageTPS": 418,
"peakTPS": 2000,
"currentBlockNonce": 13146,
"totalProcessedTxCount": 5709217,
"shardID": 0,
"averageBlockTxCount": 0,
"lastBlockTxCount": 4500
},
{
"liveTPS": 750,
"averageTPS": 410,
"peakTPS": 2000,
"currentBlockNonce": 13146,
"totalProcessedTxCount": 5599593,
"shardID": 1,
"averageBlockTxCount": 0,
"lastBlockTxCount": 4500
}
],
"lastBlockTxCount": 4500,
"nrOfShards": 2
}
},
"error": "",
"code": "successful"
}

**Comment by iulianpascalau** [comment]
This is solved by the #2134. Thanks.
