### ISSUE TITLE
[BUG] Node statistics returns wrong averageTPS

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#2107]
The average TPS returned should match the following calculation: totalProcessedTxCount / roundNumber / roundTime

Instead it seems like the averageTPS is done like this: totalProcessedTxCount / roundNumber

{
"data": {
"statistics": {
"liveTPS": 333,
"peakTPS": 4666,
"blockNumber": 13431,
"roundNumber": 13921,
"roundTime": 6,
"averageBlockTxCount": 1041,
"totalProcessedTxCount": 13982371,
"shardStatistics": [
{
"liveTPS": 2000,
"averageTPS": 506,
"peakTPS": 2500,
"currentBlockNonce": 13430,
"totalProcessedTxCount": 7045875,
"shardID": 0,
"averageBlockTxCount": 0,
"lastBlockTxCount": 12000
},
{
"liveTPS": 333,
"averageTPS": 498,
"peakTPS": 2166,
"currentBlockNonce": 13431,
"totalProcessedTxCount": 6936478,
"shardID": 1,
"averageBlockTxCount": 0,
"lastBlockTxCount": 2000
}
],
"lastBlockTxCount": 2000,
"nrOfShards": 2
}
},
"error": "",
"code": "successful"
}

**Comment by iulianpascalau** [comment]
This is fixed by #2134. Thanks.
