### ISSUE TITLE
[BUG] synchronization issue between the web portal and termui

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#2119]
<details>
When do termui synchronize with the web? I waited for more than an hour watching if there will be any changes. The web is saying 2 nodes are validators while termui is reporting them as observers. 
**WEB Report**

![image](https://user-images.githubusercontent.com/7301249/87553830-4c4c5680-c6ab-11ea-83c6-041e50c6d9c6.png)

Termui report
![image](https://user-images.githubusercontent.com/7301249/87552796-0fcc2b00-c6aa-11ea-96c6-b0902b2985ba.png)

**Update to the above**

The situation still remain the same after 4 hours, several stop and restart of the specific node failed to remedy the situation
<summary>Syncronization seems to be lagging seriously between the web platform and termui </summary>
<pre>
Application version string: 
Hosting VPS:  
</pre>
</details>

**Comment by LucianMincu** [comment]
Hi Viktor! 

Sorry for the our late and thank you for all your support! 
Most of the issues were covered in the official mainnet release which was at release version v1.1.0 and a lot more fixes we've included in the following versions. If you still run the elrond-go client please let us know if there are any other issues found and once again thank you for your support!

All the best,
Lucian 👍
