### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#2123]
Running on vps, v 1.0.38

Even if the node is sync, it is not in the consesnus group, wich lead to a lot of validator failure
![image](https://user-images.githubusercontent.com/26198807/87630544-042a4400-c73e-11ea-914f-4113f3e9c8de.png)
![image](https://user-images.githubusercontent.com/26198807/87630574-1b693180-c73e-11ea-939c-e37f51d29744.png)

**Comment by raduchis** [comment]
Can you please provide more information? Only if the node is in the consensus group the validator failure should be decreased

**Comment by ravenx29** [comment]
At this moment I don't have any new data

joi, 23 iul. 2020, 12:36 Radu Chis <notifications@github.com> a scris:

**Comment by iulianpascalau** [comment]
should be fixed by now, v1.1.0
