### ISSUE TITLE
[FEAT] Enable sending tokens to smart contracts in a single transaction, plus other improvements

### ISSUE THREAD

**Issue by hiddentao** [ElrondNetwork/elrond-go#2158]
_(Original telegram chat: https://t.me/ElrondDevelopers/3047)_

The ESDT implementation can be enhanced to fix some of the flaws in the [ERC-20](https://eips.ethereum.org/EIPS/eip-20) standard on which it is based. One of the main problems with ERC-20 is that a contract does not know when someone (whether a user or another contract) sends it tokens. The workaround for this in Ethereum is to do 2 transactions when sending money to a contract:

1. Call `approve()` on the token to allow the contract to spend tokens on your behalf.
2. Call a function on the contract which then internally calls `transferFrom()` on the token to get the tokens you approved.

This is a waste of both gas and time and continues to be the way simply because there is already so much legacy code built on top of ERC-20. A better solution and other improvements have been suggested in [EIP-777](https://eips.ethereum.org/EIPS/eip-777).  At a high level:

* Any address can register both send and receive hooks on the token contract, to be notified when tokens are being sent from/to them. Thus, a contract can register a receive hook on the token contract so that it gets notified when someone sends it tokens, thus doing away with the need to _approve -> transferFrom_.
* An address can authorize an _operator_ to send tokens on its behalf. Unlike with ERC-20, there is no limit to the no. of tokens the operator can deal with. 
* Metadata can be passed along with the transaction and is passed onto the hooks.

For ESDT, I believe that at minimum the following would be useful:

* Receive hooks for smart contracts. Since ESDT is system-level this could be done via having a special function - e.g. `receiveTokens(tokenAddress, senderAddress, amountUint)` - that any contract can implement if it wants to handle receiving tokens. For externally-owned addresses it doesn't matter since they can easily transfer received tokens at any point without knowing about them beforehand.

* Metadata parameters in the transfer call, same as for EIP-777. This will give Dapp developers more flexibility in dealing with token transfers and allow for extracting useful information from historical transaction data.

The _operator authorization_ feature is optional, though also very useful. So perhaps that can come in later on as an upgrade to the core contract code.

**Comment by hiddentao** [comment]
Just to add, another problem I've noticed with the ERC20 standard. 

Sending tokens to a contract requires first approving that amount for transfer by the contract, and this has to be done each and every time, meaning 2 transactions each and every time to send tokens.

Thus many projects on Ethereum now provide an "Infinite approval" checkbox whereby you only have to approve the contract once to transfer your tokens, essentially enabling to transfer the max uint no. of tokens. This way you never have to approve the contract again. The problem with this is that there is now a huge security risk. If the contract you approved has a bug / gets hacked in the foreseeable future then all your tokens are essentially forfeit.

This is another reason why we should NOT adopt this approval-transferFrom mechanism in Elrond.

**Comment by sasurobert** [comment]
We finished the new specs of the ESDT token and almost finished the implementation. ERC-777 has some flaws, but found a better way of sending ESDT token and calling a function in a smart contract with the same transaction.

**Comment by sasurobert** [comment]
Will link PR once is opened.

**Comment by hiddentao** [comment]
Good stuff, I'm looking forward to seeing what you guys came up with!

**Comment by hiddentao** [comment]
Done now.
