### ISSUE TITLE
[BUG] - Error storing genesis shard header (nonce-hash) #033[0;31merror#033[0m = no such unit type

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#2190]
The following error was detected by one of my nodes, config attached

PROBLEM : Elrond node error detected in /var/log/syslog. Check history for details!
Problem started at 17:35:42 on 2020.07.31
Problem name: Elrond node error detected in /var/log/syslog. Check history for details!
Host: xyz
Severity: High
Operational data: Jul 31 17:35:38 xyz node[41758]: #033[0;31mERROR#033[0m[2020-07-31 17:35:38.816]   error storing genesis shard header (nonce-hash) #033[0;31merror#033[0m = no such unit type
Original problem ID: 6571

**Comment by arcsoft-ro** [comment]
[config.zip](https://github.com/ElrondNetwork/elrond-go/files/5007600/config.zip)

**Comment by iulianpascalau** [comment]
Will fix this in the next patch. Not a critical error. Thanks for the heads-up!

**Comment by iulianpascalau** [comment]
Fix is done in #2191

**Comment by arcsoft-ro** [comment]
You're welcome and great stuff!
