### ISSUE TITLE
[FEAT] termUI bandwidth use and epoch tracking

### ISSUE THREAD

**Issue by galadriiel** [ElrondNetwork/elrond-go#2193]
It would be very useful to have total bandwidth usage (received and sent) in a specific timeframe in the termUI overview. There are multiple approaches that could be done here, last 24hours for example but maybe it would be better to combine it with epoch tracking. That way bandwidth consumption is measured since the start of the epoch up until the current moment. 
Validators could plug this into their monitoring software and then get an overview through time and compare consumption between epochs.

**Comment by iulianpascalau** [comment]
Done as of today, 2020.09.25. Will become available in the next mainnet release. Thanks.
