### ISSUE TITLE
[BUG] Stats folder, stats file

### ISSUE THREAD

**Issue by galadriiel** [ElrondNetwork/elrond-go#2194]
The question/bug report is related to the stats folder:
It is about the daily .txt file there being generated (why ".txt", who is doing development on Windows? let me slap him right away 😂), the total memory calculation seems to be summing the sys memory for each entry and it ends up into the hundreds of GBs over time. What is the purpose of this information, is it really supposed to be calculated that way?

**Comment by raduchis** [comment]
Hi,

Both observations are correct: the .txt file extension is wrong and also the total memory used, as the sum f all previous entries is not ok. We will change this in a future PR. 

Thanks!

**Comment by iulianpascalau** [comment]
Thanks for reporting. This was fixed by #2229 PR.
