### ISSUE TITLE
[BUG] v1.1.0 validator node lost sync then got stuck in fork detector loop

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#2210]
<details>
on Aug 05 from 09:11:11 UTC to 09:25:55 UTC my VPS experienced an issue that caused no monitoring data to be collected by Netdata.  Prior to 09:11:11 I can see that my 3 validator nodes were in sync, round # 83622 as reported in Netdata.  After 09:25:55 I can see that 2 of the nodes recovered and were able to re-sync.  At 09:26:10 node-0 and node-1 were in sync, round # 83655 as reported in Netdata.  However, node-2 was not able to recover.  From 09:25:55 node-2 current_round is increasing and synchronized_round is stuck at 83619.  At 09:30:08 node-2 current_round was 83700 and synchronized_round was 83619.  Unfortunately, I had setup monitoring of current_round and synchronized_round in Netdata, but had not configured any alarms, so this situation went unnoticed for many hours. The issue was resolved at 00:26 by stopping node-2, renaming db/ health-records/ stats/, then starting node-2.  node-2 was back in sync at 00:43:45 round # 92837. 

Node-2 seemed to be in a fork detector loop from the time the issue started until it was stopped.  

I am running 3 validator nodes at Hetzner on CPX41 - 8 vCPU, 16 gb memory.  This was my setup for the entire BoN Onchained event, including The Assembly, a weekend of stress testing where the sustained TPS level was between 8k TPS and 12k TPS continuous for 24 hours.  

<summary>Executing details</summary>
<pre>
Application version string: Elrond Node CLI App version v1.1.0.0-0-g2bb866e15/go1.14.6/linux-amd64/59ce8b7fcd
Hosting VPS: Hetzner, Falkenstein. CPX41 - 8 vCPU, 16 gb memory. 
</pre>
</details>

**Comment by frankf1957** [comment]
[elrond-node-logs-20200806-0024.tar.gz](https://github.com/ElrondNetwork/elrond-go/files/5035819/elrond-node-logs-20200806-0024.tar.gz)

**Comment by iulianpascalau** [comment]
We found a small issue regarding this problem, fix is on the way. Related to #2206 . Will close this after the PR gets merged. Thanks :+1:

**Comment by LucianMincu** [comment]
Quick update @frankf1957: The PR was merged a while ago and already deployed on mainnet with the [v.1.1.6](https://github.com/ElrondNetwork/elrond-go/releases/tag/v1.1.6) release.

Thank you for all your support! 👍
