### ISSUE TITLE
No PEMs present. You should add some valid keys...[BUG]

### ISSUE THREAD

**Issue by prettyCoders** [ElrondNetwork/elrond-go#2270]
![图片](https://user-images.githubusercontent.com/36216120/92209516-b620f980-eebf-11ea-9ae0-e0d7922b97d7.png)
![图片](https://user-images.githubusercontent.com/36216120/92209555-c933c980-eebf-11ea-804d-f141c6d838c4.png)

**Comment by prettyCoders** [comment]
![图片](https://user-images.githubusercontent.com/36216120/92212790-149ca680-eec5-11ea-931e-22e83db1630d.png)
choose v2?

**Comment by prettyCoders** [comment]
![图片](https://user-images.githubusercontent.com/36216120/92218504-cdfe7a80-eecb-11ea-9ef3-4c6ef9c92ea1.png)
no peers

**Comment by mrlonnie** [comment]
@prettyCoders How did you get pass the `No PEMs present. You should add some valid keys...` error? Ive tried reinstalling everything but no go for me.

**Comment by prettyCoders** [comment]
@mrlonnie maybe  you should install with https://github.com/ElrondNetwork/elrond-go

**Comment by mrlonnie** [comment]
I ended up running the keygenerator under `elrond-utils`, which created a validatorKey.pem and moved it into`node-0/config`.  The node is up and running though I would love someone from the team to verify what I did is alright.

**Comment by iulianpascalau** [comment]
Hello. This is the desired behavior. The key is no longer auto-generated as seen in Battle-of-Nodes competition. The official docs provide instructions for this extra step, as seen here: https://docs.elrond.com/validators/install/install-update
Thanks for reporting, this issue will be closed.

**Comment by elio-maggini** [comment]
@iulianpascalau  The above link is out-of-date.. Would it be possible to update for others (like me) who will also run across this issue?

**Comment by elio-maggini** [comment]
Above link is out-of-date. Correct link is now https://docs.elrond.com/validators/mainnet/install-update/
