### ISSUE TITLE
[BUG] Estimate Gas Fee gives incorrect values

### ISSUE THREAD

**Issue by atulrupnar** [ElrondNetwork/elrond-go#2282]
When endpoint /transaction/cost is called with no extra data, it returns 50000 gasprice which is insufficient to broadcast transaction on testnet
<details>
<summary>Executing details</summary>
<pre>
This is a sample post request
{
    "value": "1000000000000000000",
    "sender": "erd1y7w3yn96rau5vp8z40lrc4t00hx8zy798p83pn0j2j2x7ls3r48slhk0f8",
    "receiver": "erd1rtckak8zfmdu39xwjr9lv56x38lef9yna4ae62252lc6uwlu2r3s28r9qk",
    "data": "",
    "chainID": "T",
    "version": 1
}
It returns estimated gasPrice as 50000 but its not sufficient gas price to send a transaction. 
</pre>
</details>

**Comment by andreibancioiu** [comment]
@atulrupnar, the API responds with the following:

```
{
  "data": {
    "txGasUnits": "50000"
  },
  "error": "",
  "code": "successful"
}
```

This means that you should set a `gasLimit` of `50000` for your transaction. The `gasPrice` is not given - it is up to the user to provide a desired gas price (which should equal or less the global, network-wide `minGasPrice`).

Does this make sense?

Somehow related - in the very near future, a new feature, called `transaction simulation` will be available on the API. That would offer even more details about the execution of a transaction - **without** actually executing it.

**Comment by atulrupnar** [comment]
It seems the description in the description seems different. https://docs.elrond.com/tools/rest-api-overview/proxy-transactions-api#estimate-cost-of-transaction
the estimate gas cost name is more relatable with gasPrice than gasLimit. Anyways I found the glitch. thanks.

**Comment by miiu96** [comment]
Hello. Thank you for the feedback and sorry for the late response.
We made a task to make sure everything is working correctly.

**Comment by miiu96** [comment]
Hello @atulrupnar
We have updated the documentation for this endpoint (https://docs.elrond.com/sdk-and-tools/rest-api/transactions/#span-classbadge-badge-successpostspan-estimate-cost-of-transaction).
