### ISSUE TITLE
[QUESTION] Cannot get block height

### ISSUE THREAD

**Issue by wzt-tao** [ElrondNetwork/elrond-go#2284]
![image](https://user-images.githubusercontent.com/53932327/92691770-ae58cd80-f375-11ea-8a32-26ec9dcbaaff.png)

curl http://localhost:8080/node/statistics

**Comment by bogdan-rosianu** [comment]
Hello! 
Sorry for the late response. That endpoint works well only on metachain nodes. 
For a shard node/observer, please use `http://localhost:8080/node/status` and search for `nonce` related metrics.

Let me know if this works for you.
Thank you!

**Comment by bogdan-rosianu** [comment]
Since we haven’t heard from you for a while, we’ll be closing the issue and marked as resolved.
Please let us know if you have any issues when fetching data from metachain nodes, as shard nodes are not returning relevant data for this endpoint.
