### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by xinxuwangbitmax** [ElrondNetwork/elrond-go#2290]
Hi,I am using https://github.com/ElrondNetwork/elrond-go-scripts-mainnet/tree/exchanges-integration script to run Observing Squad and it works,but i found the node is not syncing from the beginning but recently.Is there any config section to modify to enable the node sync from beginning???Thanks very much

**Comment by bogdan-rosianu** [comment]
Hello! 
When the observers start, they will sync using the `fast bootstrapping mechanism` and will sync only from a recent epoch. Regarding the synchronization from genesis, maybe @andreibancioiu can provide further information.

Thank you!

**Comment by LucianMincu** [comment]
@xinxuwangbitmax with the current binary version the nodes can not sync from genesis as most of the network peers are being reshuffled every epoch, therefore both network topology and data availability for these nodes are not allowing to do this. However with the upcoming mainnet release we're targeting to have the feature built in with full history nodes which will provide extra topics to request the data from specific nodes that do have all the data needed. 

In case you need a full synced DB from genesis for a specific shard, we are automatically generating network snapshots from each shard after epoch change and we can provide you a copy from it which can be imported (reprocessed) and verified inside the node by using the `./node -import-db` flag.

Thank a lot and let us know if there is anything else we can help you with. 🙏

**Comment by iulianpascalau** [comment]
For traceability reasons, the work-in-progress branch can be found here: #2317 
The feature is almost complete, we are working on the integration part an last testing procedures.
