### ISSUE TITLE
Termui white bars at the Network - sent per host, Network received per host and Memory load - are not aligned

### ISSUE THREAD

**Issue by disruptivedigital** [ElrondNetwork/elrond-go#2302]
I noticed that Termui white bars at the Network - sent per host, Network received per host and Memory load - are not aligned regardless of the screen size. 

App version: T1.1.1.0-0-g2bbf9564c/go1.14.2/linux-amd64/9b43f5205d
SSH client: MobaXterm Professional Edition v.20.2 Build 4296

![Termui T1 1 1 0 resized screen](https://user-images.githubusercontent.com/66871992/93523393-a8498a80-f93b-11ea-8d03-57afeeb16f06.jpg)
![Termui T1 1 1 0 full screen](https://user-images.githubusercontent.com/66871992/93523402-a97ab780-f93b-11ea-894c-662d7ae1a6b3.jpg)

**Comment by iulianpascalau** [comment]
Fixed in #2321 . Thanks for reporting this. Will close for now.
