### ISSUE TITLE
[FEAT] Introduce REST API about list of all eGLD public addresses 

### ISSUE THREAD

**Issue by AlexPalaz** [ElrondNetwork/elrond-go#2306]
I would suggest a good feature should be added on ElrondNetwork. I think is good have a REST API with the list of all eGLD public addresses. This can allow users to build some dApps more easily.

An example endpoint could be:

`https://api.elrond.com/addresses/ `

or

`https://api.elrond.com/address/list`

**Comment by bogdan-rosianu** [comment]
Hello!
There is a PR in the testing process that will add the feature to index all addresses and their nonces and balances.
Thank you!

**Comment by AlexPalaz** [comment]
Thank you for your answer. when this feature will be released? Thanks

**Comment by bogdan-rosianu** [comment]
Hi! Sorry for the late response. The elastic search feature is merged and the only thing remaining is to parse the data and display it in the explorer. I cannot give you an ETA for this.

**Comment by bogdan-rosianu** [comment]
Hello! This feature is enabled in the testnet explorer so I will safely close this issue. Thanks!
