### ISSUE TITLE
[BUG] For StoragePruning=false + DbLookupExtensions=On node, persister and endpoint fails since restart 

### ISSUE THREAD

**Issue by jun0tpyrc** [ElrondNetwork/elrond-go#2419]
It could respond tx in current epoch  when first up running all things, but not after restart

**Expected** :
querying the node of a shard involved in transaction using `/transaction/{tx_id}` endpoint  => should return tx data 

It was normal at first up running (can be queried via proxy),
```
[root@bstg-erd-1 app]# curl 0:7950/transaction/77b1447117a6ea9ee91a540b6305b42bd6fc3e61faeceb5ff8625800aa4cdd1f | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   293  100   293    0     0   286k      0 --:--:-- --:--:-- --:--:--  286k
{
  "data": {
    "transaction": {
      "type": "reward",
      "round": 259308,
      "epoch": 108,
      "value": "12664546660798087801",
      "receiver": "erd18twauc77j5rcauxdct34yaqfdngn0dqqu6qprzc54d0awemmr8mql4gfqh",
      "sender": "metachain",
      "sourceShard": 4294967295,
      "destinationShard": 0,
      "status": "pending"
    }
  },
  "error": "",
  "code": "successful"
}
```

-----

BUT after node restart the node returns (this example tx involves metachain & shard2, both the node would return `key not found` since then)
```
[root@bstg-erd-1 app]# curl 0:8080/transaction/77b1447117a6ea9ee91a540b6305b42bd6fc3e61faeceb5ff8625800aa4cdd1f
{"data":null,"error":"getting transaction failed: transaction not found: key not found","code":"internal_issue"}
```
similarly, proxy will return
```
[root@bstg-erd-1 app]# curl 0:7950/transaction/77b1447117a6ea9ee91a540b6305b42bd6fc3e61faeceb5ff8625800aa4cdd1f
{"data":null,"error":"transaction not found","code":"internal_issue"}
```

node runs  with 
`--working-directory="/opt/app/" --keep-old-epochs-data -use-log-view --rest-api-interface="0.0.0.0:8080" --log-level="*:INFO" --destination-shard-as-observer=metachain --port 37373 --start-in-epoch --log-save`
& the tx is in current epoch 

cluster is up by running images below 
```
elrondnetwork/elrond-go-node:v1.1.5
docker.elastic.co/elasticsearch/elasticsearch:7.9.0
elrondnetwork/elrond-go-proxy:v1.1.3
```

we enabled elasticsearch , and tx can be confirmed to indexed in Elasticsearch
https://testnet-explorer.elrond.com/transactions/77b1447117a6ea9ee91a540b6305b42bd6fc3e61faeceb5ff8625800aa4cdd1f
```
      {
        "_index": "transactions",
        "_type": "_doc",
        "_id": "77b1447117a6ea9ee91a540b6305b42bd6fc3e61faeceb5ff8625800aa4cdd1f",
        "_score": 1,
        "_source": {
          "miniBlockHash": "ab3bd5739bef2fbfe631dc068010ee377afa6816ea719907618a5d00ff6776ef",
          "nonce": 0,
          "round": 259308,
          "value": "12664546660798087801",
          "receiver": "erd18twauc77j5rcauxdct34yaqfdngn0dqqu6qprzc54d0awemmr8mql4gfqh",
          "sender": "4294967295",
          "receiverShard": 2,
          "senderShard": 4294967295,
          "gasPrice": 0,
          "gasLimit": 0,
          "gasUsed": 0,
          "data": "",
          "signature": "",
          "timestamp": 1604049066,
          "status": "success",
          "searchOrder": 0
        }
```

while ES no red index, and node would continue to write into it

**Comment by jun0tpyrc** [comment]
occasionally there would be error log for node but only for persisting mini blocks, 
```
INFO [2020-10-30 11:26:00.277]   shard block has been committed successfully epoch = 108 round = 260660 nonce = 259778 shard id = 2 hash = 97c9e10efdcfb4748c06aee3b75d0ca5956bc66a0f47b3cc77b205d1c496f2be
ERROR[2020-10-30 11:26:00.277]   consumePendingNotificationsNoLock(): cannot put miniblock metadata miniblockHash = ab3bd5739bef2fbfe631dc068010ee377afa6816ea719907618a5d00ff6776ef err = cannot save miniblock metadata, hash [ab3bd5739bef2fbfe631dc068010ee377afa6816ea719907618a5d00ff6776ef]: put in epoch: persister for epoch 108 not found
ERROR[2020-10-30 11:26:00.277]   consumePendingNotificationsNoLock(): cannot put miniblock metadata miniblockHash = ab3bd5739bef2fbfe631dc068010ee377afa6816ea719907618a5d00ff6776ef err = cannot save miniblock metadata, hash [ab3bd5739bef2fbfe631dc068010ee377afa6816ea719907618a5d00ff6776ef]: put in epoch: persister for epoch 108 not found
```
could those be relevant? all nodes run with `--log-level="*:INFO"`

**Comment by jun0tpyrc** [comment]
I note the error message is under pruningStorer.go
```
storage/pruning/pruningStorer.go
55:// PruningStorer represents a storer which creates a new persister for each epoch and removes older activePersisters
284:		return fmt.Errorf("put in epoch: persister for epoch %d not found", epoch)
```

would this be relevant to
```
[StoragePruning]
   # If the Enabled flag is set to false, then the storers won't divide epochs into separate dbs
   Enabled = false
```?

**Comment by andreibancioiu** [comment]
Hello @jun0tpyrc,

Thank you for the detailed submission!

Currently, the `DbLookupExtensions` mechanics (which allows one to query historical transactions from the Node, along with their block coordinates) require each epoch to have its own databases.

Setting `[StoragePruning = False]` alters the database management scheme in a way that makes it compatible with `DbLookupExtensions`.

A short explanation for the encountered issue would be as follows:

 - API consumer: Node, please give me the transaction with hash `0xabba`
 - Node: I have `DbLookupExtensions` enabled, therefore I will:
    - Get the epoch number for `0xabba` (from a special global "static" database). Here it is, it's 42.
    - Now, I will open the database for epoch 42 (since it was closed after restart).
    - I cannot open the database for epoch 42, I will report `transaction not found`.

At this point, given the current implementation of `DbLookupExtensions` feature, this would be considered `expected behavior`.

However, after further investigation, we will come back with more details.

**Comment by andreibancioiu** [comment]
By design, `DbLookupExtensions` requires `StoragePruning = true`. This is unlikely to change in the near future.

Though, we will apply extra checks in the configuration of the Node, so that you will not be able to start the process with `DbLookupExtensions.Enabled = true` if requirements are not met.

@jun0tpyrc, thank you again for the detailed analysis! :star2:
