### ISSUE TITLE
[BUG] Chriss Cohn Server Node-0 CPU Util -> Jailed.

### ISSUE THREAD

**Issue by ChrissCohn** [ElrondNetwork/elrond-go#2436]
I have no Idea. It happend at 19:22:10 Server Time.
Node-0 used all CPU it can get and over the hours the process consumed all Available RAM. Hosting Provider apparently saw the issue with all full ressources and restarted the HW-node Today at 12:18 Germany Time. Thats all the Infos i have.

Logfiles in tar.gz Format here: *****
<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.1.6.1-0-gbae61225f/go1.13.5/linux-amd64/d180df9ee8 
Hosting VPS: Netcup with SSD and Dedicated Cores 
</pre>
</details>

**Comment by raduchis** [comment]
Seemed to just happen once. The logs didn't show any problems related to the binary. If it happens again, please reopen.
