### ISSUE TITLE
Observer lost sync (consensus round)

### ISSUE THREAD

**Issue by disruptivedigital** [ElrondNetwork/elrond-go#2450]
Hi team! Something strange happened to one of my mainnet observers on shard 0. Suddenly the observer lost sync (consensus round) and was keeping that way, not even trying to sync back. I waited for about 20 minutes until I rebooted the VPS. No CPU steal, not even high CPU usage at any moment, no memory, network or HDD issue (at least not to my knowledge), just a sudden drop of elrond_connected_nodes at that time when the observer went haywire. The node stuck at the consensus round 1 444 363.

Issue @ server time: 21:16:40 - 07.11.2020
Issue @ monitoring (Netdata) time: 23:16:40 - 07.11.2020

Application version string: v1.1.6.1-0-gbae61225f/go1.14.2/linux-amd64/88dff3eccd
Hosting VPS: AWS Lightsail

Download logs file: http://s.go.ro/i89xrxot

![image](https://user-images.githubusercontent.com/66871992/98452733-9f667f80-215a-11eb-81b1-43389f445a77.png)
![image](https://user-images.githubusercontent.com/66871992/98452745-b9a05d80-215a-11eb-8fcc-ebfb326f86a8.png)
![image](https://user-images.githubusercontent.com/66871992/98452755-c9b83d00-215a-11eb-96f4-d37d842ff47e.png)
![image](https://user-images.githubusercontent.com/66871992/98452762-d3da3b80-215a-11eb-84c4-47b319174b6b.png)

**Comment by iulianpascalau** [comment]
Thanks for reporting this. The log captured correctly the time frame on which the node tried (fruitlessly) to sync with the network. Will further investigate this issue.

**Comment by iulianpascalau** [comment]
Just a question: when the termui printscreen was taken? Before you reset the node or just after?

**Comment by disruptivedigital** [comment]
Before rebooting the VPS.

**Comment by iulianpascalau** [comment]
We found out there was a problem with the NTP synchronization due to a possible bug in a 3-rd party library that we use. We will link to this issue when we will have a fix for this.

**Comment by iulianpascalau** [comment]
Thanks for reporting! The #2458 PR fixes this issue. Please open a new issue if the problem persists after the PR will be included in a release.
