### ISSUE TITLE
[BUG] NTP Sync might caused chronology failure while being proposer on metachain

### ISSUE THREAD

**Issue by viastake** [ElrondNetwork/elrond-go#2457]
<details>
An NTP Sync might have caused a chronology failure while being a proposer on the metachain.

It happened for our metachain validator with key 9b1797ed6666... in ROUND 1487441 (1605042246), around Nov 10 22:04:05 (CET, UTC +1) in the logs.

The temporary node rating dropped accordingly.

Not too long after this, the temporary node rating for our other metachain validator with key eb27bbc01ad4... dropped as well. This may be another issue, but the log is also attached.
<summary>Executing details</summary>
<pre>
Application version string: v1.1.6.1-0-gbae61225f/go1.13.5/linux-amd64
Hosting VPS: Hetzner dedicated server 
</pre>
</details>

[elrond-node-0-9b1797ed6666-final.zip](https://github.com/ElrondNetwork/elrond-go/files/5520737/elrond-node-0-9b1797ed6666-final.zip)
[elrond-node-2-eb27bbc01ad4-final.zip](https://github.com/ElrondNetwork/elrond-go/files/5520761/elrond-node-2-eb27bbc01ad4-final.zip)

![NTPSyncIssueNodeRating](https://user-images.githubusercontent.com/60931849/98745943-d89a2c00-23b4-11eb-8631-112a6b159416.png)

**Comment by iulianpascalau** [comment]
Thanks for reporting! The #2458 PR fixes this issue. Please open a new issue if the problem persists after the PR will be included  in a release.
