### ISSUE TITLE
Stream Reset Issue

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#247]

**Comment by joesixpack** [comment]
[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3356631/logs.zip)

**Comment by drdelphi** [comment]
[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3356879/logs.zip)

**Comment by iulianpascalau** [comment]
PR #252 addresses this issue
