### ISSUE TITLE
[BUG] node stops working suddenly v.1.1.6.3 and can't restart

### ISSUE THREAD

**Issue by josefcoap** [ElrondNetwork/elrond-go#2474]
In testnet, I have one machine with some nodes, this machine and the nodes worked properly in all testnet since more than a month straight. Nothing strange there, all worked fine with all the nodes. Today sudenly node-2 stops working. And when I restarted with systemctl it doesn't sync never more with the network. validatorKey.pem is in place perfectly.

I attached Logs. The node stops working 16th November at 11:40 aprox
[elrond-node-2-.zip](https://github.com/ElrondNetwork/elrond-go/files/5545872/elrond-node-2-.zip)

 

<details>
<summary>Executing details</summary>
<pre>
Application version string: 
Hosting VPS:  
</pre>
</details>

**Comment by Makke27** [comment]
2 of my nodes went offline as well.
11:20 (CET)
error = cannot send request: peer list is empty or errors during the sending, topic: shardBlocks_0_META, crossPeers: 0, intraPeers: 0 epoch = 0 hash = 66c6576014b1221046a3688c9412c78fd5f0f6693286bec0085ae5af3067c212

**Comment by LucianMincu** [comment]
Hi @josefcoap! We'll take a look over it right away can get back with feedback. 🙏 

Hi @Makke27! Could you please extract the logs and attach them here?  🙏

**Comment by iulianpascalau** [comment]
Searching through the logs I found out that the seeder node seems down. This should be a temporary failure, we will fix this ASAP. Thanks for reporting!

**Comment by Makke27** [comment]
Log extract:
[elrond-node-0-extract.zip](https://github.com/ElrondNetwork/elrond-go/files/5546403/elrond-node-0-extract.zip)

**Comment by iulianpascalau** [comment]
@Makke27 same thing, error connecting to seeder. Will fix this asap.

**Comment by iulianpascalau** [comment]
We did a permanent fix in #2503 that will make any node try to reconnect after a while to the seeder. Also, the node now tries to connect to most of the seeders at once.
