### ISSUE TITLE
Wrong Nonce in Block (Forked)

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#248]
[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3356674/logs.zip)

**Comment by soringp** [comment]
I had the same error on my observer on shard 0
[1fbc7a0835b9-2019-03-07-23-16-16.zip](https://github.com/ElrondNetwork/elrond-go/files/3356783/1fbc7a0835b9-2019-03-07-23-16-16.zip)

**Comment by joesixpack** [comment]
Happened again with latest on two observers.  

[logs-rig.zip](https://github.com/ElrondNetwork/elrond-go/files/3364968/logs-rig.zip)
[logs-server.zip](https://github.com/ElrondNetwork/elrond-go/files/3364969/logs-server.zip)

**Comment by SebastianMarian** [comment]
Hello, you are still using an old version of the binary. Please take a look at the first line in both logs I have attached. The first one is yours and it has this text somewhere in the first line "Starting node...", in the new binaries the text should be displayed in this format "Starting node with version vx.x.x", in this case v1.0.7

Please try again with this new version but keep your current data base. Don't delete it. I'm curious to hear some feedback after. Cheers. 

![Screenshot from 2019-07-06 23-18-39](https://user-images.githubusercontent.com/36901555/60760863-05ae3000-a045-11e9-93be-6e78e888107a.png)
![Screenshot from 2019-07-06 23-20-55](https://user-images.githubusercontent.com/36901555/60760866-0c3ca780-a045-11e9-9a7a-366fb1940790.png)

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/60761503-b34a2080-9ffe-11e9-89eb-259472280eb1.png)

**Comment by SebastianMarian** [comment]
OK. I think I know what is the problem. You are trying to run with the last version from the master branch, but this fix is not yet in master as it needs reviews and so on. Until then you can test it from here: issue/#248-Wrong-nonce-in-block not from master

Thanks.

**Comment by joesixpack** [comment]
Allright, a couple of things.

The node version shown above wasn't running the node in the local directory, but it was 1.06 (showing up as 1.04).

Starting the validator with 1.07 without wiping the db incurs repeated "time is out" errrors.

Starting one observer with 1.07 without wiping the db does not incur repeated "time is out" errrors.

Starting another observer with 1.07 with wiping the db incurs repeated "time is out" errrors.

Should I open a new issue for that one?

**Comment by SebastianMarian** [comment]
Of course you can opened it, but please add these logs to can investigate the problem as I could not reproduce this error on my machine. Thanks.

**Comment by SebastianMarian** [comment]
So, I understand that the observer witth v1.0.7 continued to bootstrap without problem, am I right?

**Comment by joesixpack** [comment]
I double-checked the logs again.  The observer with the db wiped had a few time out errors but overall bootstrapped successfully:

![image](https://user-images.githubusercontent.com/23145642/60766766-76fcdb80-a063-11e9-93e1-d244b9be462b.png)

**Comment by joesixpack** [comment]
It's looking like that observer is exceptional for whatever reason.

**Comment by SebastianMarian** [comment]
Ok. Thanks

**Comment by iulianpascalau** [comment]
PR #263 address these issues
