### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#249]
After 24 hours of running, my validator node has died with this message, not contained in the log file:

2019-07-04 22:04:06.355331617 Step 2: signature has been sent

panic: runtime error: slice bounds out of range

goroutine 24130 [running]:
github.com/libp2p/go-msgio.(*reader).ReadMsg(0xc0056c39f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/Sorin/go/pkg/mod/github.com/libp2p/go-msgio@v0.0.2/msgio.go:216 +0x25f
github.com/libp2p/go-libp2p-secio.(*etmReader).fill(0xc00645cd20, 0x634, 0x0)
        C:/Users/Sorin/go/pkg/mod/github.com/libp2p/go-libp2p-secio@v0.1.0/rw.go:132 +0x3f
github.com/libp2p/go-libp2p-secio.(*etmReader).Read(0xc00645cd20, 0xc005fd9c20, 0xc, 0xc, 0x0, 0x0, 0x0)
        C:/Users/Sorin/go/pkg/mod/github.com/libp2p/go-libp2p-secio@v0.1.0/rw.go:171 +0x264
io.ReadAtLeast(0x2c919c8, 0xc00034d440, 0xc005fd9c20, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
        D:/Go/src/io/io.go:310 +0x8f
io.ReadFull(...)
        D:/Go/src/io/io.go:329
github.com/libp2p/go-yamux.(*Session).recvLoop(0xc004a51860, 0x0, 0x0)
        C:/Users/Sorin/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.2/session.go:499 +0xdb
github.com/libp2p/go-yamux.(*Session).recv(0xc004a51860)
        C:/Users/Sorin/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.2/session.go:478 +0x32
created by github.com/libp2p/go-yamux.newSession
        C:/Users/Sorin/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.2/session.go:128 +0x38f

Full log here:

[1fbc7a0835b9-2019-03-07-21-07-26.zip](https://github.com/ElrondNetwork/elrond-go/files/3360392/1fbc7a0835b9-2019-03-07-21-07-26.zip)

[stats 1fbc7a0835b9-2019-03-07-21-07-26.zip](https://github.com/ElrondNetwork/elrond-go/files/3360394/stats.1fbc7a0835b9-2019-03-07-21-07-26.zip)

**Comment by iulianpascalau** [comment]
Asked the libp2p team on this issue: https://github.com/libp2p/go-msgio/issues/16
Waiting for them to respond. This might be correlated to #247 that will be fixed soon.

**Comment by iulianpascalau** [comment]
Will keep this open for a while. Please write a comment here if the problem persists.
