### ISSUE TITLE
[BUG] Keygenerator file-naming

### ISSUE THREAD

**Issue by galadriiel** [ElrondNetwork/elrond-go#2536]
The keygenerator will name the first file as validatorKey.pem. If this file already exists, it will create the next file called
validatorKey.pem.time. This is incompatible with the file-format of the web wallet and will require rename of files. The correct format should be validatorKey.time.pem.

Steps to reproduce: run the keygenerator several times with 
`~/elrond-utils/keygenerator`

**Comment by iulianpascalau** [comment]
This was fixed by #2527. Thanks for reporting the issue!
