### ISSUE TITLE
[BUG] account was not found in RemoveAccount

### ISSUE THREAD

**Issue by anhnd** [ElrondNetwork/elrond-go#2537]
Hello
So I received an error warning like the tittle from the zabbix server. It's from my metachain node. I attached the trimmed syslog file and you can find the error at line 2110 (at 22:17:48 Dec 1st 2020 - UTC+7)
[syslog.zip](https://github.com/ElrondNetwork/elrond-go/files/5629237/syslog.zip)
<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.1.10.0
Hosting VPS: Hezner
</pre>
</details>

**Comment by sasurobert** [comment]
Thanks for the report. The fix which changes the log was merged to master. It will be in the next release. That is a scenario where there was no need to log the error message as it can happen and it is not an error - only an attention.
