### ISSUE TITLE
[BUG] testnet T1.1.12-0 build fails on macos 10.14.6 with Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#2555]
Building testnet T1.1.12-0 is failing on macos 10.16.6 with Undefined symbols for architecture x86_64
Previous testnet T1.1.10-0 would build and run with no error.  

Here are messages from the build that is failing:
<pre>
echo -e "${GREEN}Compiling the Node binary ...${NC}"
Compiling the Node binary ...
echo -e

cd $GOPATH/src/github.com/ElrondNetwork/elrond-go
GO111MODULE=on go mod vendor
cd cmd/node && go build -i -v -ldflags="-X main.appVersion=$SHOWVER-0-$(git describe --tags --long | tail -c 11)"
git describe --tags --long | tail -c 11
github.com/ElrondNetwork/arwen-wasm-vm/wasmer
# github.com/ElrondNetwork/arwen-wasm-vm/wasmer
Undefined symbols for architecture x86_64:
  "_wasmer_instance_cache", referenced from:
      __cgo_a2a2e5914ae2_Cfunc_wasmer_instance_cache in _x002.o
     (maybe you meant: __cgo_a2a2e5914ae2_Cfunc_wasmer_instance_cache)
  "_wasmer_instance_from_cache", referenced from:
      __cgo_a2a2e5914ae2_Cfunc_wasmer_instance_from_cache in _x002.o
     (maybe you meant: __cgo_a2a2e5914ae2_Cfunc_wasmer_instance_from_cache)
  "_wasmer_instance_set_points_limit", referenced from:
      __cgo_a2a2e5914ae2_Cfunc_wasmer_instance_set_points_limit in _x002.o
     (maybe you meant: __cgo_a2a2e5914ae2_Cfunc_wasmer_instance_set_points_limit)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

<details>
<summary>Executing details</summary>
<pre>

Application version string: 
Beagle:elrond-go elrond$ cd cmd/node/
Beagle:node elrond$ pwd
/Users/elrond/go/src/github.com/ElrondNetwork/elrond-go/cmd/node
Beagle:node elrond$ git describe --tags --long
v1.1.12-0-gf5a7d1dbb

Hosting VPS: 
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G4032

GCC version information:
Beagle:~ frankf$ /usr/bin/gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
</pre>
</details>

**Comment by sasurobert** [comment]
Hi! Thanks for the report. We forgot to build the new Wasmer on Mac and add to the release.
If you want to try build https://github.com/ElrondNetwork/wasmer and use the resulting libwasmer.dylib.

**Comment by LucianMincu** [comment]
Hi @frankf1957!

Thanks for pointing this out. The build has been [arwen-0.5.3](https://github.com/ElrondNetwork/elrond-go/pull/2558) made and is pending for merge on `development` branch and will be included and fixed at the next official release. 

Thanks! 🙏
