### ISSUE TITLE
[BUG] Consecutive calls to `account/:address/transaction` with different addresses returns the transactions of the first address

### ISSUE THREAD

**Issue by antonispoulakis** [ElrondNetwork/elrond-go#2560]
There is a bug where if two or more requests are sent close to each other, all the values returned will be the same as the first.

I've tested using the following scenario:
We have 3 addresses with their transactions
```
|    addr    :  transactions  |
|------------:----------------|
|   bob      :  ['tx1','tx2'] |
|   alice    :     ['tx3']    |
|   john     :       []       |
```
If we were to do a batch request for these 3 addresses, depending on what order we do them, we would get one of the following:

```js
getTransactions(addresses) {
// perform requests sequentially
}

// 1nd scenario
getTransactions([bob, alice, john])
// exepected response: [['tx1','tx2'], ['tx3'], []]
// actual response:    [['tx1','tx2'],['tx1','tx2'],['tx1','tx2']]


// 2nd scenario
getTransactions([john, alice, bob])
// exepected response: [[], ['tx3'], ['tx1','tx2']]
// actual response:    [[], [], []]
```
I've found that if I wait at least 2.5 seconds between each request then the correct history will be returned.

This could also be verified in chrome using 2 different tabs, for example:
```
https://api.elrond.com/address/erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry/transactions
https://api.elrond.com/address/erd1xcpsgzcfspjjlegrnafmvv538xsl9fsa7ac9whaw8m62spdeqanqfd7dle/transactions
```
and submitting the first and immediately reloading the second.

These requests were all performed on the mainnet api.

**Comment by bogdan-rosianu** [comment]
Hello, @antonispoulakis ! 
Thank you for reporting this.
We will take a look over the code and the caching system and come up with a fix. We will let you know the next statuses via this issue. 

Thank you!

**Comment by miiu96** [comment]
Hello @antonispoulakis . 
We have found the problem with this API route. 
A pull request that solves the problem was opened on the elrond-proxy-go repository. (https://github.com/ElrondNetwork/elrond-proxy-go/pull/112)

**Comment by miiu96** [comment]
Hello again @antonispoulakis
The fix of the bug that you found is now live on our public api. (https://api.elrond.com)
Thanks again for this and hope everything is ok now.

**Comment by joahn3** [comment]
Hello,

Sorry for asking this here, "erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry" wallet address is the Binance eGLD hot wallet address?

I received from my friend 10 eGLD, and without looking, I sent him back 5 of them, but to the above address and now I was investigating if this is the Binance wallet address so I can open a ticket to them to ask them to re-direct or return the funds to the correct wallet address.
https://explorer.elrond.com/transactions/8aad4712a74d1ee9f83a4ec5a15f1f8759e0763a9e5e1acd53599255a423cc67

Thank you!

**Comment by SeverMM** [comment]
> erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry

Hey @joahn3 - that is indeed a Binance address. Open a support ticket with them, provide the details and you'll likely get it back.

Please join https://t.me/ElrondNetwork or simply open a support request via the web chat on https://elrond.com

Let' keep this space for coding related discussions. All the best!

**Comment by tiagoferro** [comment]
> Hello,
> 
> Sorry for asking this here, "erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry" wallet address is the Binance eGLD hot wallet address?
> 
> I received from my friend 10 eGLD, and without looking, I sent him back 5 of them, but to the above address and now I was investigating if this is the Binance wallet address so I can open a ticket to them to ask them to re-direct or return the funds to the correct wallet address.
> https://explorer.elrond.com/transactions/8aad4712a74d1ee9f83a4ec5a15f1f8759e0763a9e5e1acd53599255a423cc67
> 
> Thank you!

Sry the off topic.

Hello joahn3!

It happened to me the same. I sent some EGLD from Maiar Walltet to Binance, but instead of my wallet adress e sent to that adress erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry. 
Did you solved that situation? Did Binance sent back to your account your coins? 

Thank you.

**Comment by raduchis** [comment]
Hi all, 

Please create a ticket for binance here: https://www.binance.com/en/support/faq/115003798632 

Sadly tehre is nothing we can further do for you. 

Best regards
