### ISSUE TITLE
 header in metablock is not final (on branch, commit 9f4e529)

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#257]
Observer connected to shard 2, using the code from branch "**elrond-go-issue-248-Wrong-nonce-in-block**". 

This error is repeating,  and it did not happen when I was running the observer on shard 0, same node version:

Total txs in pool: 566

header in metablock is not final
header in metablock is not final
requested header with nonce 20646 from network

received requested header with nonce 20646 from network and probable highest nonce is 49259

[6702c52b8486-2019-07-07-09-39-15.zip](https://github.com/ElrondNetwork/elrond-go/files/3365622/6702c52b8486-2019-07-07-09-39-15.zip)

**Comment by soringp** [comment]
The error no longer occurred after node reboot.

**Comment by iulianpascalau** [comment]
Related to #248
