### ISSUE TITLE
Libp2p Build Error

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#262]
The below happens occasionally while building.  The only way to fix is to wipe the go/pkg dir (or possibly the libp2p dir in that). 

![image](https://user-images.githubusercontent.com/23145642/60801616-28674400-a12c-11e9-96a1-d1e4cfbd1c01.png)

**Comment by iulianpascalau** [comment]
Looks like libp2p dependency can not load it's required package from https://github.com/jbenet/go-temp-err-catcher

**Comment by iulianpascalau** [comment]
Could you please add more lines written in console?

**Comment by joesixpack** [comment]
The other commands were the standard ones for building from https://docs.elrond.com/start-a-validator-node/start-the-network/connecting-from-windows

I built with issue/#248-Wrong-nonce-in-block checked out but the libp2p2 error also happened with the first or second release upon commencement of the validator testing.

**Comment by iulianpascalau** [comment]
I meant more log lines printed in console. If it happens again, of course.

**Comment by joesixpack** [comment]
Oh, there was no more.  I cut it off on the @PAUSE message.

**Comment by iulianpascalau** [comment]
Will keep this open for a while to further investigate.

**Comment by joesixpack** [comment]
Ran into this again building the latest but deleting just the libp2p dir didn't fix so had to delete the entire pkgs dir again.  I forgot about including the console log, sorry.

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/62813897-27765900-bac2-11e9-8107-8e3ddeb637f0.png)

**Comment by iulianpascalau** [comment]
If this happens again, please provide some logs. Thanks

**Comment by joesixpack** [comment]
That is the only kind of log there is.  But I can tell you it only seems to happen on Windows and the only way to fix it is to delete the pkg directory so it redownloads everything upon the next build.

**Comment by iulianpascalau** [comment]
Hopefully this won't happen in ubuntu with the new libp2p libs. Reference PR for this: #1721

**Comment by vitja582** [comment]
Hello, I have a problem:
![image](https://user-images.githubusercontent.com/68917248/88693767-fc847b00-d0ff-11ea-88f5-cc4cc0dff5cc.png)
![image](https://user-images.githubusercontent.com/68917248/88693904-263da200-d100-11ea-9244-f3ceed93c273.png)
 can somebody please help? maybe i have done it wrong. I sent ERD ERC20 tokens directly to my staking adress and now i cannot delegate.

**Comment by vitja582** [comment]
In the Metamask wallet it shows like i have funds in my wallet. Something went wrong :( how can i fix it?

**Comment by joesixpack** [comment]
Staking is closed until Mainnet.
