### ISSUE TITLE
[QUESTION] About cross shard contract execution

### ISSUE THREAD

**Issue by zhiqiangxu** [ElrondNetwork/elrond-go#2685]
After reading white paper of elrond , I still have one question about cross shard contract execution.

Let's talk about this by example.

Suppose there's a transaction that does this:

0. account `A` and account `B` are on different shards.
1. transfer some tokens from account `A` to account `B`
2. do something with account `B`
3. if step 2 succeeds, transfer additional tokens from account `A` to account `B`

My question is: if step 2 succeeds, but step 3 fails, will the whole process be rollbacked? If yes, how ?

**Comment by AdoAdoAdo** [comment]
Hi zhiquangxu, currently the handling of errors from chained SC calls needs to be done on callback execution inside the SCs.
So rather than rollback of changes, this is done via error/result handling through callbacks at the SC level (callbacks support is implemented at protocol level but the processing of the callback result needs to be done in the SC).

**Comment by zhiqiangxu** [comment]
Thanks for the reply!

So it's possible that the first part of SC call is succeeded, but the callback is failed inside the SC, in other words, no guarantee that the transaction will either succeed as a whole or nothing ?

**Comment by sasurobert** [comment]
It is possible for callback to fail - it depends on the SC itself. There is no complete guarantee that the transaction will completely success or fail as a whole. However, by the framework and the tools we offer we make it hard for a developer to mess it up. But it is still possible.

**Comment by sasurobert** [comment]
It really depends on how the errors are handled by the SC in all cases.

**Comment by zhiqiangxu** [comment]
Thanks, everything clarified!

**Comment by sasurobert** [comment]
Yes. The original sender - the original transaction must contain all the gas needed for the call on the first contract ,the call on the second and the callback. If there is not enough gas, the transaciton will fail. It is ensured by the protocol when an asyncCall is launch (thus contract A calling contract B) that there will be enough gas for the callback. We call that dynamic gas locking - we lock the gas away for the callBack.

**Comment by zhiqiangxu** [comment]
But the actual gas amount depends on the shard state when executed, how is it calculated for the second and callback transaction ?

**Comment by sasurobert** [comment]
It does not depend on the shard state. When the asnyc call is launched, gas is locked and written in the transaction which has the information about the asyncCall. The async call can use only the gas which is not locked. On the async callback the gasLocked and gasRemaining are accumulated and the final execution starts. The remaining and locked gas is always transported in the subsequent actions.

**Comment by zhiqiangxu** [comment]
If I understand it correctly, it's the responsibility of the original sender to estimate the gasLocked?

**Comment by sasurobert** [comment]
Check the code in Arwen: 

`// ComputeGasLockedForAsync calculates the minimum amount of gas to lock for async callbacks
func (context *meteringContext) ComputeGasLockedForAsync() uint64 {
	baseGasSchedule := context.GasSchedule().BaseOperationCost
	apiGasSchedule := context.GasSchedule().ElrondAPICost
	codeSize := context.host.Runtime().GetSCCodeSize()

	costPerByte := baseGasSchedule.CompilePerByte
	if context.host.IsAheadOfTimeCompileEnabled() {
		costPerByte = baseGasSchedule.AoTPreparePerByte
	}

	// Exact amount of gas required to compile this SC again, to execute the callback
	compilationGasLock := uint64(0)
	if context.host.IsDynamicGasLockingEnabled() {
		compilationGasLock = math.MulUint64(codeSize, costPerByte)
	}

	// Minimum amount required to execute the callback
	executionGasLock := math.AddUint64(apiGasSchedule.AsyncCallStep, apiGasSchedule.AsyncCallbackGasLock)
	gasLockedForAsync := math.AddUint64(compilationGasLock, executionGasLock)

	return gasLockedForAsync
}`

The code checks if there is enough gas for the callback and uses all the remaining gas from the initial transaction.

**Comment by zhiqiangxu** [comment]
Ah, so the actual callback gas cost is calculated precisely by simulating in wasm vm, neat!

What's the usage of `apiCosts[core.AsyncCallStepField]` and `apiCosts[core. AsyncCallbackGasLockField]`, the data flow is `LoadGasScheduleConfig->scProcessor->systemVM`, so it's loaded from file, but not used anywhere after passed to `systemVM`, are they obsolete?

**Comment by zhiqiangxu** [comment]
I see, so the `apiCosts` is just the base cost which is fixed in each epoch, plus variant part by `codeSize*costPerByte`.

So the `gasLockedForAsync` only depends on code size, not the exact wasm instructions executed?

**Comment by sasurobert** [comment]
systemVM.asyncCallbackGasLock this was used before dynamic gas lock was implemented. It was not deleted after.
You do not know the exact wasm instructions on callback. You can only preemptively lock gas. The developer could ensure locally before doing the async call if there is enough gas.

**Comment by zhiqiangxu** [comment]
Is there guarantee that the preemptively locked gas(`codeSize*costPerByte`) will be at least the exact gas needed by callback?

**Comment by sasurobert** [comment]
you cannot guarantee that the locked gas (codeSize*costPerByte)+asyncCallLock is enough. However the SC developer can check before launching any async call if there is enough gas left from the current execution, for whatever is needed in the callback. Later, we will have a feature where the developer can say how much he needs to be locked for the callback.

**Comment by zhiqiangxu** [comment]
Thanks!
