### ISSUE TITLE
[FEAT] ESDT token issue() should return generated token id as a result

### ISSUE THREAD

**Issue by hiddentao** [ElrondNetwork/elrond-go#2704]
At present, once you issue a token you have to query the entire of list of token ids to see what the generated token id was. This is wasteful.

Or at least, I can't seem to find the token id in the transaction `smartContractResults` object.

**Comment by hiddentao** [comment]
Yep that works, thanks. Will I be able to extract this result when doing an `async_call` from within a contract method too?

**Comment by sasurobert** [comment]
yes. of course
