### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by LucianMincu** [ElrondNetwork/elrond-go#273]
After processing about 15m - 20m txs on constant high network load on dual-core 4gb ram, node prints "out of memory" on node console. After that, instance keeps running but no further execution takes place.

**Comment by iulianpascalau** [comment]
Related to #304

**Comment by soringp** [comment]
I'm on v1.0.11 and my node on shard 4 died after 48h of continuous running, with no details written on console other than 390.000 tx in pool.

**Main fatal error logged:**

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x19a0415, 0x16)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc2b8000000, 0x4000000, 0x2e93918)
	/usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x2e77a80, 0x2000, 0x2e77a90, 0x1)
	/usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x2e77a80, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x2e77a80, 0x1, 0x2e93928, 0x7f54a05e10a0)
	/usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x2e77a80, 0x1, 0x23, 0x7f54a05e10a0)
	/usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153

goroutine 61436048 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc059b492d0 sp=0xc059b492c8 pc=0x45cb80
runtime.(*mheap).alloc(0x2e77a80, 0x1, 0x6f68101da1010023, 0x344e13e79176437c)
	/usr/local/go/src/runtime/mheap.go:1047 +0x8a fp=0xc059b49320 sp=0xc059b492d0 pc=0x42662a 

**Secondary non-fatal issue:**

I'm not if this caused the out of mem error, but I forgot to increase the ulimit on my ubuntu machine and I have this error repeating:

{"caller_ok":true,"file":"/home/sorin/go/src/github.com/ElrondNetwork/elrond-go/process/block/shardblock.go","level":"error","line_number":608,"msg":"open /home/sorin/elrond/1.0.11 1de226/db/Epoch_0/Shard_0/MiniBlocks/004075.ldb: too many open files","time":"2019-08-02T15:02:50Z"} 

**Hardware**

i3, 8gb ram, nvme ssd

**Comment by ahakla** [comment]
Hi guys,

I also encountered multiple runtime errors while my new node was still syncing. See the attached error logs. I didn't send the whole zipped logs folder, because it was > 30 MB and Github only accepts 10 MB.
[Alwin_log.zip](https://github.com/ElrondNetwork/elrond-go/files/3565698/Alwin_log.zip)


Best regards,
Alwin

**Comment by iulianpascalau** [comment]
Related to #404
