### ISSUE TITLE
[Bug] Issue when trying to buy elrond

### ISSUE THREAD

**Issue by AnamariaLoznianu** [ElrondNetwork/elrond-go#2739]
I am getting the error that you can see in the attached screenshot when trying to buy eGLD. 
As payment methods, I used Revolut and debit card. None of them worked.
Thank you!
<img width="1666" alt="Screenshot 2021-01-22 at 12 00 42" src="https://user-images.githubusercontent.com/6077997/105477211-3ea30980-5caa-11eb-8f76-cc103d1b92de.png">

**Comment by quezak** [comment]
@AnamariaLoznianu please contact Ramp support chat or email via one of the buttons displayed below the error, and include your user's email. We'll be happy to help you there :)

**Comment by raduchis** [comment]
Ramp support contacted AnamariaLoznianu and they should work it out.
