### ISSUE TITLE
occasional nonce errors on v1.0.8 (bd54836)

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#276]
I've checked the log and found these two non repeating errors, on shard 2:

elrond- go/consensus/spos/commonSubround/subroundBlock.go","level":"info","line_number":330,"msg":"canceled round 12613 in subround (BLOCK), wrong nonce in block\n","time":"2019-07-11T07:00:55+03:00"}

elrond-go/process/block/baseProcess.go","level":"info","line_number":115,"msg":"nonce not match: local block nonce is 11945 and node received block with nonce 11947\n","time":"2019-07-11T07:00:55+03:00"}

Full log:

[1fbc7a0835b9-2019-10-07-16-54-45.zip](https://github.com/ElrondNetwork/elrond-go/files/3381933/1fbc7a0835b9-2019-10-07-16-54-45.zip)

**Comment by JohnStott** [comment]
If of any use, here is a file (shard 4 validator) with 69 of the above instances.
[js.zip](https://github.com/ElrondNetwork/elrond-go/files/3382112/js.zip)

**Comment by iulianpascalau** [comment]
Related to #372. Fixed, will be closed.
