### ISSUE TITLE
could not create local data store: not supported cache type

### ISSUE THREAD

**Issue by Memoi** [ElrondNetwork/elrond-go#286]
Hi,

on windows with a laptop surface pro 6 (core i7 with 16GB of RAM) I have this error:

Starting as observer node...
Starting in shard: 0
closing the leveldb process loop
closing the timed batch handler
could not create local data store: not supported cache type

**Comment by Memoi** [comment]
the problem was with the 5th line at step 3, the letter "v" need to be lowercase, now it's working.

Can you edit the doc ?

https://docs.elrond.com/start-a-validator-node/start-the-network/connecting-from-windows

**Comment by iulianpascalau** [comment]
Right, updated. This can be closed.
