### ISSUE TITLE
[BUG] Delegation Cap reached

### ISSUE THREAD

**Issue by AL-Digital** [ElrondNetwork/elrond-go#2922]
<details>
<summary>It seems like the exact delegation cap can not be reached</summary>
<pre>
If I have a delegation cap of 15.000 xegld I can not delegate 15.000 xegld, but 14.999 xegld I can delegate. The response of the transaction is "total delegation cap reached" even so it should be the exact delegation cap.

I would expect a <= comparison instead of a < comparison for a delegation cap. 

I did not identify the exact code line. It might be elrond-go/vm/systemSmartContracts/delegation.go  Line 1032.
</pre>
</details>

**Comment by sasurobert** [comment]
The code is actually correct: 	
```
if withDelegationCap && checkDelegationCap && globalFund.TotalActive.Cmp(dConfig.MaxDelegationCap) > 0 {
		d.eei.AddReturnMessage("total delegation cap reached")
		return vmcommon.UserError
	}
```

Can you show the actual transaction ? We have several tests for exact delegation cap and they do seem to work.

**Comment by AnchApp** [comment]
Unfortunately I can't rebuild it on testnet right now. Back in March I could not delegate up to the exact delegation cap, only 1 xegld less. The response of the transaction was "total delegation cap reached" for a transaction that would fill up to exact delegation cap. Maybe it has been fixed in the meantime?

**Comment by AL-Digital** [comment]
Unfortunately I can't rebuild the setup on testnet right now. The transactions that did not work in march would have filled the delegation exactly to delegation cap. The response of the transactions was "total delegation cap reached". With 1 xegld less they worked without an error. Maybe the issue has been fixed?

**Comment by gabi-vuls** [comment]
Delegation dApp convertors were incorrect. Issue is solved.
