### ISSUE TITLE
[FEAT] Make observer default to random shard

### ISSUE THREAD

**Issue by galadriiel** [ElrondNetwork/elrond-go#2929]
If not specified in the config for the node, all observers will default to Shard 0. Most users running observers are not going to specify a shard, and even if they do it could still centralize the network towards another shard. Make the default pick random between available shards and meta to make the distribution of the network better.

**Comment by bogdan-rosianu** [comment]
Hi @galadriiel !
Thank you for your suggestion! We will analyze it.

**Comment by iulianpascalau** [comment]
This is done as of the current node version v1.1.51. Thanks for your suggestion :+1:
