### ISSUE TITLE
[BUG] v1.1.37.0-0 MAINNET syncer stuck with message: trie sync in progress for hours after node start

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#2931]
<details>
<summary>Executing details</summary>
<pre>
Application version string: Elrond Node CLI App version v1.1.37.0-0-gbc6a80026/go1.15.10/linux-amd64/b3f0d25a83
Hosting VPS: Hetzner dedicated AX51-NVME - 8 core 128G RAM 2 x 1Tb NVMe SSD mirrored RAID0
</pre>
</details>

I applied OS patches and restarted the system.  The three other nodes on this system started successfully.  One of the nodes did not seem to start correctly.  I could not see it in the explorer and I could not get it's heartbeat information using curl. 

The process was running, but I could not connect using termui.  The process was not listening on it's rest-api-interface port.  I am running with -log-save so I looked at the log file and saw many **_trie sync in progress_** messages coming at the tail of the log file. 

The first message came a few minutes after the node was started at 14:39:43.  I decided to let it run for some time to see if it would finish.  When I came back later and checked, the problem was still ongoing at 17:31:46.  So this has been going for about 3 hours now.  

Here are a few messages from the tail of the log file:
DEBUG[2021-03-26 17:31:42.556] [p2p/libp2p]         [/0/0/]        network connection status                known peers = 3093 connected peers = 48 intra shard validators = 0 intra shard observers = 0 cross shard validators = 0 cross shard observers = 0 unknown = 48 current shard = 0 validators histogram =  observers histogram =  
DEBUG[2021-03-26 17:31:42.556] [p2p/libp2p]         [/0/0/]        network connection metrics               connections/s = 5 disconnections/s = 5 
INFO [2021-03-26 17:31:44.355] [syncer]             [/0/0/]        trie sync in progress                    name = user accounts for shard 2 num received = 433994 num missing = 16679 
INFO [2021-03-26 17:31:46.356] [syncer]             [/0/0/]        trie sync in progress                    name = user accounts for shard 2 num received = 433994 num missing = 16679 

I will collect logs and upload to this issue.

**Comment by frankf1957** [comment]
[elrond-node-0-8eea7a98515a.log.zip](https://github.com/ElrondNetwork/elrond-go/files/6213462/elrond-node-0-8eea7a98515a.log.zip)

**Comment by frankf1957** [comment]
I restarted the node and it was able to sync in about 5 mins.

**Comment by bogdan-rosianu** [comment]
Hello! 

Thank you for the issue. This is a known one that happens from time to time because of the peers not being responsive to state requests.
The fix will follow soon and we will close your issue by that time.

**Comment by iulianpascalau** [comment]
This should be fixed as of the current node version v1.1.51 and up. Thanks for reporting this :+1: . Please open a new issue if the problem persists.
