### ISSUE TITLE
[BUG][EDGE CASE] Delegation contract unDelegate and reDelegation

### ISSUE THREAD

**Issue by mihaieremia** [ElrondNetwork/elrond-go#3092]
Scenario:
As a delegator I have staked 1 eGLD with an agency SC. Besides the active stake I have 0.01 eGLD ready to be claimed or re-delegated.

Following the next transactions the edge case will be triggered.
1. Sending a transaction to unDelegate my full active stake (1 eGLD)
2. Sending a re-delegation transaction for my unclaimed reward of 0.01 eGLD.

Reproduced on mainnet using this wallet erd1fmd662htrgt07xxd8me09newa9s0euzvpz3wp0c4pz78f83grt9qm6pn57
At this moment the delegator ended with less than the minimum amount accepted for active delegation of 1 eGLD. In order for my delegator to unDelegate his last 0.01 eGLD from active stake he will need to delegate another 1 eGLD and afterwards send another unDelegate transaction for the full staked amount of 1.01 eGLD.

Possible mitigations:
The simple one could be a check during the reDelegation process where the transaction is denied in case that the active stake of the delegator is 0. This will enforce the delegator to claim the rewards and not re-delegate.

A more complex solution which will require more transactions made by the delegator (not recommended) is a check during the unDelegate where the amount is the full active stake. If the amount is the full active stake then the SC checks if the delegator has unclaimed rewards with a value less than 1 eGLD. If so the full unDelegate tx will fail until the user claims or re-delegate the dust unclaimed rewards.

**Comment by iulianpascalau** [comment]
Thanks for reporting. Fix is on the way, related to #3094.
