### ISSUE TITLE
[BUG][IMPORT-DB] Templates deprecated for Distro Kibana v1.13.0

### ISSUE THREAD

**Issue by mihaieremia** [ElrondNetwork/elrond-go#3101]
Hey guys,
I tried the import-db using AWS Elastic Search version 7.10 with Distro Kibana v1.13.0. Looks like the templates used are not compatible with this version.

The opendistro.index_state_management.policy_id setting is deprecated starting from version 1.13.0. You can continue to automatically manage newly created indices with the ISM template field.

![image](https://user-images.githubusercontent.com/22687907/118554606-941f8c80-b759-11eb-8058-7b0ee4380f46.png)

**Comment by miiu96** [comment]
Will take a look at this issue and come with feedback. 
Thank you for reporting this.
