### ISSUE TITLE
time is out / tx pool over 100k v1.0.11 (branch, commit 0ed2c93)

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#314]
ubuntu server 18.04, shard 2, code from branch above, started node with reset storage:

The log contains two sets of errors, the first with "too many open files" stopped after running "ulimit -n 65535" and restarting.

I believe the second error started after this, "time is out" with 104k transactions in the pool

[time is out log shard 2.zip](https://github.com/ElrondNetwork/elrond-go/files/3439522/time.is.out.log.shard.2.zip)

edit:
I've updated the node to commit 8005ec and I get 'time is out' as well, but tx pool is 0 now

[log after restart on newer commit.zip](https://github.com/ElrondNetwork/elrond-go/files/3439538/log.after.restart.on.newer.commit.zip)

**Comment by iulianpascalau** [comment]
Related to #404, fixed, will be closed.
