### ISSUE TITLE
[BUG] Tokens with invalid token tickers can be created

### ISSUE THREAD

**Issue by MWFIAE** [ElrondNetwork/elrond-go#3256]
Hi guys!

Just found the following bug. 
The isTickerValid function allows the ticker to have numbers in them. 

https://github.com/ElrondNetwork/elrond-go/blob/937c215952a940d8c55c5cbb5484ef7bb572eda6/vm/systemSmartContracts/esdt.go#L382

However the TokenIdentifier in SmartContract say the identifier is invalid if the ticker does contain a number.

https://github.com/ElrondNetwork/elrond-wasm-rs/blob/master/elrond-wasm/src/types/general/token_identifier.rs#L103

So the issued token wouldn't be usable in Smart Contracts.

An example would be this transaction:
https://testnet-gateway.elrond.com/transaction/05f7172a5fb4358907c57c52cd3836ef9445ec525b171c26612a353e6619a892?withResults=true
![image](https://user-images.githubusercontent.com/6072971/125176200-eae19980-e1d1-11eb-94b7-02db017a3b3b.png)

With the token being issued just fine:
https://testnet-gateway.elrond.com/transaction/97259f811141d6992e817af789bbd490d348866846ac2ee775bf09e3fb890856?withResults=true
![image](https://user-images.githubusercontent.com/6072971/125176221-0f3d7600-e1d2-11eb-9677-d845e3bc3f62.png)

I think the right solution would be to disallow the token from being created, but that would be a breaking change.
So alternatively it might be preferable to update the smart contract method instead.

**Comment by sasurobert** [comment]
Thanks for pointing this out. Ticker validity check in protocol is fine. We will update the RUST frameworks checks for ticker validity

**Comment by bogdan-rosianu** [comment]
Thanks for the issue. It has been fixed in this PR:
https://github.com/ElrondNetwork/elrond-wasm-rs/pull/274
