### ISSUE TITLE
[BUG] testnet T1.2.5.0 node excessive memory usage / memory leak?

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#3296]
<details>
<summary>Executing details</summary>
<pre>
Application version string: Elrond Node CLI App version T1.2.5.0-0-gcee54336e/go1.15.10/linux-amd64/d57cd5df30
Hosting VPS: Hetzner CPX41 - 8 vCPU, 16G ram, 240G HDD
</pre>
</details>

I got an alert at 09:35 UTC from one of my testnet VPS - ram used 98%.  This VPS has 16G ram 8 vCPU and I am running 2 nodes (validators).  My 2 nodes have been running for 258h.  One node has resident size 5.758G the other has resident size 7.977G.  The virtual memory size of each node is around 12.9G.  I have 2 validators running on another VPS in similar state.  

I will upload and attach logs to this issue.  

I also have mem__softrestart_\*_GB.pprof files in /elrond-nodes/node-\*/health-records, I will zip them and upload to this issue too.

**Comment by frankf1957** [comment]
[elrond-node-health-records-20210725-1500.tar.gz](https://github.com/ElrondNetwork/elrond-go/files/6874085/elrond-node-health-records-20210725-1500.tar.gz)

**Comment by frankf1957** [comment]
[elrond-node-logs-20210725-1450.tar.gz.part-aa.gz](https://github.com/ElrondNetwork/elrond-go/files/6874116/elrond-node-logs-20210725-1450.tar.gz.part-aa.gz)
[elrond-node-logs-20210725-1450.tar.gz.part-ab.gz](https://github.com/ElrondNetwork/elrond-go/files/6874117/elrond-node-logs-20210725-1450.tar.gz.part-ab.gz)
[elrond-node-logs-20210725-1450.tar.gz.part-ac.gz](https://github.com/ElrondNetwork/elrond-go/files/6874120/elrond-node-logs-20210725-1450.tar.gz.part-ac.gz)

**Comment by frankf1957** [comment]
The size of elrond-node-logs-20210725-1450.tar.gz is 58M, which exceeds the maximum size I could attach in a comment, so I needed to split the file and upload the 3 parts.  Also, Github would not recognize and allow files ending in .part-ax, so I had to rename them, adding a .gz suffix to the filename.  

Here are some sha256sum, so you can check file integrity.

```
$ ls -l elrond-node-logs-20210725-1450.tar.gz 
-rw-rw-r-- 1 elrond elrond 58015659 Jul 25 14:51 elrond-node-logs-20210725-1450.tar.gz

$ sha256sum elrond-node-logs-20210725-1450.tar.gz 
7730e6dc29674af6333dbd0bbb284f170bf6048ad6e64bac7d463bf87945f5d6  elrond-node-logs-20210725-1450.tar.gz

$ split -b 20m elrond-node-logs-20210725-1450.tar.gz -- 'elrond-node-logs-20210725-1450.tar.gz.part-'

$ ln elrond-node-logs-20210725-1450.tar.gz.part-aa{,.gz}
$ ln elrond-node-logs-20210725-1450.tar.gz.part-ab{,.gz}
$ ln elrond-node-logs-20210725-1450.tar.gz.part-ac{,.gz}

$ sha256sum *.part-a*
c16112ddc7ddd085ec2261f0383ba81cb27cee9ca4819ce54bf4b2faa674f538  elrond-node-logs-20210725-1450.tar.gz.part-aa
c16112ddc7ddd085ec2261f0383ba81cb27cee9ca4819ce54bf4b2faa674f538  elrond-node-logs-20210725-1450.tar.gz.part-aa.gz
f4dfbb6c68ed0f7d4ad02f4ee678d3b66ea64ad657dfb79cd7671c47dc5feb94  elrond-node-logs-20210725-1450.tar.gz.part-ab
f4dfbb6c68ed0f7d4ad02f4ee678d3b66ea64ad657dfb79cd7671c47dc5feb94  elrond-node-logs-20210725-1450.tar.gz.part-ab.gz
23faba238f1fcb3886ce29c989a3c5e3c78dcda1d26de38228e4856fd530721d  elrond-node-logs-20210725-1450.tar.gz.part-ac
23faba238f1fcb3886ce29c989a3c5e3c78dcda1d26de38228e4856fd530721d  elrond-node-logs-20210725-1450.tar.gz.part-ac.gz
```

**Comment by frankf1957** [comment]
To extract: (I'm sure you already known how to do this, but just in case anyone else is peeking ...)
```
$ cat *.part-a?.gz* | tar -tzvf -
-rw-rw-r-- elrond/elrond 274877370 2021-07-25 14:51 elrond-node-0-4bb412300e4b.log
-rw-rw-r-- elrond/elrond 275244923 2021-07-25 14:51 elrond-node-1-4bb41456007e.log
```
change the -tzvf to -xzvf to extract.

**Comment by iulianpascalau** [comment]
Thanks, fixes are on the way. Related to #3300.
