### ISSUE TITLE
panic: runtime error: slice bounds out of range v1.0.11 (master)

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#331]
the node just died, on windows, no error message on screen:
log with details:

[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3455370/logs.zip)

**Comment by elrondscammer2** [comment]
That's enough!! Cheating bastards.
The price keeps falling. People don't trust you. ERD doesn't buy. What do you boys do for a living?

**Comment by iulianpascalau** [comment]
Hopefully this is fixed as of 2020.05.13. Will close for now, will reopen if it persists.
