### ISSUE TITLE
[BUG] erdpy testnet config fails due to constants.go having moved to a different folder

### ISSUE THREAD

**Issue by col000r** [ElrondNetwork/elrond-go#3359]
I'm following the [crowdfunding tutorial](https://docs.elrond.com/developers/tutorials/crowdfunding-p1/) - in the video they start a testnet by right-clicking on the testnet.toml file and choosing "**Start Fresh Testnet**" 

This leads to it running `erdpy testnet config`, which fails with `[Errno 2] No such file or directory [...]/core/constants.go` - it seems this file has moved from core to common.

How can I make this work?

I'm on erdpy 1.0.15 - just installed everything today following the tutorial

**Comment by andreibancioiu** [comment]
Hello @col000r!

Thank you for the issue & sorry for the delay.

Newer versions of `erdpy`'s local testnet should not present this issue anymore (as of February 2022, the current version is `1.0.25`).

Please let us know if you still experience the issue.

Furthermore, for the future, please use the following repository for issues about **erdpy**: https://github.com/ElrondNetwork/elrond-sdk-erdpy
