### ISSUE TITLE
[BUG] Elrond testnet Docker image not available as described in the documentation

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/elrond-go#3366]
`elrondnetwork/elrond-go-node-testnet` does not work as described in the documentation https://docs.elrond.com/validators/testnet/use-docker-testnet/

There is no `latest` tag on Docker hub.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/49922/130316242-ffcf74d8-e885-4db0-9c1a-c44a74ebd0c2.png">

Thus, the testnet node cannot be installed as instructed.

```
[~/code/rosetta-chain/chains/elrond/node]% docker-compose up 
Creating network "node_default" with the default driver
Pulling elrond (elrondnetwork/elrond-go-node-testnet:latest)...
ERROR: manifest for elrondnetwork/elrond-go-node-testnet:latest not found: manifest unknown: manifest unknown
```

**Comment by gabi-vuls** [comment]
Hello miohtama!

Thank you for your feedback.
You are right ! We are working on it. 

"latest" tag on testnet docker image will be available soon. 
For the moment please take manually the latest tag available : T1.2.12.0
Thank you !
