### ISSUE TITLE
[BUG] Docker testnet image required environment and parameters are not documented

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/elrond-go#3369]
On the page https://docs.elrond.com/validators/testnet/use-docker-testnet/ the example refers to 

* BLS file

* Validator key

Both should be documented. While the validator key is self-explanatory, there is no information for an outsider reader to know what's BLS file and where to get it.

**Comment by gabi-vuls** [comment]
Hello Miohtama, 

Thank you for your feedback. 
The documentation has been updated. Please check [here]( https://docs.elrond.com/validators/key-management/validator-keys/).
