### ISSUE TITLE
[FEAT] Tell in the console logs if the node is operating correctly

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/elrond-go#3374]
[There was a recent issue with testnet reboot](https://github.com/ElrondNetwork/elrond-go/issues/3371).

During diagnosing this issue, it become apparent that the elrond node does not report to the user if it is working correctly or not. The user cannot deduct from the Elrond node output if the node is receiving data from the peer-to-peer network.

Suggestion:

* Add a console log message when the node is receiving new rounds (blocks, connections, etc. whatever is defined as the yard stick of correct functioning)

* The message needs to be visible on the default logging level `INFO`

* Do not spam the logs with this message

* Show the message when the node receives the first new data from the blockchain 

* Subsequently, show the message for every 15 minutes (so that the operator can see from the logs if the node stopped working)

The message could be e.g.

```
Node running. The current round is 9018, connected to 500 other nodes.
```

As this is a new feature and if someone stumbles upon this, you can manually diagnose the node over RPC (assuming RPC is enabled):

```shell
curl http://localhost:9999/node/status | jq
```

And see if the `erd_current_round` variable is increasing.

**Comment by iulianpascalau** [comment]
The output log line can appear whenever a new block has been committed and the node's computed consensus round matches the block it just committed. Good suggestion. :+1:
