### ISSUE TITLE
Fork detected loop error on v1.0.11

### ISSUE THREAD

**Issue by MichaelStephen2428** [ElrondNetwork/elrond-go#338]
Fork was detected at a certain nonce and hash and it started the rollback mechanism to a previous header with nonce and hash and after that it ended the fork choice. After that it started to request the same header with the same hash as the one where fork was detected and went into a loop, with rollback, request, fork detected, rollback, request, fork detected and so on. 

Logs: http://s000.tinyupload.com/?file_id=22154264996387362718

**Comment by iulianpascalau** [comment]
Related to #409

**Comment by iulianpascalau** [comment]
Related to #409, fixed, will be closed.
