### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#339]
Ulimit is unlimited.

[log.zip](https://github.com/ElrondNetwork/elrond-go/files/3464864/log.zip)

**Comment by joesixpack** [comment]
Seems to keep happening on Linux after a certain amount of time.

![image](https://user-images.githubusercontent.com/23145642/62625420-ffc49c80-b8d9-11e9-8ea3-9c4e31cb739a.png)

**Comment by LucianMincu** [comment]
What is the output of `ulimit -n` in your case?

**Comment by josefcoap** [comment]
Lucian, I had the same problem yesterday with one node. If I write "ulimit -n" I get 1024 as a result. I need to change something? I must be in the installation guide?

**Comment by LucianMincu** [comment]
1. Here's a version of changing the variable of ulimit at runtime.

`#!/bin/bash

# set limit
ulimit -n 65535

cd /%GOPATH%/src/github.com/ElrondNetwork/elrond-go/cmd/node/ && ./node `

This will set the ulimit to 65535 for the node application.


2. Have seen this approach on other projects in this space, and have to deal with this problem like @ethereum / geth  or @ipfs ipfs/go-ipfs#3792

One of the best approach is to split this issue into actionable items - meta-issues like this are always hard to deal with and especially hard to close.

Therefore we'll leave this issue open until we can come back to it and cap the software file limit to a fixed number.

**Comment by joesixpack** [comment]
My ulimit is unlimited.
