### ISSUE TITLE
[BUG] Tesnet T1.2.16.0 - termui Epoch info showing 0 / 0 rounds

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#3428]
<details>
<summary>Executing details</summary>
<pre>
Application version string: Elrond Node CLI App version T1.2.16.0-0-g8864f6cfa/go1.16.7/linux-amd64/d57cd5df30
Hosting VPS: Hetzner CPX-41 - Linux 5.4.0-81-generic x86_64
</details>

**Comment by frankf1957** [comment]
![Screen Shot 2021-09-08 at 11 57 17](https://user-images.githubusercontent.com/49395034/132545173-a54a1930-9350-4ea8-a8e3-e309ef1ae4b1.png)

**Comment by frankf1957** [comment]
Closed - not an issue.  TermUI now clears itself at epoch change so those 0 values were temporary.

**Comment by frankf1957** [comment]
![Screen Shot 2021-09-08 at 13 19 56](https://user-images.githubusercontent.com/49395034/132555344-5d968438-5c1f-4d0d-8f51-133d092e8da3.png)

**Comment by iulianpascalau** [comment]
Fixes are merged. Will be available in the upcoming binary releases v1.2.17 (and up). This issue will be close. Thanks once again!
