### ISSUE TITLE
[BUG] unexpected failure if config folder doesnt exist

### ISSUE THREAD

**Issue by huttarichard** [ElrondNetwork/elrond-go#3471]
We've been using docker in production to run elrond, and its just pleasure. However last update was kinda problematic as we saw some issues during testing.

In multistage build of [docker image](https://github.com/ElrondNetwork/elrond-go/blob/master/docker/elrond/Dockerfile#L16) you guys are pulling `node` binary to different image. This is cool except it copies whole folder. 

Apperently if [config folder](https://github.com/ElrondNetwork/elrond-go/tree/master/cmd/node) doesnt exist in same directory as binary, it starts acting funny. It report no errors, dies rightaway.

I would expect to get an error, that for example file xy in config is missing.
Its bit scarry as nothing changed really on our end.

This is original docker file we used to build elrond node: https://github.com/stakecamp/provisioning/blob/master/Dockerfile (it is for previous versions)

**Comment by LucianMincu** [comment]
Fixed in the PR #3473 and will get included in the next release. 

Thanks a lot for reporting this @huttarichard. 🙏
