### ISSUE TITLE
[BUG]Transaction Pending and Timed Out

### ISSUE THREAD

**Issue by Cosminauh** [ElrondNetwork/elrond-go#3621]
On Maiar Exchange:
1. Use Harvest
2. Sign the transaction on Maiar
3. Transaction goes in Pending
4. Transaction goes Time Out
<img width="627" alt="Bug_EGLD" src="https://user-images.githubusercontent.com/95538778/144716568-b48af6f6-c8c4-48ad-b66d-afd6a89d44d9.PNG">

**Comment by Cosminauh** [comment]
P1

**Comment by Cosminauh** [comment]
Transaction not getting processed even if 
There is no congestion on the system.
Trxid
4025391687112db00e649ff2a498dd2a3c3c2b91521d3d4b1718bec498ada7f0

Thank you.

**Comment by LucianMincu** [comment]
Hi @Cosminauh! 

Seems like it did went trough. 

https://explorer.elrond.com/transactions/4025391687112db00e649ff2a498dd2a3c3c2b91521d3d4b1718bec498ada7f0

Did the error came from the Maiar Exchange UI?
Can you provide a screenshot? 

Thanks!

**Comment by Cosminauh** [comment]
Hi Lucian,

Thank you for the answer.
Yes, I checked after some time in the explorer and the transaction has
passed.

In the Maiar Exchange UI it was showing still "In Progress".
I had to disconnect from Maiar Exchange and to re-connect to find the
transaction as processed.

Sorry, I did not took a screeshot but if the situation will re-apprear I
will let you know.

Thank you.



sâm., 11 dec. 2021, 13:52 Lucian Mincu ***@***.***> a scris:

**Comment by LucianMincu** [comment]
As long the UI says still in progress it's everything ok, if you have waited a bit more the UI APIs would have updated the values as well.

There is a time buffer placed in, for the cases when there are too many users at the same time on the loop.

In case the transaction fails on the UI and it's processed on the explorer, that's a case for a bug report.

Thanks a lot for your contribution. 🙏
