### ISSUE TITLE
sync validation error testnet v1.0.11

### ISSUE THREAD

**Issue by longhuynh2811** [ElrondNetwork/elrond-go#363]
I encountered a sync validation error when resetting the node at the time. After resetting the node I was forced to run synchronously at nonce 56322, the front panel was synchronized, I was repeated 3 times before, currently I am in shard 1. is there a way to fix the error? this?

![1](https://user-images.githubusercontent.com/53088104/62834106-0a808800-bc72-11e9-83a2-f358cd84eda1.png)
![2](https://user-images.githubusercontent.com/53088104/62834107-0a808800-bc72-11e9-9dd9-db2379b4f5c9.png)
![3](https://user-images.githubusercontent.com/53088104/62834108-0b191e80-bc72-11e9-801d-10050c3809f9.png)
![4](https://user-images.githubusercontent.com/53088104/62834109-0b191e80-bc72-11e9-80cd-3578aa453357.png)

**Comment by sasurobert** [comment]
related and resolved by #409
