### ISSUE TITLE
[BUG] Token transactions via relay transactions do not get indexed correctly

### ISSUE THREAD

**Issue by MWFIAE** [ElrondNetwork/elrond-go#3657]
I used the tokens/:ident/transactions endpoint of https://api.elrond.com to get all relevant transactions of my nfts.
However, I noticed that relay transactions are not included in the result. 
After taking a look into the API code it seems like this isn't the APIs fault, because it just queries the elastic search.
Therefore it's clear that the transaction is not correctly indexed.

Request:
https://devnet-api.elrond.com/tokens/CITEM-ac24f8/transactions?size=1000

Response:
https://pastebin.com/ifqCGKJ4

Example of a transaction that is missing:
https://devnet-explorer.elrond.com/transactions/41df441a5c5adc416941632776883373144ce4e7cb06252bf941f9c4ae036bc1

Example of the same transaction without relay that was correctly included in the response:
https://devnet-explorer.elrond.com/transactions/27a81a53a0e58874ea64baef37f2ca59c06c54c5c6a993acb22417e40f8d3fe2

Hope this can be quickly fixed, as it is essential for my project :)

Have a nice day,
Martin Wagner

**Comment by miiu96** [comment]
Hello. 
Thank you for your feedback. 
We are aware of this problem and the fix is done --> soon will be live on the `devnet` and `testnet`

**Comment by MWFIAE** [comment]
Thank you 🙏 

Do we have any estimation on when the new version will be deployed on devnet? It's been a while and it would be great if I could continue testing our integration with this :)

**Comment by MWFIAE** [comment]
@miiu96 Any news on that? 🙏

**Comment by miiu96** [comment]
@MWFIAE Hello, these modifications are live on the `testnet` for the moment  In order to verify if your problem is solved can you check on the `testnet`

**Comment by miiu96** [comment]
Hello. 
I think now it is solved can you check again to ensure everything is ok?

**Comment by MWFIAE** [comment]
Hi @miiu96 

Some relay calls are now part of the transactions of this endpoint:
https://devnet-api.elrond.com./transactions?token=CITEM-8e4222&size=1000

However, it misses many transactions that involve nft transfers from a smart contract.
In a best-case scenario, the endpoint would return all transactions involving certain events in their logs. (or the logs of the results) 
This would include: ESDTTransfer, ESDTLocalMint, ESDTLocalBurn, ESDTNFTTransfer, ESDTNFTCreate, ESDTNFTAddQuantity, ESDTNFTBurn, MultiESDTNFTTransfer, etc.

For a list of transactions involving our token you can take a look at the following accounts:
This is the relayer account (I think every transaction there involves our nfts)
https://devnet-explorer.elrond.com/accounts/erd1m4xe92cgs7jtfd794ytxumrjwuvvzwyd8zhpwdj3y4tvl83e6k7qvyjut6

This is the admin account (every transaction besides the claimUser transactions should involve our nfts)
https://devnet-explorer.elrond.com/accounts/erd1q0wrkm2ydjchtqdu7qh039sam2rlfr97p2030ad9ts8w59496uyq05x6an



And this endpoint seems to no longer allow collections as it returns "Token not found"
https://devnet-api.elrond.com/tokens/CITEM-8e4222/transactions

PS: I switched to devnet again as it's easier to evaluate the transactions from the ongoing closed alpha :)
If your changes are only live on testnet I will have to build up some examples again which might take a while 😅

**Comment by miiu96** [comment]
I will take a look at your examples to check again if there is still a problem. 
The changes should be also on the devnet.

**Comment by MWFIAE** [comment]
The issue was that I was using the transactions endpoint and not the transfers endpoint. 
The later not only contains direct transactions, but all transfers, including smart contract results :)
