### ISSUE TITLE
[BUG] Library not loaded: @executable_path/libwasmer_darwin_amd64.dylib

### ISSUE THREAD

**Issue by zhiqiangxu** [ElrondNetwork/elrond-go#3666]
When I run `make test-v` under project root, lots of such errors:

```
FAIL    github.com/ElrondNetwork/elrond-go/integrationTests/factory/statusComponents    1.497s
dyld: Library not loaded: @executable_path/libwasmer_darwin_amd64.dylib
  Referenced from: /var/folders/ym/c42xcdhn78g0s97z3ycj2yw00000gn/T/go-build307865916/b1205/staking.test
  Reason: image not found
```

I'm on Mac .

**Comment by gabi-vuls** [comment]
Hello @zhiqiangxu ,
Thanks for the feedback.

We are currently working on a full fix for this problem.
To make it work, please try the following workaround: 
- install erdpy  -> https://docs.elrond.com/sdk-and-tools/erdpy/installing-erdpy/
- install all dependencies using erdpy ->  `erdpy install deps all`

Thank you !
