### ISSUE TITLE
[BUG] /transaction-Hook not working with Maiar App

### ISSUE THREAD

**Issue by janniksam** [ElrondNetwork/elrond-go#3718]
### Bugged in: 

DevNet, TestNet, MainNet

### Example-Url:

https://devnet-wallet.elrond.com/hook/transaction/?receiver=erd1qqqqqqqqqqqqqpgqeln5f496avlt65xnwas6vdykg7jjre00d8ssg90c7e&value=100000000000000000&gasLimit=6147500&gasPrice=1000000000&data=offer@ac83be4b4263a04da675c31b750ae684@45474c44@0de0b6b3a7640000@

### Description:
When you connect with Ledger / Keyfile / PEM, the correct mask is being show:

![Working scenario](https://user-images.githubusercontent.com/15337798/150686815-f0d700b1-b77c-44fd-92c3-852b9eb9cd52.png)

However, when you connect with your Maiar walllet (scanning the QR code or doing it everything on the phone), the web wallet also shows this screen for a fraction of a second, but then refreshes to this:

![With maiar app](https://user-images.githubusercontent.com/15337798/150687033-64092724-0471-4377-b9a1-6e81cf7980f0.png)

As you can see, the receiver everything else disappears....

### Severity:

This is really bad, because my work-in-progress bot currently can't be used with Maiar App Wallets, which is very likely be used by a majority of users :(

Please fix this!

**Comment by arhtudormorar** [comment]
This issue has been resolved in current mainnet version.
Thanks for your input!

**Comment by janniksam** [comment]
Hello @arhtudormorar. It got a little better now, I am able to do it once now.

BUT all consecutive transactions end up here....

![image](https://user-images.githubusercontent.com/15337798/151048971-e7c8712d-41f5-4d4a-88db-2ecd405a12f3.png)

... if I don't clear all my browser data STRG + F5 after the first transaction.

**Comment by arhtudormorar** [comment]
The bug has been resolved in all environments.
Please let us know of any further issues.
Thanks!
