### ISSUE TITLE
[BUG] Second transaction with Maiar app doesn't work /transaction-Hook

### ISSUE THREAD

**Issue by janniksam** [ElrondNetwork/elrond-go#3721]
### Bug reproducable in: 

DevNet, TestNet, MainNet

### Example-Url:

https://devnet-wallet.elrond.com/hook/transaction/?receiver=erd1qqqqqqqqqqqqqpgqeln5f496avlt65xnwas6vdykg7jjre00d8ssg90c7e&value=100000000000000000&gasLimit=6147500&gasPrice=1000000000&data=offer@ac83be4b4263a04da675c31b750ae684@45474c44@0de0b6b3a7640000@

### Description:
This is a follow up bug for #3718.

The first transaction works now as it should, BUT all following transactions end up in an empty mask.

**Specific steps:**

1. Make a transaction using the link above and connect with Maiar, finish it

2. Open the link again, log in with Maiar again and you will end up at the empty mask in the screenshot below:

![image](https://user-images.githubusercontent.com/15337798/151049623-7ceaac97-b3b6-45e0-9989-5cbe944cc317.png)

**Comment by arhtudormorar** [comment]
The bug has been resolved in all environments.
Please let us know of any further issues.
Thanks!
