### ISSUE TITLE
Latency increased?

### ISSUE THREAD

**Issue by ahakla** [ElrondNetwork/elrond-go#380]
When playing CryptoBubbles.io, I noticed that the start time was delayed for up to 6 seconds, after having waited for 15 seconds after the previous round.
I guess this is due to a higher latency in the CB testnet? I also noticed on the CB testnet Explorer that the most recent transactions were sometimes visible after more than 20 seconds.
Any clues about this?

Edit: Latency now 7 seconds in the CB Testnet Explorer, so today, no extra delays! But... also just a small amount of CB players. ;)

**Comment by iulianpascalau** [comment]
Hopefully this is fixed as of today 2020.05.13.
