### ISSUE TITLE
[BUG] Get hyperblock/by-nonce 8365843 error

### ISSUE THREAD

**Issue by JohnsonCaii** [ElrondNetwork/elrond-go#3882]
Hi team. I just updated the version of `elrond-node-obs` to `v1.2.38`. `elrond-proxy` remains the same (v1.1.16).

The request will be failed when trying to get the hypberblock by nonce of height **8365843**.

The CURL command and response is as follow (all our 3 nodes have this issue):
```
$ curl http://127.0.0.1:8079/hyperblock/by-nonce/8365843
{"data":null,"error":"sending request error","code":"internal_issue"}
```

At the same time, I've captured the log of proxy container:
```
ERROR[2022-03-07 02:19:25.203]   block request                            observer = http://10.0.0.6:8080/ error =
[GIN] 2022/03/07 - 02:19:25 | 500 |    2.517323ms |        [10.0.0.1](http://10.0.0.1/) | GET      "/hyperblock/by-nonce/8365843"
```

If I use `curl https://gateway.elrond.com/hyperblock/by-nonce/8365843` to get this info, everything fine. So it must be some issues on our side.

Any suggestions? Thanks in advance.

**Comment by airstring** [comment]
@JohnsonCaii  Hello, how did you solve that？I have the exact same problem.
