### ISSUE TITLE
DEVNET - Unstake transaction is failing with: error signalError

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#4043]
<details>
<summary>Executing details</summary>
<pre>
Application version string: Elrond Node CLI App version D1.3.19.0-0-g49f85285b/go1.17.9/linux-amd64/5970e3a12f
Hosting VPS: Hetzner Cloud VPS - CPX41.  8vCPU, 16GB RAM, 240GB disk.  
</pre>
</details>

I am running 6 validator nodes on DEVNET, all nodes are staked using the web-wallet and staked from the same account.  I tried to unStake 2 nodes this morning, and the transaction failed with error signalError.  I logged out from the wallet, and refreshed using \<command\>+\<shift\>+R, and tried a second time with same results.  

macOS 10.14.6, Google Chrome Version 100.0.4896.127 (Official Build) (x86_64).

Staking wallet address:
erd1gzzc96mpflcq5lnat0dz7dryv74fnqu6ddkwrqnk32jk508hgkgqyfc5wy

Failing transactions:
697f6989d4258d60a78299dac8c1c02b2dc96705d718ffeecc9ba5e38083e0ab
2c4cb884c1e920b7f84eae8a52b52fdaaa2feb318f8f05859f44a926da5f48e4
bcf0cdeeea65bdf9e1f469247aa57d5de97d3883b6ff6a4d900ce701b06aca76
b1adfec860b28ba24d8a9e8b88a95b65867c5793a5b506e69aefa4a8ae6ef333

**Comment by bogdan-rosianu** [comment]
Hello! 

This happens because, as the error displayed on the explorer says ("unStake is not possible as too many left"), there wouldn't be enough nodes left to achieve consensus if yours would leave. So it's not possible at the moment to unstake them. This is the expected behavior of the system.
