### ISSUE TITLE
node is connected to 0 peers on v1.0.15

### ISSUE THREAD

**Issue by rolandmoldovan** [ElrondNetwork/elrond-go#408]
![connected_to_0_peers](https://user-images.githubusercontent.com/46964104/63944527-56a53800-ca7a-11e9-9fc9-5534ee5f00e8.png)

After (node) restart, it started to run normally.

**Comment by iulianpascalau** [comment]
Hopefully this is fixed as of today 2020.05.13. Reference PR #1721
