### ISSUE TITLE
node v1.0.15 build fail with go1.13 on Linux

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#424]
I've connected remotely to someone who was having issues setting up the node on Linux.

I've recommended the _golang.sh script from elrond-go-scripts, but there's a problem, it downloads go1.13, and this is not compatible with v1.0.15, it fails at compile time.

In the end I had to remove go1.13 and install go1.12.9 and the problem goes away

**Comment by iulianpascalau** [comment]
Resolved in v1.0.16 by  PRs #430 and #427
