### ISSUE TITLE
elrond-go fails to build on arm64 / aarch64 (redirectStderrLinux.go:12:9: undefined: syscall.Dup2)

### ISSUE THREAD

**Issue by LucianMincu** [ElrondNetwork/elrond-go#425]
Problem:
`ubuntu@ubuntu:~/go/src/github.com/ElrondNetwork/elrond-go/cmd/node$ go build
 github.com/ElrondNetwork/elrond-go/core/logger
../../core/logger/redirectStderrLinux.go:12:9: undefined: syscall.Dup2`

Solution: changes in the redirectStderrLinux.go
`//+build linux darwin
package logger
import (
        "os"
        "syscall"
)
// redirectStderr redirects the output of the stderr to the file passed in
func redirectStderr(f *os.File) error {
        err := syscall.Dup2(int(f.Fd()), int(os.Stderr.Fd()))
        if err != nil {
                return err
        }
        return nil
}`

Fix: new vestion of redirectStderrLinux.go
`//+build linux darwin
package logger
import (
        "os"
        "syscall"
)
// redirectStderr redirects the output of the stderr to the file passed in
func redirectStderr(f *os.File) error {
        err := syscall.Dup3(int(f.Fd()), int(os.Stderr.Fd()), os.O_CREATE|os.O_APPEND|os.O_WRONLY)
        if err != nil {
                return err
        }
        return nil
}`

pull request will follow shortly

**Comment by LucianMincu** [comment]
https://github.com/ElrondNetwork/elrond-go/pull/426

**Comment by iulianpascalau** [comment]
This is solved by PR #426
