### ISSUE TITLE
invalid public key string - arm64 / aarch64

### ISSUE THREAD

**Issue by LucianMincu** [ElrondNetwork/elrond-go#444]
After fixing the compilation problem for arm64 architecture, once the ./node is started, the following errors occurs:

`ubuntu@ubuntu:~/go/src/github.com/ElrondNetwork/elrond-go/cmd/node$ ./node -use-log-view
Starting node with version undefined/go1.12.9/linux-arm64

Process ID: 741

/home/ubuntu/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/config/config.toml
Initialized with config from: ./config/config.toml
/home/ubuntu/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/config/p2p.toml
Initialized with p2p config from: ./config/p2p.toml
/home/ubuntu/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/config/genesis.json
Initialized with genesis config from: ./config/genesis.json
/home/ubuntu/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/config/nodesSetup.json
Initialized with nodes config from: ./config/nodesSetup.json
NTP average clock offset: 0s
Start time formatted: Fri Sep 13 17:50:00 UTC 2019
Start time in seconds: 1568397000
/home/ubuntu/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/config/initialNodesSk.pem
Starting with public key: 32854f7742a70f06b9a87ff0b62b1795a93418b65af3b2e557d2cd1ed5c0876f6ac341bdf39f1092771a7486ec03d905dd10036a4193a631c6e8a0d8958fab6334a0d6a97e2ffc3de456d8ddc52542445ed75c17944aedf2040ab22b18d8e7eb0cb9030ed38aeca03dc1131680fe0d89e1127c89e39a50167f716ed388dfacd8
Starting as observer node...
Starting in shard: 0
/home/ubuntu/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/config/server.toml
No views for current node
No AppStatusHandler used. Started with NilStatusHandler
creatingShardDataPool from config
invalid public key string`  

Raspberry Pi 4 - Ubuntu server 18.04 (arm64) + go1.12.9 linux/arm64

**Comment by LucianMincu** [comment]
@iulianpascalau can be this somehow related to the same issue ? 

one community validator reported this today:
![image](https://user-images.githubusercontent.com/30302419/64994603-5958b780-d8d9-11e9-874b-8eb34474a8b6.png)

**Comment by AdoAdoAdo** [comment]
Created pull request on kyber to fix the issue
https://github.com/dedis/kyber/pull/393

**Comment by AdoAdoAdo** [comment]
issue merged on Oct 8 and new version referenced in elrond-go
