### ISSUE TITLE
port opening problem windows 10

### ISSUE THREAD

**Issue by grazzza** [ElrondNetwork/elrond-go#445]
![1](https://user-images.githubusercontent.com/36407272/64929080-834ea300-d821-11e9-8849-ae2046abf29e.png)
why problem with connecting  udp 123

**Comment by iulianpascalau** [comment]
port 123 is used for NTP synchronization. We will look into that.

**Comment by iulianpascalau** [comment]
This might happen also on other OSes as the NTP servers have flooding protection. We have changed the NTP syncer to try from different sources if one fail. #640 addresses this issue.
