### ISSUE TITLE
Problem after disconnecting the Internet

### ISSUE THREAD

**Issue by Mystic999** [ElrondNetwork/elrond-go#451]
![0001](https://user-images.githubusercontent.com/52602853/65053745-1c420300-d975-11e9-80f8-1fd2cbd796ef.jpg)

At night there was an unexpected shutdown of the Internet. After the restart, the node sync stuck on block 7695-7696.
On my machine two nodes work and both have problems with synchronization. One works in Windows 10, the second through VirtualBox in Windows 7. I wanted to test it. Each node has its own keys. One node is on shard 4, the second is " meta".

![Аннотация 2019-09-17 180602](https://user-images.githubusercontent.com/52602853/65054174-d5a0d880-d975-11e9-961d-7e7398026089.jpg)

I decided to restart the node from the very first step by deleting the "go" folder and creating it again. I re-created the node on the manual from the site and ran it again. But that didn't solve my problem. At new synchronization I also got stuck on the block 7696
![Аннотация 2019-09-17 180957](https://user-images.githubusercontent.com/52602853/65054811-dc7c1b00-d976-11e9-986e-26752681daad.jpg)

How to solve the problem ? My nickname in Riot: mystic999

![Аннотация 2019-09-17 181238](https://user-images.githubusercontent.com/52602853/65054826-e1d96580-d976-11e9-803c-5704666a35a3.jpg)

logs and stats :
[Node.zip](https://github.com/ElrondNetwork/elrond-go/files/3624339/Node.zip)

**Comment by iulianpascalau** [comment]
This was a block syncer problem and was fixed. Related to #454
