### ISSUE TITLE
Time is Out & Forking (v1.0.16)

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#452]
Experiencing time is out, forking and/or no/slow syncing issues this run (via Docker on Ubuntu 18.04 LTS).  Shard 4 logs will encompass the new node after the patch fix.

[shard1.zip](https://github.com/ElrondNetwork/elrond-go/files/3623446/shard1.zip)
[shard2.zip](https://github.com/ElrondNetwork/elrond-go/files/3623447/shard2.zip)
[shard2b.zip](https://github.com/ElrondNetwork/elrond-go/files/3623448/shard2b.zip)
[shard3.zip](https://github.com/ElrondNetwork/elrond-go/files/3623449/shard3.zip)
[shard3b.zip](https://github.com/ElrondNetwork/elrond-go/files/3623450/shard3b.zip)
[shard4.zip](https://github.com/ElrondNetwork/elrond-go/files/3623451/shard4.zip)
[shard5.zip](https://github.com/ElrondNetwork/elrond-go/files/3623452/shard5.zip)

**Comment by iulianpascalau** [comment]
Fixed. Related to #454
