### ISSUE TITLE
Invalid Key

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#467]
Hey guys,
My v1.0.16 testnet node was running smooth, until I changed the name of the folder elrond-go to elrond-go-16. Then I run node.exe again and the firewall (Windows Defender) asked me if I should give it permission, which I answered "no" this time.
![firewall](https://user-images.githubusercontent.com/32204735/65369600-ec864a00-dc57-11e9-993d-805f7192a597.png)

Running node.exe again, I got the Invalid Key error.
![invalid v16](https://user-images.githubusercontent.com/32204735/65369609-fe67ed00-dc57-11e9-9f68-b540921a85c5.jpg)

I run again node.exe with -use-log-view parameter and the last line before the app exited, were:
No views for current node
No AppStatusHandler used. Started with NilStatusHandler
could not create local data store: file missing [file=MANIFEST-000000]

Then I installed v1.0.17, built it and tried to reproduce this issue. The result is different, as the Invalid Key message appears only for a second, after which the app resumes normal operation, so it seems the issue is partially fixed.
![invalid](https://user-images.githubusercontent.com/32204735/65369636-438c1f00-dc58-11e9-893d-441f01b044f3.png)
One second later ...
![normal](https://user-images.githubusercontent.com/32204735/65369638-48e96980-dc58-11e9-9c41-ccddc6ae0435.png)

----------------------------

Tried to reproduce it with v1.0.16 built from scratch and I get the same behaviour as in v1.0.17.
The only difference is that I disabled the AntiVirus (Avast).
After re-enabling it and trying to reproduce the issue again, node.exe crashed with the messages:
No AppStatusHandler used. Started with NilStatusHandler
closing the leveldb process loop
closing the timed batch handler
closing the timed batch handler
closing the leveldb process loop
closing the timed batch handler
closing the leveldb process loop
closing the timed batch handler
closing the leveldb process loop
could not create local data store: file missing [file=MANIFEST-000000]

The conclusion is that the issue is infact produced by the AntiVirus running node.exe in SandBox for a few seconds.

**Comment by iulianpascalau** [comment]
Regarding the invalid key, that is a display issue, something did not render well. Will add task to repair this behavior. Regarding the antivirus, we have to check that ans investigate if there is a workaround for that.

**Comment by iulianpascalau** [comment]
Closed due to the fact that we do not support windows for now and the display issue was fixed
