### ISSUE TITLE
[Bug]: Merge will take all positions even if only some of them were selected

### ISSUE THREAD

**Issue by Cosminauh** [ElrondNetwork/elrond-go#4808]
### Contact Details

hyperc2k@gmail.com

### Description

Merge will take all positions even if only some of them were selected

### Steps to reproduce

Merge will take all positions even if only some of them were selected.

Hash 27652c3a9ec62f754070ef08a4f2fba260e878b3005af500d93ceb5cce09a155

Steps to reproduce:
1. After conversion multiple XMEX positions existed.
2. Selected with checkbox to MERGE only 4 positions out of 5
3. The transaction merged all 5 possition without permission

Target was to have a XMEX position to be unlocked in 2024 and other in 2025.
Now, a single position was created in to be unlocked in 2025.

Kindly correct the defect and repair the material loss. Now all my XMEX positions are merged to a single position instead of 2 
with 2 different unlock dates.

### On which network is the bug manifesting itself?

Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ovidiuolteanu** [comment]
Thank you for the notification. Your report will be forwarded to the exchange team and investigated as soon as possible.
In hindsight, we always strongly recommend users to be wary and critic of the transactions they sign that they're always conforming the operations they are trying to perform. 
This is not stated as an excuse for the team not to maintain a high standard of quality in the products we're developing. We are constantly striving for the best products that work without issues, but we want to remind users that they bear responsibility as well when signing and consenting to operations they want to perform.

On a side note, this is the repo for "The official implementation of the Elrond protocol, written in golang", it doesn't have anything to do with the Exchange. For future assistance, please reach out to the telegram support groups or the exchange related repos, such as sc-dex-rs.
