### ISSUE TITLE
$GOPATH not defined in README.md

### ISSUE THREAD

**Issue by ahakla** [ElrondNetwork/elrond-go#492]
First users installing elrond-go from the instructions in `README.md` will not have set their $GOPATH yet. Yet it is referenced in:
https://github.com/ElrondNetwork/elrond-go/blob/master/README.md

Solution could be something like:
`# set $GOPATH if not set and export to ~/.profile along with Go binary path`
`if [[ $GOPATH=="" ]]; then`
`	GOPATH="$HOME/go"`
`fi`

**Comment by iulianpascalau** [comment]
done, please follow #1736. Thanks.
