### ISSUE TITLE
v1.0.19 - shard 0 - constant cpu 100% - logs attached

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#505]
![image](https://user-images.githubusercontent.com/16723548/66025694-c1291800-e4ff-11e9-8c78-fd8ad683fbd5.png)

[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3679934/logs.zip)

**Comment by drdelphi** [comment]
[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3679941/logs.zip)

**Comment by iulianpascalau** [comment]
This was caused by a bad config. Fixed as of today, 2019.12.03
