### ISSUE TITLE
v1.0.23 linux connected 20 peers, lots of RAM used

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#519]
[logs.tar.gz](https://github.com/ElrondNetwork/elrond-go/files/3701497/logs.tar.gz)

**Comment by drdelphi** [comment]
As RAM usage increases, the connected peers count decreases...

**Comment by LucianMincu** [comment]
This problem seem to be related to process where a node is connected to the network prior to the genesis time. Both CPU & RAM increases in load, collecting more data about the processes will be the next step. Note: the load might increase with the numbers of peers connected to the network.

**Comment by iulianpascalau** [comment]
Fixed, related with #517
