### ISSUE TITLE
server.toml indicates wrong parameter

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#522]
After several trying to type node.exe, at least but not last i can connected again to server, i just tried the new update.bat script,,

but the problem is not in there, cause when i try again to do manual connection, the server.toml issue is back, it's prevent us to get connected to the server, after several try, at least but not last, i can get connected again,,

and then now is the time for trying to run the additional node, and it comes again, this time i just copied (just 1 file), server.toml from cmd/node/config, and overwritten it who were in Node1/config/ directory, and it did it, solve the issue by now, but i think it'll still remain, unless some one has fixing it,,

i found this issue on windows, i use windows 7 sp 1, didn't know how it goes on another os

Thank you for reading my report

**Comment by scraido** [comment]
I found it we can automatically connect, by double clicking the node.exe that lies on the respective folder instead of replacing the server.toml file with the same file or by typing node.exe on the right directory on cmd, but that will bring a message to us;

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.

**Comment by scraido** [comment]
just for adding, this (debug mode), has bring me additional issue of suddenly close of cmd windows, for the main cmd and the additional cmd windows,, and you can say this as suddenly network connection lost, just for wrap my report before this i experience 1 Node can run near 8Gb of RAM (with double clicking), and i've report this before on 9/10 21.20 UTC +7 @ElrondValidators tele account, Ty

**Comment by iulianpascalau** [comment]
server.toml is used for just for elastic search component and, if left blank, will not cause node operation problems. The message `[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.` is just a message from the web server, no issues there. We are no longer support windows so this issue can be closed.
