### ISSUE TITLE
v1.0.23  lots of RAM used in OS Win10

### ISSUE THREAD

**Issue by longhuynh2811** [ElrondNetwork/elrond-go#523]
The node consumes too much data Ram in the direction of increasing steadily

Up to now has restarted Nodes 2 - 3 times!

[45ef903587fe.zip](https://github.com/ElrondNetwork/elrond-go/files/3708031/45ef903587fe.zip)
[399dea8949e4.zip](https://github.com/ElrondNetwork/elrond-go/files/3708032/399dea8949e4.zip)
![image](https://user-images.githubusercontent.com/53088104/66493575-7ea7a280-eae0-11e9-8d69-756a37b535fa.png)

**Comment by longhuynh2811** [comment]
after the next 2 hours
[45ef903587fe.zip](https://github.com/ElrondNetwork/elrond-go/files/3708648/45ef903587fe.zip)
[Uploading 399dea8949e4.zip…]()


![image](https://user-images.githubusercontent.com/53088104/66504624-bec45080-eaf3-11e9-91d5-db6ca6e6d07d.png)

**Comment by longhuynh2811** [comment]
![image](https://user-images.githubusercontent.com/53088104/66505178-fda6d600-eaf4-11e9-9bdd-f7a09f188e0a.png)

**Comment by longhuynh2811** [comment]
after resetting node 30s!

![image](https://user-images.githubusercontent.com/53088104/66505290-4199db00-eaf5-11e9-9eb7-45de86a4618b.png)

**Comment by longhuynh2811** [comment]
after resetting node 2'30s!

![image](https://user-images.githubusercontent.com/53088104/66505500-b79e4200-eaf5-11e9-8d02-b12771491b99.png)

**Comment by longhuynh2811** [comment]
after resetting node 20'

![image](https://user-images.githubusercontent.com/53088104/66506979-8bd08b80-eaf8-11e9-9137-d1a481a8b603.png)

**Comment by longhuynh2811** [comment]
after resetting node 1 Hour

![image](https://user-images.githubusercontent.com/53088104/66510049-80805e80-eafe-11e9-9fd0-d996be8dc494.png)

**Comment by longhuynh2811** [comment]
after resetting node 1,5 Hour

![image](https://user-images.githubusercontent.com/53088104/66512139-8aa45c00-eb02-11e9-9844-63ee483c91a2.png)

**Comment by longhuynh2811** [comment]
Ram max, causing Win to collapse!

screenshot after relaunching!
![image](https://user-images.githubusercontent.com/53088104/66529313-2e0a6680-eb2d-11e9-9f10-a9a8fab5d681.png)
[45ef903587fe.zip](https://github.com/ElrondNetwork/elrond-go/files/3709917/45ef903587fe.zip)
[399dea8949e4.zip](https://github.com/ElrondNetwork/elrond-go/files/3709918/399dea8949e4.zip)

**Comment by longhuynh2811** [comment]
[45ef903587fe.zip](https://github.com/ElrondNetwork/elrond-go/files/3711461/45ef903587fe.zip)
[399dea8949e4.zip](https://github.com/ElrondNetwork/elrond-go/files/3711462/399dea8949e4.zip)

**Comment by bogdan-rosianu** [comment]
We have found the problem regarding the increasing memory usage. A patch will be released soon.

**Comment by iulianpascalau** [comment]
Fixed as of tags/v1.0.24 . The problem was cause by a bad config in heartbeat storer that caused frequent writing and added a large number of waiting go routines.
