### ISSUE TITLE
Feature request - random name when NodeDisplayName not set

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#535]
I'd like to suggest that if NodeDisplayName isn't set, it gets a random name assigned, rather than everyone "N/A".  (Can be random characters, based on say MAC address or public key, from a word list, etc.)  This way we can help those who struggle to set it (and / or don't want to interrupt their uptime) find themselves on the validator list by 
`cat $GOPATH/src/github.com/ElrondNetwork/elrond-go-node-*/config/config.toml | grep NodeDisplayName

**Comment by iulianpascalau** [comment]
The solution, as of today, 2020.05.13 is to keep the N/A string but in a tone of gray as to distinguish between other strings.
