### ISSUE TITLE
Connection to network suddenly lost

### ISSUE THREAD

**Issue by ahakla** [ElrondNetwork/elrond-go#537]
Just saw that one of multiple nodes on a VPS was suddenly offline.

So I checked and the node was still running, it just lost connection to the network somehow! Very strange. I stopped and restarted it and now it's synced again and connected to 332 peers and counting.

It was on shard 3. The machine has multiple nodes running on different REST-API ports, this one was on 8080.

Any idea what could've happened?

[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3718706/logs.zip)
[stats.zip](https://github.com/ElrondNetwork/elrond-go/files/3718707/stats.zip)

**Comment by iulianpascalau** [comment]
Related to this, when starting a node, connection count is 0
[stats&logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3784156/stats.logs.zip)

**Comment by iulianpascalau** [comment]
This is still a known issue. Will be closed after the fix is done.

**Comment by joesixpack** [comment]
Wouldn't surprise me if its related to p2plib....  seen this kind of issue with other projects.

**Comment by iulianpascalau** [comment]
This is a known issue. Will remain open until a fix will be available.

**Comment by elrondscammer2** [comment]
Binance Delist/ Don't Buy ERD/ELROND / Erd scam coin / Erd big dump
ERD BIG DUMP SELL NOW ...ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
 
 Beniamin Mincu 
ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
  ERD BIG DUMP SELL NOW ...

**Comment by iulianpascalau** [comment]
Hopefully this was fixed by #1721. Please reopen a new issue if the problem persists.
