### ISSUE TITLE
Negative values on age

### ISSUE THREAD

**Issue by alexpatru** [ElrondNetwork/elrond-go#540]
I checked my balance on https://testnet.elrond.com/?fbclid=IwAR0oziqDY3Edk0D18Hfxp5AKTQ0PJBR8ov0iLhgs50M-mRD_bwowNL-RX1U#/address/32ef1f68e26a3036d7550ca81c30031ba2d207b731ab077ac912ff38a708fae8 and I've seen that same ages have negative values.

![Capture](https://user-images.githubusercontent.com/17834606/66700099-9ad05d00-ecf5-11e9-8358-0d55c7379dbc.PNG)

**Comment by iulianpascalau** [comment]
This is fixed as of today, 2020.05.13.
