### ISSUE TITLE
loosing connection  windows 10

### ISSUE THREAD

**Issue by grazzza** [ElrondNetwork/elrond-go#541]
![Untitled](https://user-images.githubusercontent.com/36407272/66700157-e1ba5480-eced-11e9-8699-3e98ff50b188.png)
[node prob.pdf](https://github.com/ElrondNetwork/elrond-go/files/3720537/node.prob.pdf)

**Comment by iulianpascalau** [comment]
This doesn't seems to be an issue if a node is "only" connected to 200 peers. Judging from above picture, all seems ok.
