### ISSUE TITLE
NTP Timeout Errors, No Syncing

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#542]
Nodes will no longer have sync state true nor participate in consensus rounds, despite restarting.  This is after quite a bit of Internet downtime and numerous router reboots.  Very little bandwidth is currently being consumed.  I needed to hard reboot the affected Linux machines to have the nodes start syncing.

![image](https://user-images.githubusercontent.com/23145642/66707411-ddde0080-ecf4-11e9-80e7-ca3d243a752f.png)

[logs1.zip](https://github.com/ElrondNetwork/elrond-go/files/3721137/logs1.zip)
[logs2.zip](https://github.com/ElrondNetwork/elrond-go/files/3721138/logs2.zip)
[logs3.zip](https://github.com/ElrondNetwork/elrond-go/files/3721139/logs3.zip)
[logs4.zip](https://github.com/ElrondNetwork/elrond-go/files/3721140/logs4.zip)

**Comment by iulianpascalau** [comment]
This might have been related to poor internet connections. There is an opened issue regarding lost of nodes connectivity. Related to #537 Will close this one and move the discussion there.
