### ISSUE TITLE
Bogus number of transactions after fork choice

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#547]
[logs (3).zip](https://github.com/ElrondNetwork/elrond-go/files/3724493/logs.3.zip)
![txsbug](https://user-images.githubusercontent.com/32204735/66752672-9f824600-ee9a-11e9-818a-158bef601ae7.png)

**Comment by miiu96** [comment]
It is o problem because the counter for number of processed transactions is not persistent when the node is restarted. Will be fixed.

**Comment by miiu96** [comment]
https://github.com/ElrondNetwork/elrond-go/pull/583 will be fixed with this PR
