### ISSUE TITLE
Incorrect 'consensus accepted' counter value on termui v1.0.28

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#553]
The issue happens when the node cannot sync, and it keeps rolling back, increasing the counter when catching up.
It gets to 1400 quickly. (shard 3)

![image](https://user-images.githubusercontent.com/16723548/66961000-5c7cca00-f076-11e9-98de-bd52d04d6db8.png)

[logs.zip](https://drive.google.com/file/d/1T57gu9R0ByHOY9CAWWYcqIZbJk9Pj6n9/view?usp=sharing)

**Comment by miiu96** [comment]
It is a problem because on roll back the counter for that metrics is not decremented. Will be fixed.
