### ISSUE TITLE
Current consensus round decreasing after stopping the Node

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#565]
Hi i'm about to let my Shard 4 can catch-up another shard so i stopping my other 2 Node, but when i start the stopping Node again, it seems it has forgotten it's last current consensus rd., before my shard 3 got in rd. 33K just differs about 10 - 20 rd from the leader, but after stop it decreasing to 25K, i think it should can remembering it last rd. that it experienced before so we don't have wait synching that much, thank you

Ps. btw current picture is from my another shard, just for looking if the issue will be happen to my other shard, this time is shard 2, before i try with shard 3, it's also the same issue and if we stop it again and then run it turn out keep decreasing to about 7k - 15k round, even before my current rd. was just diff. about 10 - 20 rd below the leader, ty very much for looking of my issue, maybe else also experienced it but they still doesn't realizing it,,

![photo6147974466085431697](https://user-images.githubusercontent.com/44559893/67116660-160ca400-f20b-11e9-8731-432087342fff.jpg)

![photo6147974466085431698](https://user-images.githubusercontent.com/44559893/67116982-bf539a00-f20b-11e9-85f1-a904c22f2d7c.jpg)

![photo6147974466085431699](https://user-images.githubusercontent.com/44559893/67116998-c8dd0200-f20b-11e9-9d9d-9c35857fba19.jpg)

**Comment by miiu96** [comment]
Hello, is not a bug is normal this behavior because here its a rollback because last notarized block
by metachain is the block with Nonce = 4901 and your current  synchronized block was  the block with Nonce=5368.

**Comment by iulianpascalau** [comment]
As stated by @miiu96 , this is a normal behavior of the node when the notarized block nonce by matachain is lower then the current nonce.
