### ISSUE TITLE
block nonce stuck 

### ISSUE THREAD

**Issue by grazzza** [ElrondNetwork/elrond-go#567]
![sahard 3](https://user-images.githubusercontent.com/36407272/67143438-b85c7400-f26b-11e9-8a29-9efec85d4b5f.png)
![shard 3](https://user-images.githubusercontent.com/36407272/67143448-c14d4580-f26b-11e9-9e6c-42426e20e24a.png)
my shard 3 node stuck on block nonce 8888  and stay there after a few restarts.

**Comment by iulianpascalau** [comment]
There were some sync/propose issues regarding v1.0.31. They have been corrected. Also, the network received counter was hopefully corrected. Will be closed for now.
