### ISSUE TITLE
Incorrect network peak recv / sent rates

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#572]
+-Network - recv:------------------------------------------------------+
|        0% / rate: 96.27 KB/s / peak rate: 17179869118.64 GB/s        |
+----------------------------------------------------------------------+
+-Network - sent:------------------------------------------------------+
|        0% / rate: 721.22 KB/s / peak rate: 17179869090.50 GB/s       |
+----------------------------------------------------------------------+

**Comment by miiu96** [comment]
it is a problem in our formula It is a problem in our method of calculating network traffic. It will be resolved.
