### ISSUE TITLE
v1.0.31 - on restart shard 2 node resyncs from very old block

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#576]
I've tested this on a validator and on an observer node. 
Even it the nodes are fully synced (~32000), on a clean node restart, the resync starts from ~6000.

Logged on restart: 
"bootstrap from shard block with nonce **6027** which contains last notarized meta block \n last notarized meta block is 5335 and final notarized meta block is 5335 \n"

Every subsequent restart lowers the beginning sync node, as seen in logs, but not that dramatically, just a few blocks back.

There was a single node, observers included, with an old version 1.0.25, could this be the first to sync every time?

**Edit: Same thing happened on shard 0, 1, 3 and 4.** 
**Meta didn't experience this problem**, on restart it resumes close to max.

Before restart:
![s2 before restart](https://user-images.githubusercontent.com/16723548/67234412-c669ea80-f44d-11e9-8689-d9c04c7a8ac2.PNG)

After restart, see max block:
![s2 after restart](https://user-images.githubusercontent.com/16723548/67234448-d8e42400-f44d-11e9-9e59-3c4f3b4802fe.PNG)

**Only after a while the correct max block is identified:**
![s2 after a while](https://user-images.githubusercontent.com/16723548/67234482-ea2d3080-f44d-11e9-90c2-f0d133a9e7a4.PNG)

[shard 2 logs v1.0.31](https://drive.google.com/file/d/1DLnkfXRy2L48sjuF5ndJJfl0-JDIt7y0/view?usp=sharing)

**Comment by iulianpascalau** [comment]
There were some sync/propose issues in the v1.0.31. They have been corrected.
