### ISSUE TITLE
Excessive logging

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#592]
Between versions .34 and .35 my shard 0 validator collected almost 800Mb in logs.  The switch before was also around 700 Mb.  The other shards seem much more light wrt logs.

I also noticed that when running through systemd, the --use-log-view switch is required to start and that yields /var/log/journal to be around 4 GB on my VPS'es.  (And 2,5 GB on my single shard validator.)

This seems excessive.  It might create unexpected system bottlenecks, in particular the large journal.

**Comment by iulianpascalau** [comment]
The excessive logging was caused by the fact that fork choice rules were triggered too often. There were sync/propose issues in the above mentioned versions that caused the node to enter in infinite loops. They were all corrected by now and also the logger system do not log everything now.
