### ISSUE TITLE
Move DestinationShardAsObserver to prefs.toml

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#598]
Following the move of NodeDisplayName, i'd say it would be consistent if DestinationShardAsObserver was also put in prefs.toml (and hopefully install scripts can preserve these settings).

**Comment by bogdan-rosianu** [comment]
Hello. Good suggestion. I will discuss with my colleagues about it and we can move it. 
Thank you !

**Comment by iulianpascalau** [comment]
This is done. Related to #531. Can be closed.
