### ISSUE TITLE
Transaction does not go through when data string contains "<>"

### ISSUE THREAD

**Issue by rolandmoldovan** [ElrondNetwork/elrond-go#600]
The transactions seems to fail when certain special characters such as "<>" are present in the data field.

Example transaction payload:

`{"nonce":3,"sender":"e6cc20045bcc00b39fbba030bff09d1bd49ab019d7c045bd54a65fec6cb86dd8","receiver":"ac9068ab2b29bb5b4fa7f56fa589649a46a5baf3675687fe9ffafc9d234c3d43","value":10000,"gasPrice":10,"gasLimit":121,"data":"~!@#$%^&*()_+}{|\":?><","signature":"681d61bbfde3226ca4a0f1cdc42ae304a73e73b44d07a6a199ea3893a4617ce4debc77155ff565c9f0bdc1e8b82d0f0dadac8f44e0fa63596683f91961040503"}`

**Comment by bogdan-rosianu** [comment]
Hello !
I have analyzed the issue and found a solution. The fix will be pushed soon

**Comment by iulianpascalau** [comment]
This is fixed, reference PR #1513
