### ISSUE TITLE
Negative values on timestamp

### ISSUE THREAD

**Issue by alexpatru** [ElrondNetwork/elrond-go#602]
I did a transaction on the network during the first mission on BoN.
I checked the transaction and i saw a negative value on timestamp.

![Capture](https://user-images.githubusercontent.com/17834606/67806304-4241e380-fa9b-11e9-9cdc-1a15ce28acf2.PNG)

**Comment by AdoAdoAdo** [comment]
was your browser page opened in a virtual machine?

**Comment by alexpatru** [comment]
No, it was open on a base OS (Windows 10 enterprise) and the browser was Chrome( version 78.0.3904)

**Comment by iulianpascalau** [comment]
It might be related to a bad clock synchronization.

**Comment by iulianpascalau** [comment]
Fixed, as of today, 2020.05.13
