### ISSUE TITLE
Balance doesn't update

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#603]
In the testnet explorer, the balance isn't updating when 
* new MN rewards come in
* you hit the refresh balance button
* you do a hard-page reload (holding shift).

**Comment by koen84** [comment]
It's not updating in "my wallet" nor in "address" pages.

**Comment by koen84** [comment]
Possibly related, after trying to send 2x 10 tERD there's a discrepancy between what shows under "my wallet" and "address", the former is stuck while the later updates with validator rewards.  Hardrefreshing the "my wallet" page doesn't help.

![WalletBalance](https://user-images.githubusercontent.com/8461454/68268743-b3633700-0057-11ea-9b4f-2e630dc54c16.png)

**Comment by koen84** [comment]
I wonder if it's a "login timeout" of sorts that doesn't properly propagate to the browser ?

**Comment by iulianpascalau** [comment]
The wallet/testnet website have been in heavy development phase. The newer versions will be available soon.

**Comment by iulianpascalau** [comment]
This is fixed as of today, 2020.05.13.
