### ISSUE TITLE
manual transaction pending for a long time (v1.0.36)

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#604]
Multiple transactions from shard 4 to other shards, generated manually using the web wallet, were pending at the same time:

This was pending for ~40 min:
https://testnet.elrond.com/#/tx/96b99ac364dabc361e121a32e73d7b48e4629ecef3da9451ccd24c36b10f951c

Another for ~20min, diff destination shard:
https://testnet.elrond.com/#/tx/d4009b87e088e81e28c684aafe81d94e66fe8dad33a595c398bb6d8aebee6399

There were other examples as well.

Somehow they where completed successfully around the same time.

The problem seems isolated and no longer happens at the time I'm writing this.

**Comment by iulianpascalau** [comment]
There were issues processing transactions in that version. They have been corrected now.
