### ISSUE TITLE
Incorrect shards in explorer

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#605]
I was checking MN reward transactions in explorer and could not make sense of the shard designations, looks like a bug?

Explorer shards | validator shard
------------ | -------------
4 > 1 | 4 
3 > 3 | M
0 > 0 | 0 
 1 > 2 | 1
2 > 2 | 2
3 > 0 | 3

**Comment by koen84** [comment]
So they might be in reverse ?  Just leaves metachain...

**Comment by soringp** [comment]
The validator shard does not matter, only the address is allocated to a specific shard.

On the transaction details page you can see the shard id for each address involved, your examples are a summary.

You can easily identify the shard for a given address with this "map":
https://github.com/soringp/elrond-stuff/blob/master/5%20Shards%20Address%20Distribution%20Last%20Hex.PNG

**Comment by iulianpascalau** [comment]
Great explanation @soringp . This issue can be closed now.
