### ISSUE TITLE
Web wallet form data not cleared between transactions

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#606]
I send a transaction with my food item in the data field.  Then I send a second transaction to a different address, and I do not enter anything in the data field. The web form looks like it was properly cleared, but, when I examine the transactions, the data entered in the first transaction, is also entered in the second transaction.  

I am using Brave browser on MacOS Sierra.  Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit).

From:
cbac1d2f2142d0534f9779e913be2c6b54095528c06b031302ee22b9f3425e20
Transaction #1:
849db7c32e1c4220fa5049a2b7f9838764e8e9c90cc58058d2da95d52048f7d3
Transaction #2:
203616213b226687d5e30967176e0c24f671a293541e89eff3971bcce62f595e

**Comment by iulianpascalau** [comment]
The wallet/explorer pages are in heavy development now and new versions will be available soon. This issue should be corrected on those versions.

**Comment by frankf1957** [comment]
Close because this issue is stale and no longer relevant.
