### ISSUE TITLE
Sudden Internet outage

### ISSUE THREAD

**Issue by Mystic999** [ElrondNetwork/elrond-go#612]
Today my cloud provider was doing maintenance related to the network connection. The instances themselves were not disabled. Only the Internet connection was interrupted only partially. In this case the ssh connection remains active.

 All my 3 nodes on shards 0, 1, 2 behaved the same.  As a result, nodes simply stopped increasing blocks.

![Аннотация 2019-10-30 212713](https://user-images.githubusercontent.com/52602853/67887443-4f72d700-fb5c-11e9-983b-1b779045dcfe.jpg)

For several hours, the Explorer showed the nodes offline. At the same time, about 10 peers were connected to each. The sync was green and showed full sync. Only blocks did not increase. 

![Аннотация 2019-10-30 212822](https://user-images.githubusercontent.com/52602853/67887467-5d285c80-fb5c-11e9-927a-7f056bf6d86c.jpg)

Both values froze. New peers do not join. There is no change for a few hours. 

I think it's a error. With a short-term Internet outage, there should not be a complete shutdown. We need a mechanism that will automatically continue synchronization after resuming the Internet connection and force the nodes to continue working.

The problem is solved only by restarting the nodes and this is wrong.

**Comment by anhnd** [comment]
I can confirm this happened to me today too

**Comment by Mystic999** [comment]
We just happened to be in the same region of the same cloud provider. Vultr, Frankfurt, Germany

**Comment by iulianpascalau** [comment]
Agree. This is an ongoing issue. Will take into account the provided info into the next patch.

**Comment by iulianpascalau** [comment]
This is fixed as of today, 2020.05.13. Please open a new issue if the problem persists.
