### ISSUE TITLE
there is a permanent sync loop problem on Shard 3, 100% online node

### ISSUE THREAD

**Issue by longhuynh2811** [ElrondNetwork/elrond-go#613]
![image](https://user-images.githubusercontent.com/53088104/67910749-82e24f80-fbb6-11e9-908c-82d1cce14fe5.png)
[399dea8949e4.zip](https://github.com/ElrondNetwork/elrond-go/files/3791701/399dea8949e4.zip)

**Comment by longhuynh2811** [comment]
![image](https://user-images.githubusercontent.com/53088104/67910852-e2d8f600-fbb6-11e9-96c9-7a96e46ee141.png)
Shard 4 still works normally, here is the image data in parallel

**Comment by iulianpascalau** [comment]
There were sync/propose problems identified in the v1.0.36. That is why only one shard was affected. This is fixed by now.
