### ISSUE TITLE
Duplicate CPU and memory load measurements

### ISSUE THREAD

**Issue by Joinko** [ElrondNetwork/elrond-go#614]
![74664492_263982784518665_1608152570142916608_n](https://user-images.githubusercontent.com/57148469/67932036-71537480-fbc3-11e9-8ab8-5b3e0c506756.jpg)

**Comment by Joinko** [comment]
Also duplicity :
Current block height: 0, size: 0 B
Current block height: 25294, size: 7,94 kB

**Comment by iulianpascalau** [comment]
The issue was fixed by #482. The reason for the above situation was related to the fact that fmt.Println's in conjunction with termui do not mix well. Those artifacts should have been fixed by now.
