### ISSUE TITLE
2 Node on same machine, same connection (on/off), but different uptime

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#617]
Hi as i wrote in group, i just realized my shard 0 is be in different uptime with my other shard on the same machines, what it could be the case, for this i'll made experiment move my shard 0 to a single machine, but the other shard on other machine doesn't give me a significant score different, there were 3 machine, 1 machine contain 2 node, but just the 1st machine have diff. uptime up to 20K+

please advice, or give me a clue, thank you

![bon-bot](https://user-images.githubusercontent.com/44559893/67954843-303f7c80-fc24-11e9-8a7c-35ecd4ecf045.png)

![node_differs](https://user-images.githubusercontent.com/44559893/67955649-7ea14b00-fc25-11e9-99eb-d07910b6cd27.png)

**Comment by iulianpascalau** [comment]
Judging from the above pictures, it seems that the nodes came online only some minutes before taking this screen shot. Did the node X6 had internet connection all the time?

**Comment by scraido** [comment]
Yeah at that time, but after that i separated my node remotely, 1 node just for one machine / hdd, is there attack on 31/10, after that i'm not too seeking about uptime / downtime, as my vps also too slow,,

but before i run it on the recommended specs. 2vCPU + 4Gb/node,,

**Comment by iulianpascalau** [comment]
This is solved as of today 2020.05.14. Please open a new issue if the problem persists.
