### ISSUE TITLE
Overwrite config.toml file

### ISSUE THREAD

**Issue by Joinko** [ElrondNetwork/elrond-go#618]
You must override tags when you reinstall a new update. It is not automatically a replacement.
![Screenshot_20191031_161828_com anydesk anydeskandroid](https://user-images.githubusercontent.com/57148469/67963028-391d5780-fbfe-11e9-8052-f86fd32f3dfa.jpg)
![Screenshot_20191031_164150_com android chrome](https://user-images.githubusercontent.com/57148469/67963048-3fabcf00-fbfe-11e9-86e7-93d11348b60e.jpg)

**Comment by iulianpascalau** [comment]
Are you referring to NetworkID field?

**Comment by Joinko** [comment]
Yes, that's what I meant then.

**Comment by iulianpascalau** [comment]
Fixed, networkID was changed to chainID, preference moved to prefs.toml file.
