### ISSUE TITLE
Shards 2 and 3. The problem of sync. v1. 0. 37

### ISSUE THREAD

**Issue by Lenin1218** [ElrondNetwork/elrond-go#619]
Shard 2 got stuck in sync on block 12942. The value is regularly reduced by 1 block and returned again.

![888](https://user-images.githubusercontent.com/56969655/67970398-f7030e80-fc1b-11e9-8621-3e19f5fcc2c7.jpg)

Shard 3 got stuck in sync on block 17175. Both values are not incremented. 

![999](https://user-images.githubusercontent.com/56969655/67971111-3847ee00-fc1d-11e9-9aab-db9bea4c9495.jpg)

Restarting and reinstalling nodes does not solve the problem of both nodes. 

I have 6 nodes running. The rest of the shards have no such problems.

**Comment by iulianpascalau** [comment]
Yes, there were known sync/propose issues on v1.0.37. They were hopefully been corrected. This issue can be closed.
