### ISSUE TITLE
Testnet blockchain db reset not properly handled v1.0.38

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#625]
This might not be an issue for mainnet, but for now on testnet as the blockchain is reset periodically, and blocks start from 0 again, keeping the db accidentally should be made harmless.

Here is how an observer looks like without resetting the database:

The current synchronized block nonce just increases the previous count instead of resetting to 0 or to the proper nonce id.

Before blocks started producing:

![image](https://user-images.githubusercontent.com/16723548/68198598-07710b80-ffc5-11e9-8a8f-9fbf9f1b8e33.png)

After:

![image](https://user-images.githubusercontent.com/16723548/68198467-c547ca00-ffc4-11e9-99af-7e8544448e21.png)

Logs:
[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3808390/logs.zip)

**Comment by soringp** [comment]
As Flavius can tell us, if this happens on a Validator node, the accepted blocks count will incorrectly stay at zero:

![image](https://user-images.githubusercontent.com/16723548/68199365-929ed100-ffc6-11e9-99e2-9ea68db7e7c1.png)

The proposed blocks appear correctly on the explorer:

![image](https://user-images.githubusercontent.com/16723548/68199526-df82a780-ffc6-11e9-8a06-5760edfcfb3b.png)

**Comment by Flaviuss22** [comment]
Hey there,

forgot to delete the db folder as Validator: no signed or proposed blocks accepted, although I received the rewards.

[23d947d855b7-2019-05-11-09-45-01.log](https://github.com/ElrondNetwork/elrond-go/files/3808468/23d947d855b7-2019-05-11-09-45-01.log)
[23d947d855b7-2019-05-11-10-45-01.log](https://github.com/ElrondNetwork/elrond-go/files/3808469/23d947d855b7-2019-05-11-10-45-01.log)

**Comment by soringp** [comment]
If the proposed blocks are indeed not accepted, this might be a major issue!

Maybe the logs contain the proposed block ids, or they can be searched in the explorer after 07 UTC for the validator id.

**Comment by bogdan-rosianu** [comment]
Hello. Regarding the accidentally forgot DBs, you can use the _storage-cleanup_ flag when starting the node.

**Comment by soringp** [comment]
I know the flag, but in my view the old DB should not cause problems. Ideally  the DB should be cleared on the go after the node is connected with up to date peers.

**Comment by iulianpascalau** [comment]
Good for pointing this out. We might think of a mechanism for invalidating blocks across networks.

**Comment by iulianpascalau** [comment]
Fixed, we have 2 mechanisms: 1. We have a chainID field on each header and 2. We are invalidating/validating blocks based on the genesis time.
