### ISSUE TITLE
Node hangs on "Starting web server..."

### ISSUE THREAD

**Issue by ahakla** [ElrondNetwork/elrond-go#628]
VPS with 8 nodes, each with incremental REST-API ports.
After more than 24 hours, 7 out of 8 nodes are running just fine, 1 of 8 nodes never started off right, see the attached screenshot.

The logs and stats don't give any clues (empty).
I killed the process and simply restarted the node with the same REST-API port, it started synching right away and was fully synched quite quickly.

I have no idea why the web server didn't start right.
![webserverfreeze](https://user-images.githubusercontent.com/35300587/68257764-a4b75880-0034-11ea-8254-0d9f734b4624.png)

**Comment by soringp** [comment]
It happened to me once as well, on one of the previous versions. Logs empty.
The application responds to ctrl+c but seems frozen otherwise, when starting the web server.

**Comment by iulianpascalau** [comment]
Yes, this was a really hard to catch bug. It has been fixed by #704. A blocking loop was present in the main function that caused application hangs.
