### ISSUE TITLE
Transaction error from Shard 2 wallet to wallet misson BoN 2 

### ISSUE THREAD

**Issue by longhuynh2811** [ElrondNetwork/elrond-go#629]
![image](https://user-images.githubusercontent.com/53088104/68260067-56bf4680-006e-11ea-9531-5185047b4108.png)
after send, I check hash txs but it emty
![image](https://user-images.githubusercontent.com/53088104/68260080-63439f00-006e-11ea-991b-d25049d3bed1.png)
and login again ERD back in wallet and dont history txs!
![image](https://user-images.githubusercontent.com/53088104/68260091-6ccd0700-006e-11ea-94ed-b79398b9710b.png)
![image](https://user-images.githubusercontent.com/53088104/68260106-76ef0580-006e-11ea-9490-b4157eba3299.png)

**Comment by ahakla** [comment]
It looks like it was undeliverable and got refunded to your originating wallet?

**Comment by koen84** [comment]
Seems eerie familiar from what i saw in #603 
I had this same issue again, now connected to TX.

**Comment by bogdan-rosianu** [comment]
Hello, it may a problem with the nonce which could be cached by your browser or something similar.
We are working on a mechanism that will provide a better feedback about a transaction's status which will tell what is wrong in it.

**Comment by iulianpascalau** [comment]
Will move the discussion in #603. Will close this one.
