### ISSUE TITLE
TX to faulty address (zeroes versus others)

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#630]
I was trying some stuff out with sending TX'es.

Seems sending to 64 zeroes as recipient address does yield a TXID, that cannot be found, yet balance decreases.  (Explorer things there are addresses to begin with.)
84accef6e8ed9943cf4e7a56083d16b16afc9e41152827a1dd570722e9b9c25a
4d0db6c1fb4963251db1e3cd2d20a9496e9bf030f167027e05c79c6485849ca1
1dec807b12113ac07f993c13091f8432603ab819d3385d5e8f4f05449de2b803

Seems sending to 64 ones as recipient address does yield a TXID, that can be found, balance shifts "correctly" from sender to receiver.
7beb2cbd2f6468cae48e7407590d576aa1adcd2abad8d8362f6906f54781a461

Seems sending to 4 times the increment 0 to F as recipient address does yield a TXID, that can be found, balance shifts "correctly" from sender to receiver.  Yet this TX recorded twice, once with and once without data field.
b4b4ad0fdb19d9b4bb312b81a05da8ae9e277e3fe3a917f136e7a25d56a3d005
2ece8164bb5502e9e7992159c36333c200e3d8de99366a3789d45ff5792fa2db

**Comment by bogdan-rosianu** [comment]
Hello. The address which contains only zeros is considered a smart contract address and if there is no valid data field (or even empty) it will not be processed.
We are working on a mechanism which will provide better feedback about the status of a transaction instead of displaying a success message anyway.

**Comment by koen84** [comment]
Basically "known issue" then ?  Just had the distinct impression funds left the wallet though ?

**Comment by sasurobert** [comment]
Hi! 

If you send to and address of 64 zeroes, that transaction is considered to be for deployment of smart contract. As the txData you send is not a valid contract, all the gas you put inside will be consumed, but you get back the value of the transaction.

This is not a bug. This is how the system was designed.

**Comment by iulianpascalau** [comment]
@sasurobert correctly point out the behavior of the Elrond blockchain. This can be closed.
