### ISSUE TITLE
Published transaction, not appearing in TX list, balance untouched, gets processed 30-60 min later (1.0.38)

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#647]
I was trying to get to 100 fee for mission 4, so data was 99900 characters.
I've tried sending it multiple times, all characters UTF-8, even forced ASCII, no luck.
I had my full 3000 erd balance intact.

30 min later, after multiple attempts, replacing characters, I gave up on that text and I've used only numbers as data, this time the transaction was successful:
https://testnet.elrond.com/#/tx/6251d8d1f30cf7d4f653a54cd08ae45b2643ebf5bffdde9b05996c3853510930

But, after a while I've noticed one of the initial transactions got processed.

Here's the ghost transaction:
https://testnet.elrond.com/#/tx/b0d45a9965de1bdadb128eee8f5e83cb2c8bec0d709bc862c98b3b7a999bc8d3

This might be an ElasticSearch issued, caused by indexing the data payload too slow, or some elastic node got out of sync. 
Or the signed transaction stayed in a pool somewhere, the latest timestamp is 20 min after the "newer" one.

At some point I've restarted the browser, and all prev pages were reloaded, could a transaction have been cached and sent on this restart? The wallet was still unlocked.

**Comment by iulianpascalau** [comment]
There were issues regarding elastic search handling large tx data.

**Comment by elronscam8** [comment]
That's enough!! Cheating bastards.
The price keeps falling. People don't trust you. ERD doesn't buy. What do you boys do for a living?

Binance Delist/ Don't Buy ERD/ELROND / Erd scam coin / Erd big dump
ERD BIG DUMP SELL NOW ...ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
 
 Beniamin Mincu 
ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
  ERD BIG DUMP SELL NOW ...
 
 
 Crooked sons of bitches. Give us our money back.
 BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
 
  BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
  We want our money back, Romanian sons of bitches.
  
  Elrond was HACKED!
  Elrond announced that he had been hacked. Please don't buy ERD

**Comment by iulianpascalau** [comment]
Fixed, as of today, 2020.05.14. Please reopen an issue if the problem persists.
