### ISSUE TITLE
New TX sent 2 TX'es from yesterday.

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#648]
For mission 4 i had to send a transaction, which successfully went through.  Somehow it also had 2 unsuccessful TX from yesterday go through as well, 1 with higher and 1 with lower nonce, approximately 24h later.  This is very problematic, in real world, if the TX doesn't go through, i'll make another solution, so it shouldn't be "dragged in" later.

Today : e25965e38c25ba826ad7f0f3c2af886c124f34cd1d8a29f825e6a7ae99cfa5bf
(Yes, i wasted 900 tERD.)

Yesterday :
5824d748b3a71b1a2d7d6f40f7b8f7255ac918c1a480e2080bdcd7595076b485
c278dc8b44932b0b2ee42ccf7942f62dd4d5931ec44b46a93521759f6d0eff9e

**Comment by iulianpascalau** [comment]
We have implemented a transaction filter that can output directly if the transaction is well formatted or not. Related to #609.
