### ISSUE TITLE
TX hash becomes valid Address

### ISSUE THREAD

**Issue by chinezupwnz** [ElrondNetwork/elrond-go#652]
Hello,

TX Hash becomes a valid Address that can have balance on it.
I see it as a bug and its very confusing. 
The use case:

TX:
https://testnet.elrond.com/#/tx/9fb43201786f128e5ffd6b2731540d854fd96ba22ebc911e98f5f1506720c0f5
Wallet:
https://testnet.elrond.com/#/address/9fb43201786f128e5ffd6b2731540d854fd96ba22ebc911e98f5f1506720c0f5

**Comment by bogdan-rosianu** [comment]
Hello. This is normal for now because a tx hash can be also considered a valid address because it respects it's format. We will want to change the address format for accounts soon so this issue won't be relevant anymore.

**Comment by drdelphi** [comment]
you could also change the tx hash format by adding 2 bytes (src_shard and dst_shard) somewhere at the beginning or end ... just an idea

**Comment by iulianpascalau** [comment]
This will remain opened as we need to figure out a (better) solution to this.

**Comment by iulianpascalau** [comment]
Fixed, implemented bech32 for address format. Reference PR #1331
