### ISSUE TITLE
v1.0.40 misconfigured prefs.toml wierd error 

### ISSUE THREAD

**Issue by EdwardTarantulo** [ElrondNetwork/elrond-go#674]
Accidentally misconfigured **prefs.toml** and left the #3 like with out a double qoute at the end `NodeDisplayName = "Tarantulo_#2`

I could not run the node and got these errors.

On **Windows** node.exe quite immediately after starting.

On **Ubuntu** I get this error.
![image](https://user-images.githubusercontent.com/57504756/68893939-e62fbe00-072e-11ea-82c0-1f518a6d113a.png)

**Comment by bogdan-rosianu** [comment]
Hello. This is normal because the node's display name is a string and it must be placed between double quotes. This is not a bug, just a bad config.
