### ISSUE TITLE
v1.0.41 Fails to Compile

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#727]
What new dependencies need to be installed?

[buildlog.txt](https://github.com/ElrondNetwork/elrond-go/files/3907417/buildlog.txt)

**Comment by iulianpascalau** [comment]
Please provide the OS & golang versions

**Comment by joesixpack** [comment]
Alpine 3.10

Linux 7aa74d439379 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 Linux

go version go1.13.4 linux/amd64

**Comment by elronscam8** [comment]
That's enough!! Cheating bastards.
The price keeps falling. People don't trust you. ERD doesn't buy. What do you boys do for a living?

Binance Delist/ Don't Buy ERD/ELROND / Erd scam coin / Erd big dump
ERD BIG DUMP SELL NOW ...ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
 
 Beniamin Mincu 
ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
  ERD BIG DUMP SELL NOW ...
 
 
 Crooked sons of bitches. Give us our money back.
 BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
 
  BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
  We want our money back, Romanian sons of bitches.
  
  Elrond was HACKED!
  Elrond announced that he had been hacked. Please don't buy ERD

**Comment by iulianpascalau** [comment]
Should have been fixed by now, 2020.05.14. Please reopen an issue if the problem persists.
