### ISSUE TITLE
v1.0.41-0 no logger output seen in TUI console and no logger files on disk

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#728]
I notice when running  node v1.0.41-0-g4cca8a9e, that there is no log output in the TUI window.  I also note that there is no logs directory and no log output on disk.  I tried started the node process with --logLevel "*:DEBUG", and now see DEBUG logging in the TUI window, but still nothing is being logged to disk.

**Comment by frankf1957** [comment]
Starting the node with --use-log-view  does not provide any output in the terminal window, and no files are created in the logs directory.

**Comment by iulianpascalau** [comment]
generating log files have been removed as of #680 
The reason behind this is that the application should not handle the log files, especially when ran as a daemon. You can use linux journalizing feature for this.

**Comment by frankf1957** [comment]
This issue should no longer be open. The generation of log files to disk has been removed in favour of using the system journal since it is expected that validators will run their node process using systemd and allow systemd to manage log output.
