### ISSUE TITLE
Transfer functionality on wallet.elrond.com is broken

### ISSUE THREAD

**Issue by SebastianJ** [ElrondNetwork/elrond-go#763]
**Describe the bug**
It's not possible to perform transfers using wallet.elrond.com anymore - you'll only get an error message stating "Failed - The transaction has failed. Please try again." (see screenshots below)

![Create transaction](https://i.ibb.co/mCYSV2y/elrond-create-tx.png)

![Transaction fails](https://i.ibb.co/gMgf28C/elrond-tx-fail.png)

After doing these steps you'll end up with the following in the Chrome dev request log:

```
{"error":"validation error: json: cannot unmarshal string into Go struct field Transaction.gasLimit of type uint64"}
```

or

```
{"error":"{\"error\":\"transaction generation failed: insufficient gas limit in tx\"}"}
```

So seems that either the transaction marshalling has changed and/or the economics settings have changed as well.

**To Reproduce**
1. Login to wallet.elrond.com using a wallet of your choice
2. Try to send a transaction
3. Transaction will fail

**Expected behavior**
Transactions should work - like they did previously.

**Environment (please complete the following information):**
 - OS: MacOS Version 10.15.1 (19B88)
- Chrome: Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by SebastianJ** [comment]
The error `{"error":"validation error: json: cannot unmarshal string into Go struct field Transaction.gasLimit of type uint64"}` happens when you try to increase the gas limit

**Comment by iulianpascalau** [comment]
Looks like web wallet issue or bad config.

**Comment by iulianpascalau** [comment]
Wallet issue + bug on the front end. Hopefully this was fixed by now. Thanks! :+1:
