### ISSUE TITLE
Pool cleaner issue

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#765]
I attach a small GO app I used to generate a few thousand transactions.
All of them have 0 value and the fee is 10 ERD.
I had enough ERD in my balance for around 2000 txs.
The transactions I have generated, have been stored in the pool and executed until my balance dropped to 0.
Being a validator wallet, it receives rewards every several seconds.
The tx generation happened a couple of hours ago, but the unexecuted transactions are still in the pool, and every time the rewards add up to 10 ERD, another tx is executed, which is not quite normal as they shoud've been dropped as soon as my wallet went out of funds.

[main.txt](https://github.com/ElrondNetwork/elrond-go/files/3935366/main.txt)
![Screenshot from 2019-12-07 19-33-40](https://user-images.githubusercontent.com/32204735/70378411-c43deb80-1928-11ea-9942-d65a23f91735.png)

**Comment by drdelphi** [comment]
The transactions pool cleaner should check every round if they are in the same shard as the sender, and if they do, check if the tx_value + tx_fee > balance and if so, remove the tx from the pool.

**Comment by iulianpascalau** [comment]
Good catch! Will need to fix that soon.

**Comment by iulianpascalau** [comment]
We have a new tx pool cache that contains a smart eviction system. Please open a new issue if the problem persists.
