### ISSUE TITLE
Validator node OOM on shard-0 (v1.0.56)

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go#767]
Is there a memory leak in v1.0.56?  I have been trying to restart my validator node on shard-0, but it's having trouble and running out of memory.  My VPS has 4G, so I created a 12G swap file to see if that would make it go.  Here is what I see in top.

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                  
12472 elrond    20   0 15.723g 3.559g   8616 S  62.6 92.4   9:02.97 node     

It just ran out of memory, crashed and restarted. Here is the last line from the stats file

timestamp: 1575788533, uptime: 10m14s, num go: 576, alloc: 9.33 GB, heap alloc: 9.33 GB, heap idle: 2.57 GB, heap inuse: 9.36 GB, heap sys: 11.93 GB, heap released: 69.26 MB, heap num objs: 101314923, sys mem: 12.52 GB, total mem: 25.40 GB, num GC: 35, FDs: 151, num opened files: 150, num conns: 59

**Comment by frankf1957** [comment]
I increased the size of my swapfile to 24G and restarted. After running 30 minutes, I am connected to 240 peers, not syncing any blocks yet, and the process is using 23.5G according to top.

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                  
12901 elrond    20   0 23.591g 3.539g   8316 S  38.7 91.9  19:08.28 node

**Comment by frankf1957** [comment]
I shut it down and renamed the db folder. I started it, and now it is behaving properly again. Connecting to peers much more quickly and synchronizing blocks. Connected to 110 peers and using 1.6G mem after about 5 minutes.

**Comment by iulianpascalau** [comment]
Thanks, there was an issue withing a bootstrapping-related component. This was fixed in #861
