### ISSUE TITLE
Meta stuck

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#768]
One TX from my #1 validator to the staking SC address (000000000000000000010000000000000000000000000000000000000000ffff) seems to have rendered the metachain stuck.
![Screenshot from 2019-12-08 19-33-10](https://user-images.githubusercontent.com/32204735/70393363-abe5d380-19f1-11ea-96e8-535ef18d6b57.png)
![Screenshot from 2019-12-08 19-33-22](https://user-images.githubusercontent.com/32204735/70393365-adaf9700-19f1-11ea-9867-4c9c0df70eb1.png)

**Comment by iulianpascalau** [comment]
Fixed as of #749
