### ISSUE TITLE
Implement Kadcast (> Kademlia)

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#770]
https://eprint.iacr.org/2019/876.pdf

**Comment by iulianpascalau** [comment]
Nice doc, started to read it.

**Comment by joesixpack** [comment]
Here's some other ideas...  

https://medium.com/perlin-network/noise-v1-1-2-fearless-decentralized-p2p-networking-in-go-bf3afdd77230

https://decrypt.co/18083/microsoft-researcher-solved-blockchain-scalability-problem

**Comment by joesixpack** [comment]
@iulianpascalau

**Comment by joesixpack** [comment]
[ava-platform.pdf](https://github.com/ElrondNetwork/elrond-go/files/4196240/ava-platform.pdf)

**Comment by iulianpascalau** [comment]
We have implemented a modified version of kademlia algorithm for network sharding. Will publish a paper soon about this topic.
