### ISSUE TITLE
Set the economics.toml file

### ISSUE THREAD

**Issue by Joinko** [ElrondNetwork/elrond-go#793]
Hello,

After rebuilding economics.toml, Reward estimation increased several times.
Normal:
![normal](https://user-images.githubusercontent.com/57148469/70694453-f13f2500-1cbf-11ea-9a19-5b42249a1ea1.png)

Modified n.1:
![20](https://user-images.githubusercontent.com/57148469/70694493-087e1280-1cc0-11ea-8a21-15a8a3189d94.png)

Modified n.2:
![20000](https://user-images.githubusercontent.com/57148469/70694501-0f0c8a00-1cc0-11ea-9d3e-e574c4666f8f.png)

Could there be a problem if the file is misused?

**Comment by miiu96** [comment]
It is normal this behavior because rewards estimation is calculated with information from your economics.toml file, and if you change some value you will have a wrong estimation. But if you take a look at total rewards you have 0 because you will not propose valid blocks.
