### ISSUE TITLE
Wallet unavailable attack

### ISSUE THREAD

**Issue by Joinko** [ElrondNetwork/elrond-go#797]
After logging into the elrond wallet via accessing using pem. Shows:
![2019-12-12 (6)](https://user-images.githubusercontent.com/57148469/70706114-99131d80-1cd5-11ea-8a32-62a6eb90400d.png)

**Comment by Joinko** [comment]
I think it's caused by the erd transaction from my account to my account.

**Comment by Joinko** [comment]
Repeated trials again put the wallet in a wallet unavailable state.

**Comment by Joinko** [comment]
I sent 5 times from the address: 8fdb2b27838df56c0a9b187fae61df5e473594e0bd8cd7c9ef2bd244b992662e to: 8fdb2b27838df56c0a9b187fae61df5e473594e0bd8cd7c9ef2bd244b992662e. Transaction was not successful. Then she was a wallet : Wallet anavailable
Data:
Joinka erd attack

**Comment by iulianpascalau** [comment]
There was a bug on the wallet front end application. It is now fixed. Thanks for pointing this out.
