### ISSUE TITLE
Shard 0 Uses a high amount of other Ram

### ISSUE THREAD

**Issue by longhuynh2811** [ElrondNetwork/elrond-go#810]
On my Shard 0 the capacity is increasing steadily up to 3Gb and possibly more.
![Screenshot from 2019-12-13 16-49-23](https://user-images.githubusercontent.com/53088104/70791084-f3d97180-1dc8-11ea-8319-ff3e49b46010.png)

**Comment by longhuynh2811** [comment]
Up to 3.5 Gb


![Screenshot from 2019-12-13 17-07-41](https://user-images.githubusercontent.com/53088104/70792108-1b313e00-1dcb-11ea-9cb2-320344992efd.png)

**Comment by longhuynh2811** [comment]
Up to 4.15 Gb 

![Screenshot from 2019-12-13 18-08-04](https://user-images.githubusercontent.com/53088104/70795931-9696ed80-1dd3-11ea-96ed-9e363e53c9bc.png)

**Comment by longhuynh2811** [comment]
Up to more 5Gb
![Screenshot from 2019-12-13 18-48-35](https://user-images.githubusercontent.com/53088104/70798356-4d499c80-1dd9-11ea-8d51-8826a9b39d2c.png)

**Comment by SebastianJ** [comment]
Guessing this is because of the mass tx spam attack I did (plenty of people reported high memory usage because of it): https://github.com/ElrondNetwork/elrond-go/issues/799

**Comment by iulianpascalau** [comment]
Indeed, we have observed the same behavior on our servers.

**Comment by iulianpascalau** [comment]
Will move the discussion on #799
