### ISSUE TITLE
VPS provider overview: Draft Proposal

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#813]
The Elrond Battle of Nodes is an amazing experience to learn new things from experts in the field. It requires having a Virtual Private Server. Most people are new to this and are paying extremely to have their node(s) set up and running where they can get the same service/specifications with almost 50% less. 

Based on this, I will like to write a comprehensive guide on VPS providers overviews by looking at the following metrics that will be a guide for Elrond validators

- OS choices available
- The RAM attached to each category of disk sizes (SSD)
- Payment method (daily, weekly, monthly, quarterly, yearly or pay as you consumed)
- Type of support provided (email, live chat, telephone etc)
- Min - Max Bandwidth
- Different categories of CPU available (from lowest to max)
- Upgradeable
- Uptime 
- Cost
- Any provision for a money-back guarantee
- Reputation (Where available)

![image](https://user-images.githubusercontent.com/7301249/70800204-ef529000-1dab-11ea-831f-b638635f76a7.png)

![image](https://user-images.githubusercontent.com/7301249/70800282-1e690180-1dac-11ea-8550-4a1d9def733c.png)

**Comment by iulianpascalau** [comment]
Closing. We had a contest "Rate my node" during the first BoN period.
