### ISSUE TITLE
Sending a transaction and changing the fee

### ISSUE THREAD

**Issue by klanek007** [ElrondNetwork/elrond-go#820]
It is not possible to send a transaction, each attempt ends with an error:

![tx_1_error](https://user-images.githubusercontent.com/32298908/70862987-7d14b380-1f43-11ea-9173-665cdbed767f.JPG)
![tx_1_error_2](https://user-images.githubusercontent.com/32298908/70862988-7d14b380-1f43-11ea-9ce7-de3cee801386.JPG)
![tx_2_error_1](https://user-images.githubusercontent.com/32298908/70862989-7d14b380-1f43-11ea-9729-72b7650f760d.JPG)
![tx_2_error_2](https://user-images.githubusercontent.com/32298908/70862990-7dad4a00-1f43-11ea-908b-e856161df5c2.JPG)
![tx_2_error_3](https://user-images.githubusercontent.com/32298908/70862991-7dad4a00-1f43-11ea-9ec2-fe004c453b87.JPG)
![tx_fee_bug_limit](https://user-images.githubusercontent.com/32298908/70862992-7dad4a00-1f43-11ea-8819-25dc8ab79528.JPG)

in addition, it is not possible to change the fee for shipping below 100 ERD

**Comment by iulianpascalau** [comment]
There was a known issue regarding fee computation. This is fixed by now. The problem regarding sending data that contains special characters `<` is on the way to be fixed soon.
