### ISSUE TITLE
REQUEST topics spam

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#821]
Spamming the nodes on a specific shard with invalid messages on all REQUEST topics, freezes the shard.

**Comment by drdelphi** [comment]
[request-topics-spammer.zip](https://github.com/ElrondNetwork/elrond-go/files/3965045/request-topics-spammer.zip)

These is a 'brutally' modified seednode that does the job.

**Comment by iulianpascalau** [comment]
:+1:  Keep the testing tool to retest when we will deploy the node's anti-flooding capabilities.

**Comment by iulianpascalau** [comment]
Fixed, the antiflood component filters out the spamming stuff. Reference PR #787
