### ISSUE TITLE
Last block in shard 1 - 7 hour ago.

### ISSUE THREAD

**Issue by Joinko** [ElrondNetwork/elrond-go#826]
Last block in shard 1 - - 7 hour ago.
![79259339_552057118977193_6325035497429139456_n](https://user-images.githubusercontent.com/57148469/70917030-ea484780-201c-11ea-93d3-793a6d74fc5b.jpg)

**Comment by iulianpascalau** [comment]
This happened due to the attacks on shards. Will move the discussion on #799 and #821
