### ISSUE TITLE
Consensus accepted failed.

### ISSUE THREAD

**Issue by Joinko** [ElrondNetwork/elrond-go#831]
Consensus accepted failed and block accepted failed.
![Block](https://user-images.githubusercontent.com/57148469/70995430-d5c58700-20d0-11ea-977c-55232dfd11c0.png)

**Comment by iulianpascalau** [comment]
If you are referring the differences between the `consensus accepted / signed blocks' and `blocks accepted / blocks proposed` this is normal operation as there where rounds on which the consensus group was unable to gather minimum required number of signatures shares.
