### ISSUE TITLE
Concensus deliberate timestamp poisoning

### ISSUE THREAD

**Issue by MikeHibbert** [ElrondNetwork/elrond-go#834]
I've edited consensus/message.go to add 1 hour to the Message timestamp when creating a new consensus message and it it appears that they are still being accepted!

Code to reproduce:
```
// NewConsensusMessage creates a new Message object
func NewConsensusMessage(
	blHeaderHash []byte,
	subRoundData []byte,
	pubKey []byte,
	sig []byte,
	msg int,
	tms uint64,
	roundIndex int64,
) *Message {

	tms += 3600
	return &Message{
		BlockHeaderHash: blHeaderHash,
		SubRoundData:    subRoundData,
		PubKey:          pubKey,
		Signature:       sig,
		MsgType:         msg,
		TimeStamp:       tms,
		RoundIndex:      roundIndex,
	}
}
```

**Comment by MikeHibbert** [comment]
![Screenshot from 2019-12-17 15-19-07](https://user-images.githubusercontent.com/1153455/71008588-c3534980-20e0-11ea-934c-48c35a35d722.png)

**Comment by iulianpascalau** [comment]
Yes, the timestamp field used in consensusMessage appears unused. That is why the consensus messages are being propagated. Will be removed. Thanks.
