### ISSUE TITLE
Autoupdater resets variables.cfg file after a stress test

### ISSUE THREAD

**Issue by kmatari** [ElrondNetwork/elrond-go#837]
After the attacks, my nodes crashed and I got an error on the console. I tried to cleanup and reset my nodes to make them running. My nodes are on the root and my previous variables.cfg was root. I am adding a running node's ss here.
![running_error](https://user-images.githubusercontent.com/55320765/71029920-76439780-2121-11ea-97c3-0765f2c08809.PNG)

after I try to fix the problem, I used stop command and couldnt make it worked. this might be because variables.cfg is changed. below, there is the stop error and the variables.cfg file's ss

![error2](https://user-images.githubusercontent.com/55320765/71030043-b30f8e80-2121-11ea-9f2b-993502a7d0a6.PNG)

something changed my variables.cfg. It wasn't ubuntu, it was root and I didnt touch this file.  I don't know the source but I am suspected of autoupdate. It seems autoupdater tried to update or start my nodes again and after, it resetted my variables.cfg

![stop_error](https://user-images.githubusercontent.com/55320765/71030052-b6a31580-2121-11ea-8631-c5db6b6004bc.PNG)

**Comment by iulianpascalau** [comment]
Did you `git pull` the elrond-go-scripts-v2 repo? Otherwise the scripts do not update themselves. Also there seems to be some issues regarding saving files on disk.

**Comment by kmatari** [comment]
I didn't do anything and yes, we have a disk issue that you should take into account. I didn't write any code and probably the autoupdater tried to fix the issue. It resetted the variables.cfg file. I haven't touched anything.

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.

**Comment by kmatari** [comment]
Hello,

Through this, you accept there was an issue or a glitch? If so, this issue
is created between the bug bounty timeframe that I must earn a compensation
for it. Please inform me about these.

Iulian Pascalau <notifications@github.com>, 15 May 2020 Cum, 17:22
tarihinde şunu yazdı:
