### ISSUE TITLE
Proposal : non-interactive install option

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#847]
I'd like to provide a non-interactive option in the auto-updater script.  It would check if valid answers are provided in the variables.cfg and if so use them, otherwise still prompt for the input.  Since the idea would be to run without user input, i'm proposing this option would as first check if it finds all information (variables) it needs, otherwise exit / prompt immediately, without going through any of the install procedure.

This should be valuable for people who need to move server and for people who run larger amount of nodes.

Time : 
* 1 week for local install option
* 2 extra weeks for remote option (as it requires deep nesting the information).

**Comment by iulianpascalau** [comment]
Nice, @valentin-lup , what do you think?
