### ISSUE TITLE
Proposal : yum support for auto-updater

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#848]
Expand the auto-updater script with support for yum based systems.  Now it's limited to Debian / Ubuntu (and derivatives) in a hardcoded fashion.  This would expand to RedHat / CentOS (and derrivates).

Needs : 
* detecting distribution, possibly also version
* in every command & function check for packagemanager instructions and provide alternate instructions.

Time :  1 week.

**Comment by iulianpascalau** [comment]
@valentin-lup

**Comment by elronscam8** [comment]
We've been waiting months for you motherfuckers to do something.
