### ISSUE TITLE
Proposal : add optional auto system updates to installer script

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#849]
Expand the auto-updater script with system updates, through separate cronjob.  While i still reckognise / advocate the importance of node operator control, i also reckognise people with less experience on linux / servers / blockchain will (eventually) run nodes.  The node "set-and-forget" approach might have people forgetting to upgrade their OS.  Upon presenting this choice their will be a warning displayed that successful updates might make some services temporarily unavailable (e.g. SSH server when it gets updated) and automatically reboot.

Time : 3 days.

**Comment by koen84** [comment]
To be done after #848 if also approved.

**Comment by iulianpascalau** [comment]
@valentin-lup
