### ISSUE TITLE
Proposal : monitoring on raspberry pi + pifaceCAD

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#850]
Starting from the premise that some people might want to have control over their monitoring and off course a certain coolness factor.  Everything will be read from a config file.

Have a script running on the rpi that queries your (or a public) observer for online / offline status.  In case one or more nodes are showing as offline, switch on the display and show problem information.  Use the buttons where needed for seeing more info.

Allow the user to "query on request" the status by push of a button.

Requires, preferably an observer, rest-api to be available to the home IP address.

I'd try to make everything as modular and setup through variables as possible, so it's easy to modify for other requirements (different display, sound alarm, etc).

Time : 3 weeks.

**Comment by iulianpascalau** [comment]
We are going to change the status reporting system. We will provide an option that will try to open an http connection and start pushing status requests. Will close this for now.
