### ISSUE TITLE
Proposal : extended monitoring on rpi + display

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#851]
Building on #850, add more information than online / offline.  Say disk and RAM usage.  On reaching thresholds, it'll switch on the display and provide error information.  By button push user can query manually.

The main reason why this is a separate proposal, is because rather than polling rest-API, this will need SSH key access to the nodes in question.  The idea is to avoid installing monitoring suites, to not add load to the server and might be over-complicated for many users.

It will also be checked to run in parallel to the auto-updater remote options, so your raspberry pi can run the install-remote, install-upgrade, etc options (with the same set of keys).

Time : 3 weeks.

**Comment by iulianpascalau** [comment]
We are going to change the status reporting system. We will provide an option that will try to open an http connection and start pushing status requests. Will close this for now.
