### ISSUE TITLE
Proposal: Wallet CLI

### ISSUE THREAD

**Issue by SebastianJ** [ElrondNetwork/elrond-go#853]
Elrond clearly needs a CLI that allows users to send transactions.

I've already started on an initial implementation (based on the previous tx sending code I wrote for my transaction spammer).

I intend to implement the following features:

- Keystore functionality (import/export wallet keys to a given keystore location)
- Transaction sending (regular transactions from a given wallet to another specified wallet)
- CLI argument and command parsing using [Cobra](https://github.com/spf13/cobra)
- and a few more features (will update this ticket when I come up with more features to add)

An initial alpha version of the wallet will be released before the end of this week.

**Comment by SebastianJ** [comment]
I've released an initial CLI version here: [elrond-cli](https://github.com/SebastianJ/elrond-cli)

It currently supports sending transactions using pem files. I'm planning to implement keystore functionality next.

How to use it/install it:

```
mkdir -p elrond-cli && cd elrond-cli
bash <(curl -s -S -L https://raw.githubusercontent.com/SebastianJ/elrond-cli/master/scripts/erd.sh)
./erd --help
```

The installer scripts downloads a pre-compiled static binary from Amazon S3 (similar to what I'm suggesting in https://github.com/ElrondNetwork/elrond-go/issues/854). So people can just download the static binary using the installer without having to install golang, compile etc. etc.

To send transactions:
Using an initialBalancesSk.pem file in the same directory:

`./erd transfer --to ADDRESS --amount AMOUNT`

Using a custom specified .pem file:

`./erd transfer --wallet ~/elrond-nodes/node-0/config/initialBalancesSk.pem --to ADDRESS --amount AMOUNT`

**Comment by iulianpascalau** [comment]
Nice proposal, will follow up and discuss about it.

**Comment by iulianpascalau** [comment]
Will close this as we have several projects that do just this. Just to mention erd-py and erd-js projects developed by our team.
