### ISSUE TITLE
Negative values on the Explorer

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#860]
This could be just a minor Explorer/Elastic search issue, but it's not pleasant to the eye, here is what I see on my pc, the Age has negative values:

https://explorer.elrond.com/address/cf51fc9eab73998545e2390a563c7a11603e37d0b581ee18bd1c5b1dc1343563

![image](https://user-images.githubusercontent.com/16723548/71168904-62eb1600-2260-11ea-994f-cb0f11f38947.png)

**Comment by soringp** [comment]
This could be the same issue described in this issue:
https://github.com/ElrondNetwork/elrond-go/issues/540

**Comment by soringp** [comment]
In my defence, as this issue might sound trivial, the Explorer is no longer branded as a Testnet version, the URL "https://explorer.elrond.com" shows this is a production environment, so I think this should be fixed sooner or later. Thanks :)

**Comment by iulianpascalau** [comment]
Indeed this needs fixing.

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
