### ISSUE TITLE
Git Bash for Windows terminal error

### ISSUE THREAD

**Issue by Mystic999** [ElrondNetwork/elrond-go#877]
This issue has already been posted in another branch, apparently in the wrong place: 
https://github.com/ElrondNetwork/elrond-go-scripts-v2/issues/34

Git Bash is a standard terminal utility for Windows. If you install Git on Windows, this utility is installed by default. The terminal itself works fine both inside Windows and with a remote VPS. The problem only occurs when I run the command:

./elrond-utils/termui -address localhost:8080

The node window is not displayed correctly. Although this does not cause any problems for the operation of the node, but I want to remind you that we are on the site Github and Git Bash-is a product of Git. What could be the problem?

The settings have a standard character encoding and several times I did a default reset. Before the scripts of V2, there was no such image.
I love this terminal and use it all the time. I don't want to use Putty.

![70212042-9fd6e900-1747-11ea-9f6e-25a6535d9140](https://user-images.githubusercontent.com/52602853/71266660-ed637080-2359-11ea-8248-bbf69f491f45.gif)

https://www.youtube.com/watch?v=EiYiIwDJtgc

**Comment by iulianpascalau** [comment]
Thanks for pointing this out. Will take a look at it.

**Comment by iulianpascalau** [comment]
We stopped supporting windows for now. Closing for now.
