### ISSUE TITLE
Shard 1 is dead. All transactions are rejected

### ISSUE THREAD

**Issue by Mystic999** [ElrondNetwork/elrond-go#878]
Sent a few transactions to a vote. On shard 1 all transactions are returned back to the wallet balance.
a20382a67cc9ef4b97b8128aae05179bf76eb0f15a24fea1d3f1bebeef9be36f
c50c2a00d9c48675b95d3b3a584351b4db065e39a5c749d66d8d31220d1b7306

![001](https://user-images.githubusercontent.com/52602853/71275636-864bb900-2365-11ea-9c05-d992adeca51a.jpg)

![002](https://user-images.githubusercontent.com/52602853/71276435-c27f1980-2365-11ea-8ed6-6c844181f10b.jpg)

Perhaps this is the problem of only half of all nodes on shard 1. Only those who fell into the fork. A fork can happen if some group does not have enough HDD capacity.

**Comment by Mystic999** [comment]
Perhaps this is the problem of only half of all who hit the fork

**Comment by iulianpascalau** [comment]
Yes, we know about the issue. Will provide a fix for this issue.

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
