### ISSUE TITLE
Broadcasting 100 times the consensus messages

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#879]
Broadcasting 100 times each consensus message, blocks the shard.
(v1.0.64)
I attach the 'consensus' folder to make a diff.
[altered-consensus.zip](https://github.com/ElrondNetwork/elrond-go/files/3989578/altered-consensus.zip)

**Comment by iulianpascalau** [comment]
Will find the problem and provide a fix for this.

**Comment by iulianpascalau** [comment]
Great attack. This is prevented by the antiflood system. Reference PR #1176
