### ISSUE TITLE
Observation: Sending transaction

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#881]
When sending a transaction, there is always an error dialog box with sending transactions failed as shown in this screenshot. I have the following observations:

1. If the amount sent is not deducted from the balance, this error will popup. My observation shows that most time the amount sent is not deducted from the balance immediately. 

2.  Continuous sending will not yield any desired result until the page is reloaded. Why this was so, still remain a mystery. 

![image](https://user-images.githubusercontent.com/7301249/71307490-81334c00-23ef-11ea-91aa-0b6b5a149db2.png)

**Comment by iulianpascalau** [comment]
Will take a look at this issue

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
