### ISSUE TITLE
Transfer to unavailable Wallet gives no error message

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#882]
When i'm about to manage balance for voting, i found one of my Wallet is unavailable, and then when i transfer to there hope it's back, it doesn't give error message, the Tx is success, and my balanced is decrease, even when i check the detail it says pending,,

tx hash
f375d040c96d1714665e0ffb6a3792ef894a790e658862d3d85ed7163be7244b

tx picture
![Untitled](https://user-images.githubusercontent.com/44559893/71309766-7eac1300-243e-11ea-8be3-e632eff9fbc2.png)

the unavailable Wallet are;
4c75f7b88add8d811814e93432e09e5181701a545ab0dec990cf43d002cf1ffc

**Comment by iulianpascalau** [comment]
This is a non-issue as you provided a valid address (in terms of character size) and the blockchain did the transfer. Will provide a way to have the addresses in bech32 format which (hopefully) will reduce the chance of making a transfer to a wrong address by mistake.
