### ISSUE TITLE
5 Tx continuously to an existing or non existing address on one shard make Wallet not handling certain input correctly

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#883]
Existing Wallet. 
3d7e858c6edb4deecab2b57fd3dfc08807e745a3ce7449d112e3feeb7f08fcd7

Existing Wallet Picture.
![Untitled2](https://user-images.githubusercontent.com/44559893/71310837-760e0980-244b-11ea-8d29-8d050895f991.png)

Non Existing Wallet. 
4c75f7b88add8d811814e93432e09e5181701a545ab0dec990cf43d002cf1ff1

Non Existing Wallet Picture.
![Untitled](https://user-images.githubusercontent.com/44559893/71310852-9b027c80-244b-11ea-8770-f0e1a080223d.png)

**Comment by iulianpascalau** [comment]
Can you tell us the details when making those transactions in terms of gas price, gas limit, value and other things? We need to be able to replicate the error as to be able to fix it. Thanks.

**Comment by scraido** [comment]
i didn't changes gas price and gas limit, i use min value with proper gas, the first 4th tx is success, but at the 5th time it will corrupt,,

it must do by the same wallet, at first i think this is some of tx spam protections, but when i just try it again and it happen on the 2nd transactions, i realize something, that if the balance is not refreshed to the remaining present balanced after the first Tx, this will happen,,

to be able to do the Tx again you must refreshed the balance until it substract to the present balance, then you can continue the Transactions,,

maybe you can add additional notice "please refresh the balance to view the remaining balance 
to be able to make a transfer"

I think it can disturb a little when some one / company want to do a transfer or payment to a several relation or business partner, they'll face this problem later,, Thank you

**Comment by elrondscammer2** [comment]
Binance Delist/ Don't Buy ERD/ELROND / Erd scam coin / Erd big dump
ERD BIG DUMP SELL NOW ...ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
