### ISSUE TITLE
Auto updater not working nicely with the wrong version tag (auto update "attack" loop)

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#885]
1.0.65 instead of v1.0.65

![image](https://user-images.githubusercontent.com/16723548/71312026-01c56d00-242f-11ea-819a-0b3c7e4b08bf.png)

Nodes rebooting / reinstalling multiple times in a loop,

![image](https://user-images.githubusercontent.com/16723548/71312254-59fd6e80-2431-11ea-8a0c-7edcd45a8dd8.png)

**Comment by soringp** [comment]
Issue identified as:
![image](https://user-images.githubusercontent.com/16723548/71312485-37208980-2434-11ea-867b-bedde4568bc2.png)

**Comment by iulianpascalau** [comment]
Will check for this. @valentin-lup

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
