### ISSUE TITLE
Minor Explorer issue - Next tx page button available when shouldn't

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#886]
Tx page contains 3 transactions as depicted here:

![image](https://user-images.githubusercontent.com/16723548/71314293-23821c80-244e-11ea-841a-214df7ce208f.png)

After pressing Next, I am greeted with this error:

![image](https://user-images.githubusercontent.com/16723548/71314249-6b547400-244d-11ea-8047-61b465913ce4.png)

The current node version is 1.0.65, and this address was filled to a previous value on the genesis file, if this makes any difference.

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
