### ISSUE TITLE
Proposal - PR for issue 42

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#887]
On the auto-updater i submitted issue 42 a while back, which is contingent on solving PR19.  Some common distributions, even more their VPS implementations, don't have sudo installed by default.  My proposed solution is to try detect if sudo is indeed installed (rather than needlessly add it tot the package list) and adapt the script accordingly.

Time : 1 week

**Comment by iulianpascalau** [comment]
Will take a look asap. @valentin-lup
