### ISSUE TITLE
Explorer can't find address if it has no tx yet

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#889]
It seems the new wallet can't find an address if it hasn't had any transactions yet, while it should show the address with zero transactions.  If you want to verify a recipient address before making a transaction, it looks like something is wrong.

**Comment by soringp** [comment]
It might be just an Elastic Search indexing thing, if an address is not used it's not stored.
I think you might have a problem only if the node or the API failed to give you a balance.

Here is what I get for a newly generated address:

https://wallet-api.elrond.com/address/245fd34b080ddacb13aa1511bbde38e00b469087f7522a7f0cd7377a267eeed4

![image](https://user-images.githubusercontent.com/16723548/71320899-c2446280-24ba-11ea-9fe0-186015811608.png)

And this is when I check using the node on the corresponding shard. 4 in this case:

curl --request GET --url http://localhost:8080/address/245fd34b08                                            0ddacb13aa1511bbde38e00b469087f7522a7f0cd7377a267eeed4

![image](https://user-images.githubusercontent.com/16723548/71320933-7e9e2880-24bb-11ea-9be0-1aded2c8325f.png)

So I'd say this is only a minor issue on the Explorer.

**Comment by koen84** [comment]
Thanks for these additions.  Though with mainnet imminent, therefore aiming for adoption (including less tech savvy people), i'd say having the webversion respond properly is not that minor.

**Comment by iulianpascalau** [comment]
@soringp is right. The protocol first searches the provided string as an address. If it does not find one will try to search the provided string as a tx hash. This will be improved when we are ready to implement bech32 address format.
