### ISSUE TITLE
Wallet balance & transactions not updating

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#890]
When an incoming transaction is processed, the wallet GUI isn't updating automatically the balance.

When manually refreshing the balance, the "latest transactions" don't equally refresh.

**Comment by iulianpascalau** [comment]
Will provide an answer to this

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
