### ISSUE TITLE
Proposal: Use Docker  to create, deploy, and run Elrond nodes

### ISSUE THREAD

**Issue by MarkWillems** [ElrondNetwork/elrond-go#891]
To lower the entrance to run a Node I propose to simplify the deployment with using Docker containers.

This will gives lightweight, portable, self-sufficient container, which can run virtually anywhere. However this is a bit of a marketing text, running a Docker container is a lot more user friendly then do the manual install (checkout, install dependencies, compile etc) yourself.

See [Docker](https://www.docker.com/) for more background.

**Some benefits of this solution:**
* Containers allow a developer to package up an application with all of the parts it needs, such as libraries and other dependencies, and ship it all out as one package. So upgrade of Go etc is a lot more easy.
* More standarized way of running nodes, therefore more knowledge can be shared.
* No more, or atleast a lot less, obscure enviroment problems.
* Jailing of Node resource pos* sible, so if you run more than 1 node on an VM, one Node can not steal all memory/cpu and take all nodes with it to crash.
* Container should open the doors to a lot of other Operating Systems.
* A lot of tooling like monitoring, restart, updating is allready developed.

**Some considerations:**
* How to integrate with the current official scripts, therefore the question is to build a compile node version image or build an image which automatic update the node binary with the official script (but like a mini vm). See things like [watchtower](https://github.com/containrrr/watchtower) to enabe updates with packed version binaries.

[EDIT]
I started it because I was working on a tool which automates the keygeneration and wraps terraform to create VPS stuff.

See https://github.com/MarkWillems/elrond-docker for the docker part. (Will finish jn coming days)

**Comment by iulianpascalau** [comment]
@LucianMincu

**Comment by raduchis** [comment]
is in development
