### ISSUE TITLE
Problem with shard 1 - rewards 

### ISSUE THREAD

**Issue by klanek007** [ElrondNetwork/elrond-go#892]
Shard 1 does not charge total rewards correctly, please check.
![IMG_20191222_120110](https://user-images.githubusercontent.com/32298908/71320952-4b579b80-24b3-11ea-8740-3536f258f02c.jpg)

He checked all the time and unfortunately the amount of funds does not match.

**Comment by iulianpascalau** [comment]
The values showed in termui are just the rewards gather by the node. There is the chance that the account will have more funds as the proposer collects the transactions fee.

**Comment by klanek007** [comment]
I do not quite agree with this, earlier you can observe the problem because it was also raised on the channel. And that was a global problem.

**Comment by iulianpascalau** [comment]
Removed the rewards gather by the node metric.
