### ISSUE TITLE
Proposal: Tool for deploying, managing and monitoring Nodes

### ISSUE THREAD

**Issue by MarkWillems** [ElrondNetwork/elrond-go#893]
**The idea**
The elrond-cli wil be a tool to manage nodes on your own computer/laptop. 

It acts as an interface to run node simultaneously on Azure, AWS, Google Cloud Vultr etc. Migrations to VPS should be easy and can managed through [Terraform](https://www.terraform.io/). With Terraform al the VPS specifics (network, VM, Ip, firewall) are handled and automaticly created.

The tool will run in  a Docker container.

***Phase 1***
There should be a website as UI (like [Elrond wallet prototype](https://github.com/ElrondNetwork/elrond-wallet-prototype))
-  To easy configure the unique nodes (name, keys etc).
- To easy add/delete virtual machines (name, vps (azure, vultr etc). 
- To configure on which VM to deploy a node (Azure VM, Vultr VM) 
- A console approach to request SSH acces based on your node names to the specific node. 

***Phase 2**
- Include a Prometheus and or Grafana
 - Include Grafana dashboard in the tool for displayed a lot of graphics embedded in the website/tool.
- Perhaps Ansible to furthere configure/harden/update nodes automatic.
- A lot more ideas

***See similar concepts:***
[Ren darknode-cli](https://github.com/renproject/darknode-cli)
[Harmony one-clike ](https://docs.harmony.one/pangaea/archived-obsolete/pangaea-archives/once-click-deploy-aws-only-mac-and-linux-only)

**Comment by iulianpascalau** [comment]
@LucianMincu

**Comment by raduchis** [comment]
is under development
