### ISSUE TITLE
Offline node receiving rewards - v1.0.65

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#894]
I'm not sure if this is an Explorer bug or a Protocol bug, but I found a node offline since v1.0.65 was released, registered as Validator in the nodesSetup.json file, receiving substantial rewards:

https://explorer.elrond.com/validators/8e1776c42b3a0c9cf435491f9428e5a365afcd285241ad0ddd982db4843e6df37313107db0dad8a4ece093bbe39684b90a33593e856725813bbbf408b064fac133ce3317ac8beaa1ea805be8556f09e11f99eeaa06f0e36f435c1afe20a70bad692c0759035eb0a4c3f6a29c4da1791aebc058911eec2151367ae515014303b2

![offline proof](https://user-images.githubusercontent.com/16723548/71328839-20f2f600-2526-11ea-8142-b588952abbb9.png)

https://explorer.elrond.com/address/1ed3c01d87730e3dbb6ce21bfcae4a209a9d18609432928c2b55f3c84538aaa4

![reward proof](https://user-images.githubusercontent.com/16723548/71328845-2f411200-2526-11ea-811b-6a3376210d43.PNG)

https://github.com/ElrondNetwork/elrond-config/blob/master/nodesSetup.json

![nodesSetup evidence](https://user-images.githubusercontent.com/16723548/71328847-323c0280-2526-11ea-8103-d65e482c2d57.PNG)

**Comment by iulianpascalau** [comment]
Will take a look at this

**Comment by raduchis** [comment]
We don't have the rating in place yet, and all validators in the consensus group are getting the rewards, whether they are online or offline .

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
