### ISSUE TITLE
Issue with the of Transaction History

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#895]
When the end of transaction history is reached and the **Next** button is clicked as shown in this screenshot
![image](https://user-images.githubusercontent.com/7301249/71341959-b0ff6280-255b-11ea-8112-adedf245a76a.png)

It will generate an error of unable to locate wallet address instead of **You have reached the end of the transaction history** or the button **Next** is disabled on getting to the EOF. 

Screenshot of error
![image](https://user-images.githubusercontent.com/7301249/71342262-86fa7000-255c-11ea-9998-6657a8c7733c.png)

**Comment by iulianpascalau** [comment]
Duplicate, as found by @soringp #886 will move the discussion there
