### ISSUE TITLE
Proposal: Google Chrome wallet extension

### ISSUE THREAD

**Issue by SebastianJ** [ElrondNetwork/elrond-go#896]
It would be great to have a Chrome extension that would allow you to interact with Elrond's blockchain.

Here are some features it could include:

**Phase 1**
- Import/Export (multiple) keys/accounts
- Send regular transactions
- Quickly take you to your wallet on the explorer

**Phase 2**
- Staking and delegator functionality
- General smart contract interactions
- Web3/dAPP integrations

**Timeline:**

- **Phase 1:** 2-3 weeks of development and testing.
- **Phase 2:** Very much dependent on scope - very hard to estimate right now.

**Comment by iulianpascalau** [comment]
Thanks, we are thinking of a solution to this proposal. :+1:

**Comment by iulianpascalau** [comment]
Currently, we are not taking into account creating a google chrome extension. Will reopen if we reconsider this.

**Comment by fajzen** [comment]
@iulianpascalau are you still decided to not create google chrome/firefox/brave extension? I really think you should reconsider this - browser extension is the easiest and secure way to interact with dApps
