### ISSUE TITLE
Proposal: Please included ./script.sh start at installation

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#897]
Hi i realize i keep forgot to start the node, so could you included the ./script.sh start at installation, as you included ./script.sh stop at cleanup,,

Also if you don't want it do automatically, you can gave people options (Yy/Nn), like the Autoupdater,,

Ty very much for the approvement

**Comment by raduchis** [comment]
./scripts upgrade  fixes this
