### ISSUE TITLE
Logging this just in case T.W.E.R.P.S Defender breaks anything

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#898]
10 minutes before Monday 23 Dec, 12:00 UTC, I'm turning on my Mission 6 defence tool, written in GO.

It will monitor 11 wallets, first 6 will offload any contained balance to other intra-shard wallets, then these 5 will be monitored and ERD transferred to my article campaign address 640e7e30c684aafc3c959881b38ee6bc510798267e7cdc78a314f05ae5294a40.

All transactions are marked with txData 'T.W.E.R.P.S Defender'

This is not an attack, we're in Cease-Fire interval, but I have the right to defend myself for Mission 6.

I will publish the code used if needed to reproduce any potential issues.

Thanks

**Comment by iulianpascalau** [comment]
Great! :+1:

**Comment by soringp** [comment]
![image](https://user-images.githubusercontent.com/16723548/71357503-b0cc8a80-258e-11ea-8758-f3d7187d8147.png)

Defender in action, didn't seem to break anything :)) Currently defending 6.

Turtle: 5f06bfe68e78edc52bc642e2bfc56074b98678e7219cfeacfdb6b45fbcf23442

Weasel: 767b0cfd471501c760d3338e5dcb16836f7e9cd7366387851b92022ac6cba020

Eagle: cf51fc9eab73998545e2390a563c7a11603e37d0b581ee18bd1c5b1dc1343563

Raven: 1f59999f81032463036b7414ab65ffbca003542582ec78ebd8032c44ddc7024c

Panda: 0f66deababd94d0de7fc205fed533f5bc6a31f9f21f3889f793f8f742ef3f41b

Snake: 84fb6cd51e5b5e0c557018bd869a953e645d4e58de0e562acd42f6dd6e0ed2e4

**Comment by iulianpascalau** [comment]
BoN mission ended, this issue will be closed
