### ISSUE TITLE
logout wallet on another tabs or windows doesn't logout the first login wallet

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#902]
Hi i'm realize, when we have open one wallet (say it wallet 1), and then open the wallet.elrond.com on another tabs / windows to open another wallet (say it wallet 2), we will prompt to logout the wallet 1, but in fact the wallet 1 is not logged out (on the first login tabs/windows), this can be disadvantage user if he/she open the wallet on public or office and forgot to logged it out.

It should when he forgot to logged out, he can logged it out remotely, by open the same wallet and then logged out it (logout one will logout all opened wallet remotely on all machines).

Or give wallet the ability to close it self (_[session lifetime](https://github.com/ElrondNetwork/elrond-go/issues/912)_) to 1 or 2 minutes, when it didn't used, Ty

![wallet-standby](https://user-images.githubusercontent.com/44559893/71465939-985baa80-27f0-11ea-9927-5d9d648b8194.png)

![wallet-do-not-logout](https://user-images.githubusercontent.com/44559893/71370223-d46bf100-25df-11ea-8595-9978534bf7b1.png)

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
