### ISSUE TITLE
Tx Age on explorer is not updated

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#903]
Hi just realize when i want to know when was the last time of vote happened on my article wallet, so i can know the balanced that taken by snapshot, and i can't knowing it as the Tx Age is keep changing from time to time, and then back again,,

![new2](https://user-images.githubusercontent.com/44559893/71375130-c8882b00-25ef-11ea-8779-461a3c494d42.png)

**Comment by miiu96** [comment]
termui console is not synchronized with the wallet . There you see a estimation of how many rewards you earned (this estimation is without fees)

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
