### ISSUE TITLE
Total Reward on Termui is not Reflected with Present Wallet Balances

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#904]
As i've empty my metachain and then starting over my metachain node to know how it goes i found that my Termui Total Reward is not the same with my Present Balances on metachain wallet, or there were mechanism that i didn't know? but the CLI balance must be reflected by the wallet balance where ever they are isn't it? Thank you for answering

![totalreward](https://user-images.githubusercontent.com/44559893/71375736-cfb03880-25f1-11ea-9b77-e2d4a38f45bb.png)

**Comment by klanek007** [comment]
It probably doesn't work like that and it won't work, after each restart the values change, there is no synchronization with the wallet :)

**Comment by miiu96** [comment]
termui console is not synchronized with the wallet . There you see a estimation of how many rewards you earned (this estimation is without fees)

**Comment by iulianpascalau** [comment]
Removed rewards gatherings metric as it is no more relevant.
