### ISSUE TITLE
Proposal: Auto delete database script that run after certain range of time 

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#905]
Hi in this battle field i realize the auto updater just delete database when it come a new patch, some time the patch didn't come, and the node can be killed by the host because of run out of capacity,,

As on VPS some time the storage price is separated from machines/instances, can you made run an autoscript that detect the use of HDD, and if it touch some value, it stop the node, clean up the database (only the database), and then run it again, so we can push the vps spending by just using the bundled capacity, Thank you

**Comment by iulianpascalau** [comment]
The node will have the ability to prune its storage data. In our tests we ran the blockchain with this feature turned off.

**Comment by scraido** [comment]
since when?

**Comment by iulianpascalau** [comment]
Storage pruning and start in epoch is on since v1.0.112 - BoNwards 46. So this issue should be fixed by now.
