### ISSUE TITLE
Proposal: Create a client for Windows users.

### ISSUE THREAD

**Issue by Mystic999** [ElrondNetwork/elrond-go#906]
A small program that would allow you to easily control the operation of the nodes. The client will know where the ssh keys from the VPS are located locally. Independently connect to remote servers, monitor nodes.

Each connection window should be inside the program window and divided into several sections. Section where you can see all the Windows working remotely nodes, the window where each node can be seen separately. This will be very convenient for Mainnet. We expect a large number of new node operators. Their technical knowledge may not be sufficient to use the nodes, as they did not participate in BoN. Most people use Windows 7-10.

The program should also have its own folder for safe storage of PEM keys. You can also add buttons to restart the node, force update, stop, and start. A separate window that tracks the balances and returns of each node.

All scripts should be integrated into the program, including BonMonitorBot features and other useful tools. For ssh connectivity you can integrate into the PowerShell client or any other free open source ssh utility

**Comment by iulianpascalau** [comment]
At the current moment we are not supporting Windows for a platform to deploy your nodes on. Creating a windows tool for monitoring is not our main focus right now. Will close this issue now.
