### ISSUE TITLE
Proposal: Make Shard can run and do consensus in min. amount of Node for running on that Shard

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#909]
As every time we start a new round with a new blockchain, and with a small number of participants, that with it, it couldn't make our Nodes started work, so this can be a gap for initial and main attacks on a group of nodes and shards

This; 
[Concept Attack 1](https://github.com/ElrondNetwork/elrond-go/issues/910)
[Concept Attack 2](https://github.com/ElrondNetwork/elrond-go/issues/911)

**Comment by iulianpascalau** [comment]
This proposal is a security breach. Will not be implemented. Closing.
