### ISSUE TITLE
Little Boy Attack Concept Could Make Shard Paralyze

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#910]
Known Bug so Far
1st think we know that if the amount of Node that runs is not much so the Shard wouldn't operate and we also know if HDD Full, The Node will be Freeze or Auto Killed by Server so The auto updater couldn't get it back

_As long as my proposal to auto deleted database / log file when reach some of capacity amount is not approved, so maybe this Attack Concept can be apply_

What is Little Boy Attack
Like Little Boy that dropped at a City (Node) and can paralyze the Whole Island (Shard), so i get inspired of this Concept, that if we send a Tx that continuously with fast speed or medium speed with greater amount, to a series of Random Node that we pick before, with enough amount of Node to die so can make shards stop working when the chosen Nodes all are die, which is when all of their Capacity is Full and it makes it Freeze or be killed by the host, so the Shard will paralyze

The Purpose of the Attack
They were 2 purpose, one is to make the chosen Node die (killed/freeze) because HDD out of space, and the main purpose is to make the Shard not active because the node for operate is not enough

Prevention
Proposal [#905](https://github.com/ElrondNetwork/elrond-go/issues/905)
Proposal [#908](https://github.com/ElrondNetwork/elrond-go/issues/908)
Proposal [#909](https://github.com/ElrondNetwork/elrond-go/issues/909)

![littleboy](https://user-images.githubusercontent.com/44559893/71464642-bf17e200-27ec-11ea-9a61-0889eb568d21.png)

**Comment by iulianpascalau** [comment]
This will not apply as soon as the antiflood component will be in place. Work on the antiflood component started way back in November 2019 and is expected to be integrated in the main branches in about 1 week.

**Comment by elrondscammer4** [comment]
Crooked sons of bitches. Give us our money back.
 BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD

**Comment by iulianpascalau** [comment]
Fixed thanks to the antiflood subsystem. Reference PR #787
