### ISSUE TITLE
Known Security Hole being used, System of a Down; Fat Boy Attack Concept

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#911]
What is Fat Boy Attack
Is another Little Boy Attack but thoroughly on all shards

The Purpose of the Attack
To made Elrond testnet blockchain paralized

see [Little Boy Attack Concept](https://github.com/ElrondNetwork/elrond-go/issues/910) for further information

Prevention
Proposal [#905](https://github.com/ElrondNetwork/elrond-go/issues/905)
Proposal [#908](https://github.com/ElrondNetwork/elrond-go/issues/908)
Proposal [#909](https://github.com/ElrondNetwork/elrond-go/issues/909)

**Comment by iulianpascalau** [comment]
Can not be applied when the antiflood component will be available.

**Comment by iulianpascalau** [comment]
Fixed thanks to the antiflood subsystem. Reference PR #787
