### ISSUE TITLE
Proposal: Add min. session lifetime for wallet for auto closed if it not in use

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#912]
Regarding to this issue [#902](https://github.com/ElrondNetwork/elrond-go/issues/902), please add min session lifetime when wallet were not in touch in 1 or 2 min., to auto closed, Thank you

**Comment by miiu96** [comment]
Will be fixed on the new web wallet version.

**Comment by scraido** [comment]
hello bro, when it's not a bug and you said it will be fixed soon, could you considered the label as an enhancement? ty brother,,

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
