### ISSUE TITLE
Proposal: Add ability for wallet to log out on All Machine or give option on Wallet to do so

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#913]
As of before issue,[#902](https://github.com/ElrondNetwork/elrond-go/issues/902), i think it's important to add wallet this ability or we can manually do it by press button on our wallet administration page, Thank you

**Comment by miiu96** [comment]
Will be fixed on the new web wallet version.

**Comment by scraido** [comment]
hello bro, when it's not a bug and you said it will be fixed soon, could you considered the label as an enhancement? ty brother,,

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
