### ISSUE TITLE
Proposal - create zip archive of new pem sets in autoupdater

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#917]
When the function "keys" is called, it's checking if a zip file exists for that index.  If yes it uses it, otherwise it generates new keys.  This proposal is about writing a PR that would amend this function that when keys don't exist yet, it'll create the zip archive, so it can be used when it gets called again.  This also allows easier backup for any and all keys used.

**Comment by iulianpascalau** [comment]
No longer required as the node now needs only one pem file. Nice heads-up although.

**Comment by elrondscammer4** [comment]
Binance Delist/ Don't Buy ERD/ELROND / Erd scam coin / Erd big dump
ERD BIG DUMP SELL NOW ...ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.

**Comment by raduchis** [comment]
autoupdater is disabled
