### ISSUE TITLE
Proposal: Split Wallet for receiving Staking Reward and the Consensus Wallet

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#918]
Regarding to CLI Wallet it's attempt for disguise from the attacker, so every user will get their Staking Reward that just only they and the company that know it (the .pem file), so every think happen on shard or Node, it wouldn't harm the real staking balance and also the staking reward wallet, this all if you decide to make CLI Wallet

**Comment by iulianpascalau** [comment]
This is currently implemented in our delegation SC. Regarding CLI wallet, we have developed erd-py and erd-js clients. Will close this issue.
