### ISSUE TITLE
Proposal: add Desktop Wallet for more privacy

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#920]
I found in the future that desktop wallet will made user fill comfortable and save, as if in web, Some one just can try to attack the database and changed their balance amount and withdraw it

**Comment by miiu96** [comment]
wallet does not have a database because it takes information from proxy about account balance and this information about balance it is saved in blockchain.

**Comment by raduchis** [comment]
This is not how a blockchain works. There is no single database that can be changed and the other nodes in the network will not accept the change.
