### ISSUE TITLE
Proposal: add withdrawal prevention if balance withdrawed is not the same as the last balance snapshot

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#921]
I found out in last accident on korean exchanger, some one with ability to play with database can do this kind of stuff, it will very helpful later, thankyou

This can make culprit without history of incoming balance couldn't do withdrawal and be locked out on that wallet

**Comment by iulianpascalau** [comment]
Not required for the layer one protocol. It is needed only on centralized exchanges.

**Comment by iulianpascalau** [comment]
Will close. Irrelevant to what we are building.
