### ISSUE TITLE
Database Injection on web wallet Concept Attack

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#923]
Method.
Database Injection like some kind of SQL Injection or with other program

The purpose of the attack 
To change balance amount of one wallet and withdraw it on the functioning wallet in the future

Prevention
Proposal #920
Proposal #921 
Proposal #922

**Comment by raduchis** [comment]
The balance of the wallet does not exist in a single database. It is stored on the decentralized blockchain and the only way to change that everywhere is through a transaction.
