### ISSUE TITLE
Web Wallet Phising Concept Attack

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#924]
Method.
Making fake login page to lure user to login using their credential or .pem file, infact they'll never login but sending their logon data instead of login & they'll bring to the real login page, but without realizing that they've send their data to the culprit web or email

The purpose of the attack.
To steal all of user wallet balance

Prevention.
Proposal #921 
Proposal #922 
Proposal #928

Just incase if someone not whitelisting his/her ip; Proposal #929

**Comment by raduchis** [comment]
This can happen on any website if you are not paying attention and login with user and password on a fake login site.

**Comment by scraido** [comment]
what i mean on above is, instead of making fake login site, they changes yours, so every .pem & password user submit is send to theirs

**Comment by iulianpascalau** [comment]
And how can someone change our website? If you do not trust our website, you can use erd-py and erd-js tools to safely request data from the blockchain. Or safer: you can build your own tools for this purpose. Closing: irrelevant.
