### ISSUE TITLE
Proposal: add honey pot on wallet login page to prevent unwanted login

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#925]
When i realize our wallet is web based i'm thingking about this a bit, that culprit can try to login with some apps, so can you add honey pot on hidden field, so some one with app can't login coz when we add honey pot, something that can't be seen by human, Will be seen by robot, and when it detect and fill it, on the contrary web system will prevent it to log and banned the ip, thank you

**Comment by elrondscammer4** [comment]
That's enough!! Cheating bastards.
The price keeps falling. People don't trust you. ERD doesn't buy. What do you boys do for a living?

**Comment by iulianpascalau** [comment]
We do not have a backend that can be "hacked". All the information you see on the web page is presented by a frontend in front of our tools that directly communicate with the blockchain. Will close this for now.
