### ISSUE TITLE
Web Wallet Brute Force Concept Attack

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#926]
Method.
People with knowledge to try to login with some apps can try to Brute Force for login, with many of apps available and we can choose for trying to login

The purpose of the attack.
To steal all of user wallet balance

Prevention.
Proposal #922 
Proposal #925 
Proposal #927 
Proposal #928 

Just incase if someone not whitelisting his/her ip; Proposal #929

**Comment by raduchis** [comment]
Brute force a 256 bit private key? It will take some time.
