### ISSUE TITLE
Proposal: make balance notification monitoring

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#929]
Please made some official bot or app that can track our last balance, and also reporting it directly to that bot or wallet when the balance is withdraw to some address also with information of the address the balance has withdraw to, it's more useful if we can directly report it to admin by giving user some button for reporting it, so user not have to open another program for bring able to report, the report it self sended not just to admin tele but also cc on email, for more reach out, ty

**Comment by miiu96** [comment]
nice idea. we will discuss and maybe this app will be implemented soon.

**Comment by scraido** [comment]
hello bro, when it's not a bug and you said will be implemented, could you considered the label as an enhancement? ty brother,,

**Comment by iulianpascalau** [comment]
What is the main purpose of knowing who stole your funds at that exact moment? The process is irreversible. If you are careless about your keys, someone will steal your funds. Closing: irrelevant.
