### ISSUE TITLE
Proposal: Automation friendly Node Deploy Scripts

### ISSUE THREAD

**Issue by MarkWillems** [ElrondNetwork/elrond-go#940]
The current node deploy scripts (Elrond Node Deploy Scripts V2) require user input to execute succfully.  While this forks fine for manual installation, it does not scale well with automation scripts to deploy. This proposal is to extend the scripts to support automation with more conventions.

* Add an unattend.sh (or something) which reuses most of the functions.

* The config/variables.cfg file should not be required, the variables should be read from environment variables or fall back to a default convention (like user elrond).

* The VALIDATOR_KEYS directory should be there, but instead of a node-0.zip the proposal should be subdirectories which contains the node name. The directory expects a initialBalancesSk.pem and initialNodesSk.pem file.
```
/home/elrond/VALIDATOR_KEYS/beast-1/initialBalancesSk.pem
/home/elrond/VALIDATOR_KEYS/beast-1/initialNodesSk.pem
/home/elrond/VALIDATOR_KEYS/beast-2/initialBalancesSk.pem
/home/elrond/VALIDATOR_KEYS/beast-2/initialNodesSk.pem
```
The name of the node is derived from the directory name, which are based on conventions. The name accepted is [name]-[id]. The Id is used to determine the rest api port, which is 8080 + [id].

* Maybye the cleanup/install  functions should clean node which names/directories no longer exist.

[EDIT]
I started it because I was working on a tool which automates the keygeneration and wraps terraform to create VPS stuff.

See https://github.com/MarkWillems/elrond-docker for the docker part. (Will finish jn coming days)

**Comment by iulianpascalau** [comment]
Nice heads-up. I'm sure this will delight @valentin-lup

**Comment by raduchis** [comment]
is under development
