### ISSUE TITLE
Sharding Seems to be stucked without prompt recovery of Node

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#953]
The New sharding that was implemented in the version 1.0.73 seems not to be recovered. I have watched shard 1 and 3. Screenshot of Shard 3 is pasted below to be dwindling between 5248 and 5246 nonce without progressing for complete 10 minutes. 

I thought shard should auto-recover as at now and this experience seems strange to me.

![image](https://user-images.githubusercontent.com/7301249/71973568-8e35a500-320f-11ea-9713-0446764af437.png)

The system status of the node is running as expected
![image](https://user-images.githubusercontent.com/7301249/71973750-11ef9180-3210-11ea-926f-a398943b2a30.png)

**Comment by iulianpascalau** [comment]
There were some issues regarding syncing of new blocks. Thanks for the heads-up.

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please reopen a new issue if the problem persist.
