### ISSUE TITLE
Node stuck offline after internet loss v1.0.74

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#964]
For some reason, my router lost WAN connection and couldn't reconnect so I've rebooted it. The Internet was back ON.
I have two machines running nodes at home, the nodes on one of them reconnected to the network but the node on the second machine is still stuck offline.

![image](https://user-images.githubusercontent.com/16723548/72202636-99d0d800-346a-11ea-89e7-a447527581ea.png)

This doesn't appear to be a shard issue as I have another node on a VPS on shard 0, and that one is running just fine:

![image](https://user-images.githubusercontent.com/16723548/72202656-d7cdfc00-346a-11ea-82a1-9e475723dc5e.png)

Node reconnected after manual restart:

![image](https://user-images.githubusercontent.com/16723548/72202993-b1aa5b00-346e-11ea-813c-f92c84df9a21.png)

Here is the node folder if needed for inspection:

https://drive.google.com/open?id=1Es-Dj3QmEMqgVsnQp7jm9c96xMgXfglk

**Comment by soringp** [comment]
It happened again, on 1.0.81, I've had a power loss, internet reconnected, one node on the machine reconnected, the other didn't. 
My IP changes on internet reconnect if this makes any difference.

![image](https://user-images.githubusercontent.com/16723548/72734722-fdfa4700-3ba2-11ea-8bd6-17b2c005cb6b.png)

**Comment by soringp** [comment]
Could this be a side effect of the anti-flooding mechanism?

**Comment by iulianpascalau** [comment]
Antiflooding mechanism is not enabled as of today. This is a known bug that is incredibly hard to hunt down. Since you brought this up, I have a question regarding this problem: does your nodes use a hardcoded value for port in p2p.toml? If this is hardcoded (such as 23000) it might happen when the nodes restart as they try to reuse the TCP port that was not "fully" closed by the last instance. If the value in your toml files is 0 we are back on the drawing board...

**Comment by soringp** [comment]
I'm running a standard setup, with port set to 0.
Maybe you can implement a periodic node auto-restart if no peers connected as a workaround.
I thought maybe it caches the old IP address and sends it to the peers and they reply to the wrong address.
Maybe you can play with your internet connection while on debug, maybe you'll notice something useful. Maybe try it at home where the external IP is dynamic.

**Comment by iulianpascalau** [comment]
This should be fixed with the new version of the libp2p libraries implemented. Please open a new issue if the problem persist. Reference PR #1553
