### ISSUE TITLE
Node cannot be started or stopped with script.sh

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#965]
I'm running the latest script version, installed after a cleanup, node started with ./script.sh start.

Now for some reason, the stop command doesn't work:

![cannot stop node](https://user-images.githubusercontent.com/16723548/72203035-43b26380-346f-11ea-8dd4-daf538997885.png)

Stop worked using sysctl:

![worked with sysctl stop](https://user-images.githubusercontent.com/16723548/72203039-4d3bcb80-346f-11ea-83af-c79e1e2e1a51.png)

Start doesn't work either:

![start doesnt work either](https://user-images.githubusercontent.com/16723548/72203043-5dec4180-346f-11ea-90d8-a3a5f9313fb6.png)

It appears that variables.cfg has reverted to the original values:

![image](https://user-images.githubusercontent.com/16723548/72203075-ab68ae80-346f-11ea-81d8-cd469f5be0b4.png)

**Comment by soringp** [comment]
Both my home pc's have the config reverted, but not my VPS.

**Comment by soringp** [comment]
It happened again, home pc's reverted to /home/ubuntu and my node didn't update from 1.0.81 to 1.0.82. The vps's updated just fine.
Could this be caused by my Canonical Livepatch being active? Or is this a bug with the updater.

**Comment by iulianpascalau** [comment]
looks like a bug in scripts. @valentin-lup ?

**Comment by iulianpascalau** [comment]
scripts were refactored. Thanks
