### ISSUE TITLE
could not create txpool and shard data pools: not supported cache type

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#972]
I received notification that all my nodes were offline. I thought there was a new patch until Sever told me that the patch is still on the way. Thus, made me to login to my VPS to see what is happening. I cannot connect to the dashboard with an error of connection refused. I look at the log view and there seem to be an issue with creating shard data pools with the following errors
![image](https://user-images.githubusercontent.com/7301249/72255582-65dee980-3607-11ea-9f7d-ef746db15545.png)

**Comment by bogdan-rosianu** [comment]
Hello !
This error messages most of the time appear because of a bad config. Can you check if there is an old config.toml ?

**Comment by iulianpascalau** [comment]
This should be fixed as of today 2020.05.15. Please open a new issue if the problem persist.

**Comment by supersheepshaker** [comment]
Hi there, is this the same issue? Just installed my first node
![image](https://user-images.githubusercontent.com/63821913/84198248-8c645c00-aaa3-11ea-9863-5fc38f72e4c0.png)
