### ISSUE TITLE
Node doesn't sync after VPS reboot v1.0.77

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#986]
I had to reboot my VPS, I have three nodes on it, it was down for 15 min.
I've started all nodes with script.sh start.
Two of them started syncing right away, but the third, on Shard 2 didn't:

![image](https://user-images.githubusercontent.com/16723548/72427479-7b354e80-3794-11ea-9494-80b55bb626c3.png)

Node started 26 min ago:
![tempsnip](https://user-images.githubusercontent.com/16723548/72428011-8a68cc00-3795-11ea-91a1-edc1d17da200.png)

I've noticed a delay on another node on a previous version, started sync with a few minutes delay, but not this long.

Node DB: http://s.go.ro/bn9fp5ea | password: 858866

I've restarted the node manually and doesn't sync, but I see the last block as 5209 instead of 5210.

I have another shard 2 node, synced at 5209. The shard might be stuck after all but is the sync normal not to happen in this case?

![image](https://user-images.githubusercontent.com/16723548/72429201-0a903100-3798-11ea-8ce0-e74447dc50d8.png)

**Comment by soringp** [comment]
After restarting the node it started syncing again after a few minutes:

![image](https://user-images.githubusercontent.com/16723548/72430384-df5b1100-379a-11ea-8a4b-fb9e51601f99.png)

**Comment by iulianpascalau** [comment]
We have identified some problems regarding saving data on bootstrap storage unit. They were corrected. Thanks for the heads-up.

**Comment by elrondscammer4** [comment]
Crooked sons of bitches. Give us our money back.
 BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
